### ISSUE TITLE
Name cluster connection with "connection.name" to have a user-name in M&M

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#1026]
The server team as set a new property to use when creating a voltron connection. You can set `connection.name` (optional) to set the user-name for a logical connection to a cluster.

M&M will use this name to display the clients.

@chrisdennis / @ljacomet suggested Ehcache could set this property to something like `EHCACHE:<cm-name>` when creating the connection.

CC @cljohnso

**Comment by ljacomet** [comment]
I see PR #1031 already takes care of the default.
In the context of this issue though, we want to think about a public API allowing users to name their connection, which would then override the default.

**Comment by chrisdennis** [comment]
Is this really what we want?  Maybe I've gotten out of sync on this issue.  To my mind:

"Ehcache:NameOfMyCacheStorageInTheCluster" - tells me what the connection is doing
"HotelBookingJettyInstance-43" - tells me what the greater purpose of the connection is.

I had hoped this wouldn't have to be an either/or decision on which of these we expose.

**Comment by mathieucarbou** [comment]
Form latest discussion, we defined the `connection.name` to be a user-defiend string that can be anything but that will represent for what the cluster connection is used for.

Ehcache would then use the name: `Ehcache:my-cache-manager-name`

This is sufficient to know that the connection will only be used by Ehcache in the context of my-cache-manager-name.

If several webapp on the same app server / JVM is using the same name `Ehcache:my-cache-manager-name`, will be able to differentiate these different clients thanks to the `connection.uuid`

In M&M a client is identified by this user string: `PID@ADDRESS:NAME:CONN-UUID`

After that, we will add the ability to set some tags. The tags will allow us to regroup clients based on tags for logical views. So tags could be: `HotelBookingJettyInstance-43, appserver-node-1` for example

**Comment by mathieucarbou** [comment]
Does the above explanation makes sense @ljacomet @chrisdennis  ?
(CC @anthonydahanne)

**Comment by chrisdennis** [comment]
Yes.

**Comment by mathieucarbou** [comment]
Closed by #1031 ?
