### ISSUE TITLE
XSD reference glitch in web site documentation

### ISSUE THREAD

**Issue by snicoll** [ehcache/ehcache3#1040]
I guess those alternative paths were not expected:

![ehcache](https://cloud.githubusercontent.com/assets/490484/15136240/dd1909e6-167f-11e6-86ee-5cf445678fc6.png)

**Comment by ljacomet** [comment]
Thanks for the report - documentation has been updated with proper URLs for finding the XSDs.

**Comment by ljacomet** [comment]
Fix done through PRs #1041 and #1042
