### ISSUE TITLE
unable to reuse the cache file after a jvm quit

### ISSUE THREAD

**Issue by shapowang** [ehcache/ehcache3#1066]
I'm try to use ehcache3 as a small database to persistent my serialisable java objects

1    private static CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
            .with(CacheManagerBuilder.persistence("ehcache_db"))
            .withCache("proxyCache", CacheConfigurationBuilder.newCacheConfigurationBuilder(String.class, AvailableProxy.class, ResourcePoolsBuilder.newResourcePoolsBuilder().disk(100, MemoryUnit.MB, true)))
            .build(true);
2.put some cache into "proxyCache",wait until the ehcache3 persistent thread die and the application quit
3.restart the application ,try read old cache info from "proxyCache",but it's new and empty.

logs as below:
Connected to the target VM, address: '127.0.0.1:51118', transport: 'socket'
10:39:12.376 [main] DEBUG org.ehcache.impl.persistence.DefaultLocalPersistenceService - RootDirectory Locked
10:39:12.387 [main] INFO org.ehcache.core.internal.service.ServiceLocator - All Services successfully started.
10:39:12.388 [main] INFO org.ehcache.core.EhcacheManager - Cache 'proxyCache' is getting created in EhcacheManager.
10:39:12.407 [main] INFO org.ehcache.impl.persistence.DefaultLocalPersistenceService - Reusing /Volumes/sdk/bottle/pluginsPro/ehcache_db/proxyCache_51da15dcfb3bca73d696eb0ab11109a8e4f18e25
10:39:12.411 [main] INFO org.ehcache.impl.persistence.DefaultLocalPersistenceService - Reusing /Volumes/sdk/bottle/pluginsPro/ehcache_db/proxyCache_51da15dcfb3bca73d696eb0ab11109a8e4f18e25/DefaultSerializationProvider-Key
10:39:12.411 [main] INFO org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider - Serializer for <java.lang.String> : org.ehcache.impl.serialization.StringSerializer@69a10787
10:39:12.414 [main] INFO org.ehcache.impl.persistence.DefaultLocalPersistenceService - Reusing /Volumes/sdk/bottle/pluginsPro/ehcache_db/proxyCache_51da15dcfb3bca73d696eb0ab11109a8e4f18e25/DefaultSerializationProvider-Value
10:39:12.439 [main] INFO org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider - Serializer for <com.proxy.AvailableProxy> : org.ehcache.impl.serialization.CompactPersistentJavaSerializer@4f9a3314
10:39:12.447 [main] INFO org.ehcache.impl.persistence.DefaultLocalPersistenceService - Reusing /Volumes/sdk/bottle/pluginsPro/ehcache_db/proxyCache_51da15dcfb3bca73d696eb0ab11109a8e4f18e25/offheap-disk-store
10:39:12.558 [main] WARN org.ehcache.impl.internal.store.disk.OffHeapDiskStore - The index for data file ehcache-disk-store.data is out of date by 2896037ms, probably due to an unclean shutdown. Creating a new empty store.
10:39:12.640 [main] INFO class org.ehcache.core.Ehcache-proxyCache - Initialize successful.
10:39:12.641 [main] INFO org.ehcache.core.EhcacheManager - Cache 'proxyCache' created in EhcacheManager.
10:39:12.641 [main] INFO org.ehcache.core.EhcacheManager - Initialize successful.

stackoverflow has the same questions of ehcache2.x:
http://stackoverflow.com/questions/1729605/ehcache-persist-to-disk-issues
most answers point out I should use "CacheManager.getInstance().shutdown();" 

But after explore the source code of ehcache3 CacheManager and it's sub interfaces and sub classes,I can't find the shutdown method.

what should I do?

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3. Note that we ask that questions go to the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) instead of issues directly.

Now, to answer your question:
There is a `CacheManager.close()` method, which is what needs to be invoked in order to guarantee proper shutdown of persistent caches.

Note also that using `.with(CacheManagerBuilder.persistence("ehcache_db"))` enables you to receive a `PersistentCacheManager` which is the type that will allow you to destroy persistent storage when needed.

As a final note, your opening sentence:

> I'm try to use ehcache3 as a small database to persistent my serialisable java objects

raises all kind of alarms.
Between expiry and eviction, Ehcache really is a caching library for temporary storage. Your application needs to have the necessary logic to react when a mapping is not present in cache. Assuming anything else will cause problems ahead.

**Comment by shapowang** [comment]
Hello,

Sorry for my bad spellings.

In fact ,the feature I want is available in Enterprise Ehcache.
http://www.terracotta.org/documentation/3.7.4/enterprise-ehcache/fast-restart

Did the open source version of Ehcache 3 have the ability to restore the cache data from the file after an application restart?

I know there exists `CacheManager.close()`,but that is not what I want because this method remove all the cache data.

Ehcache 3 just didn't has this feature ,right?

**Comment by shapowang** [comment]
Hi,

I just found the document.

>"localRestartable" — Enables the RestartStore and copies all cache entries (on-heap and/or off-heap) to disk. This option provides fast restartability with fault tolerant cache persistence on disk. This option is available for standalone Enterprise Ehcache only.

Should I close this issue now?

**Comment by ljacomet** [comment]
> I know there exists CacheManager.close(),but that is not what I want because this method remove all the cache data.

This is incorrect - if your data is persistent, this does not remove it.

Now it is true that the open source disk store is not crash proof and not designed for fast recovery. If that is your use case, then indeed the open source solution falls short.

**Comment by VancouverK** [comment]
how to  "restart a cache with previous mappings"
Previously having one index file, but after one incorrectly shutdown and i reboot my program, the data on disk has been wiped.

**Comment by henri-tremblay** [comment]
@VancouverK You are asking an unrelated question (probably using Ehcache 2) on a closed issue. This is inappropriate in many ways. Please use the [Ehcache mailing list](https://groups.google.com/forum/#!forum/ehcache-users) instead and try to give a full and concrete example of what your issue is.

**Comment by haqer1** [comment]
FYI: I encountered the same issue as the one @shapowang mentioned when using XML config. Then tried with Java-API-based config, & it worked as @ljacomet said it did. So i logged https://github.com/ehcache/ehcache3/issues/2876.
