### ISSUE TITLE
Implement remaining CRUD ops for ClusteredStore

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#1075]

**Comment by ljacomet** [comment]
* `containsKey(K key)`
* `remove(K key)`
* `clear()`

**Comment by ljacomet** [comment]
A few things to add:
* Statistics
* Proper return value - thinking put here but may apply to others

**Comment by ljacomet** [comment]
Still need clean up on the clear message that _wastes_ 8 bytes for a long key that is not used.

**Comment by albinsuresh** [comment]
The `Clear` message and `ClientInvalidationHashAck` message that got added in #1007 has an extra long field in their types for the key that they got inherited from the `ServerStoreOpMessage` in the hierarchy. Even though the extra 8 bytes is not sent over the network at least for the`Clear` message the message hierarchy requires some refactoring to eliminate it from the type level itself. Working on fixing this hierarchy.
