### ISSUE TITLE
UserManagedCacheBuilder: cannot add Expiry

### ISSUE THREAD

**Issue by fgil55** [ehcache/ehcache3#1086]
Hello, I think I have found a problem with the UserManagedCacheBuilder DSL. I am not able to define any expiration if I try to build the cache with key/value classes other than java.lang.Object (ehcache 3.0.1 from Maven central). 

If you see the source from class CacheConfigurationBuilder, you can see:

`public CacheConfigurationBuilder<K, V> withExpiry(Expiry<? super K, ? super V> expiry) `

But with UserManagedCacheBuilder, the equivalent method is:

`public final UserManagedCacheBuilder<K, V, T> withExpiry(Expiry<K, V> expiry)`

Doesn't the parameter 'expiry' should be the same in both files?

**Comment by chrisdennis** [comment]
Yes, you're right.  I'll line a fix up for Ehcache 3.0.2.  In the meantime a judicious use of casting to a raw type should get things to work for you.

**Comment by fgil55** [comment]
Thanks!
