### ISSUE TITLE
EhcacheServerEntityService should get a concurrent ConcurrencyStrategy

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#1105]
Currently the EhcacheServerEntity still uses a "no concurrency" concurrency strategy - we should replace this with one that provides concurrency on some stable combination of cache name and cache key.

**Comment by cljohnso** [comment]
No provisions for Ehcache service-level configuration is presently expected in support of concurrency strategy.  If something is added, it may need to be considered for configuration compatibility checks.
