### ISSUE TITLE
Idea: Mark CacheManager Closeable

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#1109]
To use with try / resources and code that handles Closeable / AutoCloseable objects in a similar way.

**Comment by ljacomet** [comment]
Short answer: we cannot because it would add a checked exception to the already defined `CacheManager.close()` which would break public API and is thus a no-no.

**Comment by mathieucarbou** [comment]
Not if you do not declare the `IoException` and keep the exact current signature :-)

```
public interface CacheManager extends Closeable {
[...]
    void close() throws StateTransitionException;;
[...]
}
```

That's what we did in our [`IMonitoringConsumer`](https://goo.gl/zZJFTq) interface.

So... basically no change for users using `CacheManager`, and for those wanting to use a `Closeable`, well, then they'll have to catch an `IoException` that would never occur.
