### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#112]
We need to decide on an abstract logging framework (à la slf4j) and add it to the code base:

 - Add loggers to `core` classes like `Ehcache`, `EhcacheManager` and `ServiceLocator` and choosing some levels to log things in place where required, so they don't act like complete black boxes;
 - Add logging about specific cases, especially around failures, like in lifecycle methods (e.g. `EhcacheManager#close` or `ServiceLocator#startAllServices`;
 - More?

**Comment by alexsnaps** [comment]
This was somewhat discussed here : https://www.youtube.com/watch?v=Rf86ZxtYXaY&list=UU43PVCp2j0b2og2DtxNOU1A#t=2387

**Comment by ljacomet** [comment]
I believe part of the work was done in PR #264. But there still remains works, in `Ehcache` at least.
And to that, the question of how to get the cache name in there still exists. So I am moving this one back to in progress.

**Comment by alexsnaps** [comment]
Could we use MDC for that? see http://www.slf4j.org/apidocs/org/slf4j/MDC.html

**Comment by AbfrmBlr** [comment]
MDC works for Ehcache and Cache names will be added to the logger.
But MDC does not work with sl4j-simple(which we currently use), it will only work with log4j and logback.
Therefore, should we change gradle testRuntime dependency to use log4j (so that tests log it properly) and add an documentation for MDC logging so that users can use it accordingly.

**Comment by chrisdennis** [comment]
Makes sense to me.

**Comment by ljacomet** [comment]
@AbfrmBlr Looks like I let [a typo](https://github.com/ehcache/ehcache3/commit/b02eb0d5adb679beb06fd0c949e0db24ce0739e7#diff-92de9e0237d8b12df0194b049e12722fR132) slip through.
Can you fix it?

**Comment by ljacomet** [comment]
I did fix the typo
