### ISSUE TITLE
Does ClusteringService really need maintenance mode?

### ISSUE THREAD

**Issue by cljohnso** [ehcache/ehcache3#1137]
Discussions with @chrisdennis suggest that the use of `MaintainableService` for `ClusteringService` is overkill -- the only operation for which maintenance mode is used/required is `PersistableResourceService.destroyAll()`.  The contention is that the shift to the required state for this operation could be performed internally without exposing that to the caller of `destroyAll`.

Discussion ...

**Comment by ljacomet** [comment]
I believe keeping this concept is required and useful. Maybe we could do without right now, but addition of future operations that would require maintenance mode would be in jeopardy.
Also it is not like this is bringing unneeded complexity.

Unless someone has a different opinion, I will close it within 3 days.

@chrisdennis @cljohnso and others comments?

**Comment by ljacomet** [comment]
Took a bit more than three days, closing though
