### ISSUE TITLE
Unable to use only OffHeap store with JSR107 Cache

### ISSUE THREAD

**Issue by gmagniez** [ehcache/ehcache3#1146]
Configuring a JSR107 cache with only offHeap store  fails du to "`java.lang.RuntimeException: store result must not be null` . OnHeapStore has a `OnHeapStoreStatsSettings` which declares the tag 'store'.
But OffHeapCache does not have one.
Starting the cache with only 0 elements configured as Heap works but I see that statistics are false as it seems to count 1 miss for the heap cache and 1 hit for the offheap one.
Moreover, using on heap cache, even if empty, lookup into the heap cache and it also use synchronisation in internal ConcurrentHashMap implementation, so performances are degraded.

**Comment by gmagniez** [comment]
I've tried to not use the JSR107 api, but I did not find a way to get JMX statistics though the native ehcache API.

**Comment by ljacomet** [comment]
Hello,

Thanks for your report - there is indeed a bug hiding there.
