### ISSUE TITLE
Need access to configured Expiry

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#1153]
Requirement for #1148.

```
CacheConfiguration<?, ?> cacheConfig;
Expiry<?, ?> expiry = cacheConfig.getExpiry();
```

We would need to get the expiry type plus the values configured.

1. `Expirations` declares all expiry implementations as private
2. We cannot get the duration values configured

**Comment by mathieucarbou** [comment]
(CC @GaryWKeim for usability)

**Comment by ljacomet** [comment]
Can you describe what you want to do with that? And what is the plan for custom user expiry?

**Comment by mathieucarbou** [comment]
It's for #1148. We need to expose the cache manager and caches configuration through management. So currently, there's a lot of configuration not directly available or easily available from the ehcache runtime configuration.

Expiry is one but there's a lot more (i.e. clustering)

You can see some code that I currently did in my branch:

https://github.com/mathieucarbou/ehcache3/blob/97b7a5264671a80431eea675c8e246b181745ac9/management/src/main/java/org/ehcache/management/providers/settings/ExposedSettings.java

Since Ehcache does not provide in model or xml or another easy way all the configuration set by the user (programmatically or by the XML), then we need to do a lot of ugly reflection at the moment.

We already discussed that with @anthonydahanne and @lorban : we did not find a better way to do this, and at least warn / open an issue when we encounter some usability issue such as the Expiry thing.

**Comment by mathieucarbou** [comment]
UPDATE: in case of custom expiry, then we will only show the Expiry class name (type). But is we know that we can get more information (configured) from known expiry (i.e. ttl, time to idle, etc) then we would like to be able to read the static values set :-)

**Comment by mathieucarbou** [comment]
UPDATE 2:

I guess we probably don't need to access the core values. But we at least need to output the Expiry type, plus some other information describing it. It could be done like it's done in `BaseClusteredResourceType.toString()` : by adding toStrings into `TimeToLiveExpiry`, `TimeToIdleExpiry` and `NoExpiry`. Because just having the toString() on `BaseExpiry` with all 3 durations is too technical.

**Comment by mathieucarbou** [comment]
spoke to @ljacomet : we won't need it: it will be handled by #951
