### ISSUE TITLE
Improve concurrency strategy for clustered Ehcache

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#1178]
From @AbfrmBlr on #1155:

> I think we should try to differentiate between reads and mutations in concurrency startegy so that reads are not blocked on mutations which typically require passive replication, making them slow.
> If we do that I think we can get some advantage in read perf when we have passives and considerable mutations being done on cache.
> I think we can do some perf tests to assert if moving reads to a different queue would really help.

**Comment by AbfrmBlr** [comment]
We now use Universal key for `GET` messages, which would imply that the messages would be bound on the least loaded queue.
