### ISSUE TITLE
Does ehcache3.x need lock when put element in multithread env?

### ISSUE THREAD

**Issue by formath** [ehcache/ehcache3#1188]
I can't find acquireWriteLockOnKey in ehcache3.x api. So, ehcache3.x do not need lock explicitly when put element in multithread env?

**Comment by ljacomet** [comment]
Hi,

There is no need for explicit locking and there was none in Ehcache 2.x
even. Both are thread safe libraries with regards to cache operations.
The explicit locking API from Ehcache 2.x was promoting the wrong kind of
patterns and thus we have decided to not reproduce it in Ehcache 3.x.

Regards,
Louis

**Comment by ljacomet** [comment]
Thanks for your interest in Ehcache 3.x. We recommend questions such as these go to the google group - [ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) - instead of opening issues on GitHub.
