### ISSUE TITLE
Assess current destroy support

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#1193]
* Destroy a cache having a clustered tier
  * No other clients can be connected
  * Still closes the local cache
  * Throws to indicate did not destroy
* Destroy a cache manager having a clustered entity
  * Requires no clients have fetched the entity or hold the maintenance lease
  * Still destroys all local state!
  * Throws on failure, CM back to un-initialized state

Need to know what remains to be done and how we handle corner cases

**Comment by fossf** [comment]
BF-4579
