### ISSUE TITLE
Default config of the kit's server doesn't contain any resource pool

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#1205]
That makes the server virtually useless - and even confusing - as you can create entities but can't get a single working cache.

**Comment by chrisdennis** [comment]
I would much prefer making the CacheManager initialization throw when there are no available offheap resources over creating a default resource.  Then we can make the error message take the user by the hand... and thereby avoid all the awkward decisions around the size and name of the default pool.

**Comment by albinsuresh** [comment]
After having a discussion with @ljacomet and @lorban the right thing to do here is to fail the cache manger initialization throw when there are no offheap resources available on the platform side. But we are limited by the capabilities of platform's service registry to lookup for a service with a generic configuration to at least know if a service exists. Platform's _ServiceRegistry.getService_ requires a `ServiceConfiguration`. And in the case of `OffHeapResource` it expects an `OffHeapResourceIdentifier` (the `ServiceConfiguration<OffHeapResource>`) with a non-null identifier. We would need an extension of the `ServiceRegistry` that would permit a generic lookup for a service by its type.
