### ISSUE TITLE
Make Passive Sync Behavior Decision

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#1210]
For Ehache active-passive we have a choice as to whether we sync any/all of a cache's key-value pairs during the passive sync stage.  This is essentially a tradeoff between time to HA and quality of HA when starting a new passive.  We need to decide if there is a good enough default here to avoid having to add configuration to control this behavior or whether we have to ad configuration to control it (and where any potential configuration would belong).

**Comment by albinsuresh** [comment]
Was discussing this with @AbfrmBlr and we were thinking of making this configurable on a per-entity basis. That will free us from making a choice on the "best" default configuration. The user would know better about the peak-load support of the cache's back-end system and can make a choice.

**Comment by ljacomet** [comment]
The goal of this task is to decide on the first implemented scheme. While we may want to support both at one point and offer configuration, we initially need to make a choice.

**Comment by albinsuresh** [comment]
Then wouldn't it be best to go with the "sync all" approach which is probably what users also would prefer since that is the behavior that they're used to from the 2.x line. And once we have it, adding configurability would be much easier as it'd just be enabling/disabling what we have already.

**Comment by ljacomet** [comment]
From multiple discussions, we will start with having all active content synced to the passive before it is considered a live passive.
This is based on the Ehcache 2.x / Terracotta 4.x model and also will make sure that the announced HA will not surprise users who do not read the fine prints.
While we may want to offer different options in the future, I am closing this as resolved.
