### ISSUE TITLE
Samples for ehcache 3.1 release

### ISSUE THREAD

**Issue by jhouserizer** [ehcache/ehcache3#1238]
Create a new repository for ehcache samples.
- Proposal:   `ehcache\ehcache3-samples`

The README.md file at the root of that repository would have a short description of each sample.

Each sample will have it's own sub-tree with its own README.md describing the sample in full, as well as how to use / run it.

We should have a sample(s) that:

- Show basic cache usage (with both put and get ops)
-- Show it run unclustered
-- Show the same thing run clustered (with the small config file change)

- Demonstrate distributed caching
-- run a server
-- one client writes data
-- one client reads data 

- At least one sample (possibly the above) should setup logging, etc. to show full usage.

- Make sure samples are consistent with the docs for using clustered caches

**Comment by jhouserizer** [comment]
Gary, can you give this some effort?

**Comment by jhouserizer** [comment]
Should samples projects be maven or gradle based, or do we care?

**Comment by GaryWKeim** [comment]
I'd like to create them with Maven. I feel hoisting Gradle on end-users is an impediment to 30MTV. But, suggestions on alternative execution environments are welcome.
