### ISSUE TITLE
Review and adapt terminology

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#1243]

**Comment by jhouserizer** [comment]
@lorban  I'm working on grammar/wording improvements to the `custered-cache.adoc` file, and will be trying to also fix some of the terminology in there. I will make my changes based upon what we all saw in the "terminology" mail thread.  Hopefully it lines up with what you're doing and isn't redundant.

**Comment by lorban** [comment]
I've only touched the messages reported by the logs and exceptions. Hopefully we now have a common terminology across doc and code.
