### ISSUE TITLE
Restore client-side stack trace to server-side exceptions

### ISSUE THREAD

**Issue by cljohnso** [ehcache/ehcache3#1256]
Updates for issue #763 changed the way server-side exceptions returned to the client in response to clustered cache operations -- the server-side exception is wrapped in client-side exception to provide client-side stack trace information in addition to the server-side stack trace information.

Updates for issue #1221 reverted this behavior.

This issue is directed at re-enabling the wrapping of a server-side exception in a client-side exception to recover the client-side stack trace.

**Comment by cljohnso** [comment]
Blocked pending resolution with issue #1279 / PR #1283.

**Comment by ljacomet** [comment]
Opened a discussion on the topic on [ehcache-dev](https://groups.google.com/forum/#!topic/ehcache-dev/u3mXvnJQKSg)

**Comment by ljacomet** [comment]
From discussions with @AbfrmBlr, @albinsuresh, @cljohnso and @lorban, this goes in first and we will see what remains to be done for #1279 after.
