### ISSUE TITLE
kit zip archive has duplicate README file

### ISSUE THREAD

**Issue by aurbroszniowski** [ehcache/ehcache3#1273]
I downloaded the kit from
https://github.com/ehcache/ehcache3/releases/download/v3.1.0/ehcache-clustered-3.1.0-kit.zip

and extracted it in windows **(there was no previous installation, the directory was empty)**
I got a duplicate file error as seen in the screenshot

![readme-dplicate](https://cloud.githubusercontent.com/assets/1264251/16502856/b3adc8e4-3f10-11e6-8234-4329284ebc83.png)

**Comment by ljacomet** [comment]
@GaryWKeim Assigning to you since you have a PR open for this.

**Comment by GaryWKeim** [comment]
It will be easier if you handle this.

**Comment by anthonydahanne** [comment]
I could give it  try
