### ISSUE TITLE
Limit EhcacheEntityResponse.Failure to return ClusteredEhcacheException

### ISSUE THREAD

**Issue by cljohnso** [ehcache/ehcache3#1279]
The `EhcacheEntityResponse.Failure` message is used to return a server-thrown exception.  The message is presently set up to accept any `Exception` which then needs to be re-interpreted on the client to add the client context (most importantly, stack trace).  Updates for issue #1256 adds a method specifically for the adding the client-side stack trace to `ClusteredEhcacheException` instances.  From an error handling hygiene point of view, it would be best to have _only_ `ClusteredEhcacheException` subclasses returned forcing server code to return exceptions that can be more directly re-thrown in the client (or provide more contextual detail for other client-side handling).

**Comment by chrisdennis** [comment]
I had actually envisioned something a little more than this... I had hoped we could have the server return only say: `ClusteredEhcacheServerException` that would have a method that added the client stacktrace and returned a `ClusteredEhcacheClientException`.  Then by ensuring that nothing client-side can throw the server exception type we have better assurances that all server exceptions will get client stack traces attached to them.

**Comment by cljohnso** [comment]
Yeah, what he said ...

**Comment by albinsuresh** [comment]
If we are going to do that split, which I personally feel is cleaner, do we still want to keep the word `Ehcache` in those? Isn't that a bit redundant? Wouldn't `ClusteredServerException` and `ClusteredClientException` suffice? Cos the user is using Ehcache and hence would know the context.

**Comment by chrisdennis** [comment]
Well... if you're going to go that far you could almost make this a feature of Voltron itself.

**Comment by albinsuresh** [comment]
Oh I agree to that. I honestly feel that there should be some clear exception handling contract between the platform and the entities. The platform must be able to handle at least something and it should be part of the contract. The server(platform) crashing when an entity throws an exception sounds insane to me. But I don't know the history of why the platform was designed like that. They must have had some reason. Perhaps another conversation to be had with the platform team.

**Comment by cljohnso** [comment]
Blocked pending resolution with issue #1256 / PR #1272.

**Comment by ljacomet** [comment]
Opened a discussion on the topic on [ehcache-dev](https://groups.google.com/forum/#!topic/ehcache-dev/u3mXvnJQKSg)

**Comment by ljacomet** [comment]
#1256 has been merged - let's see what is still worth doing here following the conversation with @AbfrmBlr, @albinsuresh, @cljohnso and @lorban
