### ISSUE TITLE
Custom serializers constructor contract changed for 3.1, docs are not updated

### ISSUE THREAD

**Issue by cschanck** [ehcache/ehcache3#1280]
In 3.1, custom Serializers have change from needed a constructor of:

`public MySerializer(ClassLoader classLoader, FileBasedPersistenceContext persistenceContext) ..`

to:

`public MySerializer(ClassLoader classLoader, StateRepository stateRepository) ...`

The current docs (http://www.ehcache.org/documentation/3.1/serializers-copiers.html) do not reflect this.

**Comment by alexsnaps** [comment]
Adding some implementation sourced from the actual code base into
asciidoctor would address that.
On Fri, Jul 1, 2016 at 1:16 PM Chris Schanck <notifications@github.com>
wrote:

> In 3.1, custom Serializers have change from needed a constructor of:
>
> public MySerializer(ClassLoader classLoader, FileBasedPersistenceContext
> persistenceContext) ..
>
> to:
>
> public MySerializer(ClassLoader classLoader, StateRepository
> stateRepository) ...
>
> The current docs (
> http://www.ehcache.org/documentation/3.1/serializers-copiers.html) do not
> reflect this.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ehcache/ehcache3/issues/1280>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAfEgndkeuWR_fR_A-aNVHmO4Ij2Bo6kks5qRUpRgaJpZM4JDUyH>
> .
>
-- 
Alex Snaps
Twitter: @alexsnaps

**Comment by ljacomet** [comment]
For compatibility reasons, the previous constructor contract remains valid. But indeed the documentation is missing an update on this.
