### ISSUE TITLE
Statistics work

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#1286]
Define a set of standard statistics and implement them.

**Comment by ljacomet** [comment]
I certainly hope so. I believe starting with the set of stats exposed by JCache / JSR-107 is an idea. Then we can discuss the Java based API to expose them. And maybe later discuss about exposing more.

**Comment by lorban** [comment]
In my mind, this task was more about first deciding what stats we want to expose. At the moment, there are dozens of counters all around but that's pretty much it. We don't calculate rates, ratios, latencies... and the store counters that should be used to calculate useful stats change depending on the cache topologies.

I think we should first work on the statistics themselves before defining an API to expose them.

**Comment by lorban** [comment]
Here is for instance a set of stats that would be very handy to have when performing perf testing:

```
tier hit/miss ratio
 tier hit count
 tier hit latency
 tier miss/fault count
 tier miss/fault latency
 tier eviction count
 tier eviction latency
 tier resource usage in %

cache hit/miss ratio
 cache hit count
 cache hit latency
 cache miss count
 cache miss latency
 cache eviction count
 cache eviction latency
 cache resource usage in %
 
special cases:
 clustered tier's resource usage is not available on the client
 clustered tier should also report invalidation count and latencies
```

**Comment by aurbroszniowski** [comment]
What would be useful is

- cache tiers hit distribution (e.g. if we have a heap+offheap+clustered cache, reporting where the hit came from, e.g. 10% from heap, 30% from offheap, 50% from clustered)
- for cache read (hit) and cache write, the latencies running medians, min, max and probably moving averages
- nb of elements in each tier (even approximative)

those 3 types of numbers would help to decide of the caches sizing, by giving clear feedback on how performance is updated when changing sizes of the cache tiers.

for the statistics you listed by @lorban, it would help to decide which one are really useful if you could explain for each one of them, how they can be used and for which purpose.

**Comment by lorban** [comment]
Tier hit/miss ratio will tell you how useful a tier is.
Tier hit count and latencies will tell you how fast a tier serves its hits.
Tier miss/fault latencies will tell you how much overhead a tier adds to the lower tiers' hit (in case of higher tiers) or how fast it misses.
Tier eviction count and latencies will tell you how often the tier needs to make room to fault in lower tier's mappings and how fast it does that.
Tier resource usage will tell you how much of its allocated resources a tier consumes. I start to believe reporting count as well as bytes would be useful.

Cache stats are the same but on the global cache level. Together with the tier's stats you can get a better idea of the impact the tiers have on the overall cache's performance.
Cache resource usage actually is the lowest tier's usage. Knowing how full a cache is and how many mappings it contains is very useful, especially when resources are in bytes.

Invalidations of the clustered store are very useful too to figure out how often the other clients force the local tiers to wipe some data away.

**Comment by lorban** [comment]
@aurbroszniowski some of the stats you ask for would require maintaining a histogram. We currently don't support that but I do know some work has been done in there by @chrisdennis but got shelved. If time permits, I'm sure we'll want to add those too.

**Comment by aurbroszniowski** [comment]
running medians (I guess that's what you are referring to) doesn't necessary need to keep a full histogram, but on second thought I think anyway that the responsibility of calculating it (and average, min and max) should be the user's (or the monitoring app if those stats ends up being displayed there)

**Comment by lorban** [comment]
A working prototype is available in those branches:
https://github.com/lorban/statistics/tree/better-stats-registry
https://github.com/lorban/ehcache3/tree/issue-1293

**Comment by gibsong** [comment]
I am having a lot of test failure problems. 

I traced through the ManagementTest.capabilitiesAndContexts() test and found that OnHeapStore.createStore(...) tries to create an instance of 
TierOperationStatistic without a StoreOperationOutcomes.GetOutcome.TIMEOUT value.  There is a set comparison check at the end of the TierOperationStatistic(...) constructor that checks whether input Set xlatMap contains all the values defined in the enum set.  Lines 82-91.  This issue seems to stem from a change Abilash made, where he added StoreOperationOutcomes.GetOutcome.TIMEOUT.  If this change is correct, then can I assume that I need to add an enum TIMEOUT value to TierOperationStatistic.TierOperationOutcomes.GetOutcome?

e.g.
public static class TierOperationOutcomes {

    public enum GetOutcome {
      HIT,
      MISS,
      TIMEOUT
    }

    public enum EvictionOutcome {
      SUCCESS,
      FAILURE
    }

  }

In addition, would a TIMEOUT enum value also need to be added to each of the *OperationsOutcome enum implementations?
