### ISSUE TITLE
OffHeapChainMap thieving argument is ignored

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#1292]
`OffHeapChainMap` is backed by `EvictionListeningReadWriteLockedOffHeapClockCache` but the latter lacks a constructor that accepts `shareByThieving` argument.

The offheap store lib should be modified to add such constructor so that `OffHeapChainMap` can make use of it.

**Comment by chrisdennis** [comment]
Given how busted ARC is at the moment this turns out to be a non-issue. That said @AbfrmBlr is going to fixing the broken ARC implementation in clustered (that he wrote) and extending it to cover unclustered offheap and disk. He's going to run headlong in to this as a result.

**Comment by chrisdennis** [comment]
This will be fixed under #2215
