### ISSUE TITLE
A name for pool-1-thread-1's thread  is still running

### ISSUE THREAD

**Issue by yourwafer** [ehcache/ehcache3#1315]
class ‘PartitionedScheduledExecutor’ got a bug
just work thread exit but not scheduler

`@Override
  public boolean awaitTermination(long time, TimeUnit unit) throws InterruptedException {
    if (isShutdown()) {
      if (termination.isDone()) {
        return worker.awaitTermination(time, unit);
      } else {
        long end = System.nanoTime() + unit.toNanos(time);
        try {
          termination.get(time, unit);
        } catch (ExecutionException e) {
          throw new RuntimeException(e.getCause());
        } catch (TimeoutException e) {
          return false;
        }
        return worker.awaitTermination(end - System.nanoTime(), NANOSECONDS);
      }
    } else {
      return false;
    }
  }`

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We usually recommend starting a conversation on the [users google group](https://groups.google.com/forum/#!forum/ehcache-users) before opening an issue.

Could you elaborate on what makes you think there is a bug?
