### ISSUE TITLE
Handling exceptions from Expiry methods

### ISSUE THREAD

**Issue by timeck** [ehcache/ehcache3#133]
At the moment unchecked exceptions from the methods `org.ehcache.expiry.Expiry.getExpiryForAccess(K, V)` and `org.ehcache.expiry.Expiry.getExpiryForUpdate(K, V)` are thrown back to the caller and the cache operation in which the `Expiry` call was part of will not mutate the cache. 

There are at least two other options proposed:
(1) Catch exceptions and use a default (either Duration.ZERO or Duration.FOREVER). This is similar to 107 behavior for exceptions in `ExpiryPolicy`
(2) Give the exception to a `ResilienceStrategy` to deal with as it sees fit. It's not clear what to do with the cache operation or what Duration it should apply if it is allowed to succeed

**Comment by rishabhmonga** [comment]
Reiterating the proposals above :
(1) We either conform to JSR107 and handle the exception we receive and in turn revert with a `Duration.ZERO` or `Duration.FOREVER`. This allows the cache operation to succeed.
(2) We fail the operation, destroying the mapping and throw the exception using `CachePassThroughException`.

**Comment by ljacomet** [comment]
Discussion with @chrisdennis and @rishabhmonga: we go for option 2 and if doing so in the JSR-107 bridge still passes the TCK, then we apply the same logic there.

**Comment by rishabhmonga** [comment]
As per the discussion, we will implement the option 2 by logging the exception received at error log level and returning a `Duration.ZERO`, essentially leading to a removal of the mapping.
