### ISSUE TITLE
Coalesce interval implementations

### ISSUE THREAD

**Issue by cljohnso** [ehcache/ehcache3#1330]
After issue #1158 and PR #1227, we have two representations of intervals in Ehcache sharing a common XML base.  The implementations
- `org.ehcache.clustered.client.config.TimeoutDuration`  (`/ehcache:config/ehcache:service/tc:cluster/tc:read-timeout`)
- `org.ehcache.expiry.Duration` (`/ehcache:config/ehcache:cache/ehcache:expiry/ehcache:tti` and `/ehcache:config/ehcache:cache/ehcache:expiry/ehcache:tti`)

share the underlying schema type `time-type`.

XML parsing support for `TimeoutDuration` takes advantage a JAXB parser based on the XML module definition of `time-type`.

This issue suggests:
1. Coalescing the common _interval_ specifications of `TimeoutDuration` and `Duration` into a new API module object -- possibly `TimeSpan`-- and deriving `TimeoutDuration` and `Duration` from that common object.
2. Provide a JAXB parsing routine (see `org.ehcache.clustered.client.internal.config.xml.ClusteringServiceConfigurationParser#processGetTimeout`) that can be used by modules using configurations based on extension XSDs.

Review comments on PR #1227 should be reviewed for context and additional details.

**Comment by chrisdennis** [comment]
Issue #2196 removed TimeoutDuration, and Duration is now deprecated in favor of `java.time.Duration`.
