### ISSUE TITLE
StringSerializer performance regression

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#1340]
The #958 changes have cost about 14% perf.

**Comment by chrisdennis** [comment]
Did some quick testing using JMH and I'm not seeing the same dip comparing the original version of the StringSerializer that used UTF-8 and the current version.  My test can be seen here https://github.com/chrisdennis/ehcache3/tree/jmh - running on my machine yields:

| Benchmark | Mode | Cnt | Score | Error | Units |
|-------------|-------|----|-------|------|-------|
| StringSerializerTest.asciiDeserialize | sample | 182067 | 89.063 | ± 2.395 | ns/op |
| StringSerializerTest.asciiEqualsMatch | sample | 116452 | 64.195 | ± 1.017 | ns/op |
| StringSerializerTest.asciiSerialize | sample | 171411 | 83.780 | ± 0.931 | ns/op |
| Utf8SerializerTest.asciiDeserialize | sample | 182430 | 92.038 | ± 0.997 | ns/op |
| Utf8SerializerTest.asciiEqualsMatch | sample | 183848 | 95.195 | ± 1.168 | ns/op |
| Utf8SerializerTest.asciiSerialize | sample | 154149 | 106.401 | ± 1.138 | ns/op |

![issue-1340-graph](https://cloud.githubusercontent.com/assets/954331/17637218/209edc5c-60b0-11e6-90d2-6b6b21c936e8.png)

**Comment by chrisdennis** [comment]
@lorban did you ever get a chance to verify/refute this?
