### ISSUE TITLE
Codecs account for ~27% time spent

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#1341]
This only accounts for the time spent in the codecs to send on the wire / receive from it: codecs usage by the chain resolver is on top of that.

ChainCodec seems to consume most of that time.

Overall, the codecs generate about 830 MB of garbage per second.

**Comment by lorban** [comment]
While working on improving performance of the codecs, long-term maintenance of codecs and messages was considered too, especially w.r.t. forward/backward compatibility over future changes.

Protobuf was tried but its insistence on using immutable builders to create messages is a performance killer, especially since our largest messages are `byte[]`-based which require multiple in-memory copies.

The three other libs I looked at that do take performance into consideration are Cap'n Proto, SBE and FlatBuffers.

Cap'n Proto's java implementation requires JDK 1.8, is incomplete and has been left untouched for almost a year.

SBE has a cumbersome API, requires JDK 1.8, gratuitously (IMHO) uses s.m.Unsafe and has a few annoying bug/limitations like its inability to work on read-only `ByteBuffer`s.

FlatBuffers is considered experimental and is only delivered as a code drop, binaries aren't even published to maven central.

After all, I could not find the Silver Bullet we are looking for, so it looks like we would need to come up with our own tool (that could be a fork of one of the above three) but I'm not certain it's worth the effort.

**Comment by albinsuresh** [comment]
Are there any other benefits; if not performance; if we get rid of the hierarchies in our messages? I remember someone saying that it'd make forward/backward compatibility maintenance easier although I don't know how. So would it help in any way if we do at least that flattening of messages as part of this task?

**Comment by lorban** [comment]
If you omit performance, protobuf is really nice : instead of creating codec and message classes we could write a simple message descriptor and all the serialization/deserialization code would be generated for us, with a lot of options to modify them without breaking backward compatibility.

Using a protobuf-like lib would make our messaging layer a lot cleaner, leaner, easier to maintain and future-proof.

**Comment by chrisdennis** [comment]
Is this the task we are going to use for adopting runnel in Ehcache?  If not I guess we should file a task for that, and close this one, right?

**Comment by ljacomet** [comment]
Opened #1482 for runnel adoption - closing this
