### ISSUE TITLE
Suboptimal ChainResolver

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#1343]
`ChainResolver.resolve()` spends a lot of time decoding and encoding operations.

There certainly are optimizations that could be done here. For instance, the key and value of the payload always are decoded even if the key doesn't match -which in that case makes the decoded value useless-.

**Comment by albinsuresh** [comment]
As for the first iteration going to do delayed value deserialization in operations. There is no need to delay key deserialization as the resolution involves key comparisons anyway.

**Comment by albinsuresh** [comment]
Some more minor optimizations that can be done are:

1. Avoid encoding/decoding of time stamps in Operations and sending it across the network if a valid expiry is not available (either not configured or configured as `Expirations.none()`)
2. Avoid creating a new PUT operation on every resolution. Try to send the final resolved operation as is, if the time stamp has not changed (Could save one key serialization and one value serialization per resolution as the serialized forms of both key and value are available from the initial chain itself; provided keys also use `LazyValueHolder`).

These will be done as part of PR #1381 or as a followup PR.

**Comment by albinsuresh** [comment]
Some more minor optimizations that can be done are:

1. Avoid encoding/decoding of time stamps in Operations and sending it across the network if a valid expiry is not available (either not configured or configured as `Expirations.none()`)
2. Avoid creating a new PUT operation on every resolution. Try to send the final resolved operation as is, if the time stamp has not changed (Could save one key serialization and one value serialization per resolution as the serialized forms of both key and value are available from the initial chain itself; provided keys also use `LazyValueHolder`).

These will be done as part of PR #1381 itself or as a followup PR.

**Comment by ljacomet** [comment]
After discusson with @chrisdennis and @albinsuresh let's go with the PR as it stands and not do any more work under this item. If later perf test ends up raising this code area as a problematic one, we could revisit.
