### ISSUE TITLE
OSGi support for clustering module

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#1348]
Investigation points:
- Module properly loads in an OSGi container
  - Currently broken, because of dependencies on a number of `*.internal.*` packages from ehcache core.
- ServiceLoader from core is able to load clustered implementations of services.

**Comment by ljacomet** [comment]
Interesting OSGi resource around use of `ServiceLoader`: http://blog.osgi.org/2013/02/javautilserviceloader-in-osgi.html

**Comment by chrisdennis** [comment]
This should all work now... the component modules of the clustered implementation cannot be loaded as independent OSGi modules, but the resulting shaded JAR can.
