### ISSUE TITLE
Idea: Automatically shutdown provided executors

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#1378]
When requesting an ExecutorService like this:

```
    this.managementCallExecutor = serviceProvider.getService(ExecutionService.class).getOrderedExecutor(
        configuration.getManagementCallExecutorAlias(),
        new ArrayBlockingQueue<Runnable>(configuration.getManagementCallQueueSize()));
```

I'd like to avoid having to put each time the following code in the `stop()` method

```
shutdownNow(managementCallExecutor);
```

Several goals here:
1. to my mind, it's hard to tell the users that they should call `shutdownNow(managementCallExecutor);` by themselves
2. error-prone: myself I forgot to call it 2 times already... (i.e. PR #1377)

Proposal:

The `ExecutionService` could keep weak references on provided executor services and in its `stop()` method, shutdown all provided executors. 

This would prevent a user or dev to "forgot" closing one and thus blocking a cache manager close for example.

**Comment by chrisdennis** [comment]
Closing this since it's not (to my knowledge) come up again since we did this.  We're just not writing enough new code against this interface to justify adding this. The existing code is now right... new code can be made right too.
