### ISSUE TITLE
Default Serializer implementation of read() method does not protect buffer position

### ISSUE THREAD

**Issue by rkavanap** [ehcache/ehcache3#1386]
Since the default supplied ehcache serializer implementation (such as StringSerializer, PlainJavaSerializer etc) disturbs the buffer positions post call, it may be unusable in some situations without developing wrapper serializers. It may be better if these serializers do a buffer.duplicate() (buffer.slice()) so that the positions are not disturbed after a read.

**Comment by chrisdennis** [comment]
I'm inclined to consider this a bug (if it even exists) in the calling code. Serializer implementations should be allowed to advance positions, callers should make sure to pass them slices/copies etc.
