### ISSUE TITLE
How to access cache created by other clients?

### ISSUE THREAD

**Issue by esebasti** [ehcache/ehcache3#1413]
Accessing clustered cache created by other clients using CacheManager.createCache() outside of cache manager initialization seems not possible as getCache() never hits server. Is there any other way? Here is the test case demonstrating the problem.
 
    PersistentCacheManager cacheManager = null;
    int clientId = barrier.await();

    if (clientId == 0) {
      //Create new cache manager from client 0
      CacheManagerBuilder<PersistentCacheManager> builder = newCacheManagerBuilder()
          .with(ClusteringServiceConfigurationBuilder.cluster(getClusterUri(testName))
              .autoCreate()
              .defaultServerResource("primary-server-resource")
              .resourcePool("resource-pool-a", 128, MemoryUnit.KB)
              .resourcePool("resource-pool-b", 128, MemoryUnit.KB, "secondary-server-resource"));
      cacheManager = builder.build(false);
      cacheManager.init();
    }
    barrier.await();
    if (clientId == 1) {
      //Connect to existing cache manager created by client 0
      CacheManagerBuilder<PersistentCacheManager> builder = newCacheManagerBuilder()
          .with(ClusteringServiceConfigurationBuilder.cluster(getClusterUri(testName))
              .expecting()
              .defaultServerResource("primary-server-resource")
              .resourcePool("resource-pool-a",   128, MemoryUnit.KB)
              .resourcePool("resource-pool-b", 128, MemoryUnit.KB, "secondary-server-resource"));
      cacheManager = builder.build(false);
      cacheManager.init();
    }
    barrier.await();
    if (clientId == 0) {
      //Create cache from client 0
      cacheManager.createCache("cache1", CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, String.class,
          ResourcePoolsBuilder.newResourcePoolsBuilder()
              .with(ClusteredResourcePoolBuilder.clusteredDedicated("primary-server-resource", 2, MemoryUnit.MB))));
      Cache<Long, String> cache1 = cacheManager.getCache("cache1", Long.class, String.class);
      Assert.assertNotNull(cache1);
      cache1.put(1L, "one");
    }
    barrier.await();
    if (clientId == 1) {
      //Access the cache from client 1
      Cache<Long, String> cache1 = cacheManager.getCache("cache1", Long.class, String.class);
      //It fails here
      Assert.assertNotNull(cache1);
      Assert.assertEquals(cache1.get(1L), "one");
    }
    barrier.await();
    cacheManager.close();
    barrier.await();
    if (clientId == 0) {
      cacheManager.destroy();
    }
    barrier.await();

**Comment by ljacomet** [comment]
The code does not work by design.
What client 1 needs to do is to create the cache as well inside its `CacheManager` because a `Cache` is a client concept.
Regarding the clustered tier on the server, it will be created once by client 0 that has _auto create_ on.
