### ISSUE TITLE
EhcacheActiveEntity.clientStateMap looks fishy for concurrent accesses

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#1418]
`EhcacheActiveEntity.clientStateMap` is a plain `Map` and thus may suffer from concurrency artefacts when used in the EhcacheActiveEntity.
Some of this may be answered by terracotta-oss/terracotta-apis#144.

Also, we seem to lookup the `ClientDescriptor` multiple times _per message_ which sounds pretty inefficient.

**Comment by AbfrmBlr** [comment]
As discussed with @albinsuresh , this is being worked under #1525
