### ISSUE TITLE
Tests not running on Windows

### ISSUE THREAD

**Issue by anthonydahanne** [ehcache/ehcache3#1436]
It was reported by several users using the Windows platform that some tests are running.
Let's keep track of all issues (and resolutions) from this ticket

**Comment by henri-tremblay** [comment]
Do we have examples?  Because on my side, I tend to have this one:

> Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

Which is more Gradle related than Ehcache

**Comment by anthonydahanne** [comment]
oh yes we have examples, I'm currently working on a PR for AbstractClusteringManagementTest and EhcacheManagerToStringTest
But I think @gibsong  also listed others.

That said, I did not have your issue on windows...

**Comment by henri-tremblay** [comment]
Can you try with java 1.8.0_102?

**Comment by fossf** [comment]
They are running now on Azure
