### ISSUE TITLE
Our maven artifacts are Divergent!

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#1438]
![Divergent!](https://i.kinja-img.com/gawker-media/image/upload/s--A7P8WhsL--/c_scale,fl_progressive,q_80,w_800/rull9j7ubkw0tdvilh80.jpg)

We should add a Gradle version of Kate Winslet to crush the threat that divergent ~~teenagers~~ _transitive dependency sets_ pose to the stability of ~~our society~~ _downstream dependent projects_.

**Comment by cschanck** [comment]
You understand, that is not Kate Winslet, right? It's Shailene Woodley who will save our builds.
