### ISSUE TITLE
MappedByteBufferSource's ASYNC_FLUSH_EXECUTOR never shut down

### ISSUE THREAD

**Issue by Xyaren** [ehcache/ehcache3#1444]
org.terracotta.offheapstore.disk.paging.MappedPageSource.ASYNC_FLUSH_EXECUTOR
is an instance of org.terracotta.offheapstore.util.Retryer and owns an executor which is not shut down.

This is my ugly workaround:

```
            Field retryerField = MappedPageSource.class.getDeclaredField("ASYNC_FLUSH_EXECUTOR");
            retryerField.setAccessible(true);

            Retryer retryer = (Retryer) retryerField.get(null);

            Field executorField = Retryer.class.getDeclaredField("executor");
            ScheduledThreadPoolExecutor executor = (ScheduledThreadPoolExecutor) executorField.get(retryer);
            
            executor.shutdown();
```

**Comment by ljacomet** [comment]
Hi,

Thanks for your interest in Ehcache 3!

We recommend starting conversations on the [google group](https://groups.google.com/forum/#!forum/ehcache-users) instead of filing issues directly.

To the problem: @chrisdennis any comment on that?

**Comment by chrisdennis** [comment]
Looks like a bug to me... but it's a bug in Terracotta-OSS/offheap-store

**Comment by ljacomet** [comment]
Opened terracotta-oss/offheap-store#38 - closing here
