### ISSUE TITLE
ehcache-sizeof-agent*.jar Files not deleted when using in webapp.

### ISSUE THREAD

**Issue by Xyaren** [ehcache/ehcache3#1445]
We#re using ehcache3 in out tomcat environment.
the agent jar files are .deleteOnExit(). This will not be called when running on an application Server.

Please consider to delete the Files on close() of the CacheManager.

**Comment by ljacomet** [comment]
Hi,

Thanks for your interest in Ehcache 3!

We recommend starting conversations on the [google group](https://groups.google.com/forum/#!forum/ehcache-users) instead of filing issues directly.

To your problem: we cannot delete the agent file on `CacheManager.close` because there may be multiple cache managers in the VM.

Can you link to explanations as to why the `deleteOnExit` is not respected in an app server?

**Comment by Xyaren** [comment]
I am just experiencing this.
Even if the .deleteOnExit is called and the hook runs. The files are not deleted. I think they may be still accessed by the VM.

**Comment by chrisdennis** [comment]
Are you saying that the file isn't deleted because the VM doesn't exit (because it's longer running), or are you saying that the VM does exit but the file doesn't get deleted?

**Comment by Xyaren** [comment]
The vm does exit. The file will not be deleted. Running in an webapp on tomcat 8.x

**Comment by chrisdennis** [comment]
How are you terminating the JVM?  Depending on how hard you terminate the process, the JVM may not get to run shutdown hooks, which could be why the file does not get deleted.

**Comment by Xyaren** [comment]
The "shipped" tomcat shutdwon script / command. No termination by force.

2016-10-05 15:45 GMT+02:00 Chris Dennis <notifications@github.com>:

**Comment by chrisdennis** [comment]
Could you show me what the shutdown command outputs to the terminal when you run it.  My understanding is depending on the environment, command and configuration the process can eventually be "shutdown" in a great variety of ways, up to and including a `kill -9`

**Comment by Xyaren** [comment]
Call shutdown.bat/sh within the tomcat /bin directory.
It will send a shutdown signal to the tomcat.


2016-10-05 18:09 GMT+02:00 Chris Dennis <notifications@github.com>:

**Comment by chrisdennis** [comment]
Looking at the Tomcat shutdown procedures it does in order:
1. A clean Java initiated shutdown
2. A `kill -SIGTERM`
3. A `kill -SIGQUIT`
4. A `kill -SIGKILL`

Anything short of the last option should run the JVM shutdown hooks and delete the file. I would suggest if it's having to resort to the SIGKILL that something is broken in your environment/deployment.
