### ISSUE TITLE
transaction timeout

### ISSUE THREAD

**Issue by shengc** [ehcache/ehcache3#1446]
I am receiving this message in the log which has caused the process failure,

```
 org.ehcache.transactions.xa.XACacheException: Current XA transaction has timed out
```

I am wondering if there is a way to increase the timeout, or just completely disable it? I checked the btm's configuration wiki page, it has default time out of 60 seconds, so I think the timeout should somehow come from the implementation of the ehcache transaction. Unfortunately the documentation I can find on this topic for ehcache is very limited :-(

**Comment by chrisdennis** [comment]
As an XA resource Ehcache will default to a 30 second transaction timeout if the transaction manager hasn't explicitly set it.  If you want to control this you should do it through the transaction manager:
* `javax.transaction.TransactionManager#setTransactionTimeout(int seconds)`
* `javax.transaction.UserTransaction#setTransactionTimeout(int seconds)`
