### ISSUE TITLE
Proper implementation for ServerStoreImpl.put

### ISSUE THREAD

**Issue by AbfrmBlr** [ehcache/ehcache3#1448]

**Comment by AbfrmBlr** [comment]
The put operations on ServerStoreImpl only to be used by EhcachePassiveEntity, i.e. why it is not part of the ServerStore api as it is not supposed to be used by clients.
Also the implementation is kind of a provisional thing for now, so that work for AP can move forward. The implementation for put needs to be rewritten in much proper way

**Comment by AbfrmBlr** [comment]
:clustered:server:jmh
# JMH 1.12 (released 243 days ago, please consider updating!)
# VM version: JDK 1.8.0_92, VM 25.92-b14
# VM invoker: C:\Java\jdk1.8.0_92\jre\bin\java.exe
# VM options: -Dfile.encoding=windows-1252 -Duser.country=IN -Duser.language=e
# Warmup: 10 iterations, 1 s each
# Measurement: 10 iterations, 1 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: benchmark.ChainMapJMHTest.measurePutPerfNew

# Run progress: 0.00% complete, ETA 00:00:40
# Fork: 1 of 1
# Warmup Iteration   1: 217.563 us/op
# Warmup Iteration   2: 174.468 us/op
# Warmup Iteration   3: 174.302 us/op
# Warmup Iteration   4: 191.941 us/op
# Warmup Iteration   5: 182.233 us/op
# Warmup Iteration   6: 180.499 us/op
# Warmup Iteration   7: 495.155 us/op
# Warmup Iteration   8: 171.668 us/op
# Warmup Iteration   9: 176.183 us/op
# Warmup Iteration  10: 209.131 us/op
Iteration   1: 194.152 us/op
Iteration   2: 180.879 us/op
Iteration   3: 243.994 us/op
Iteration   4: 170.736 us/op
Iteration   5: 615.403 us/op
Iteration   6: 170.199 us/op
Iteration   7: 203.135 us/op
Iteration   8: 171.781 us/op
Iteration   9: 207.789 us/op
Iteration  10: 175.578 us/op


Result "measurePutPerfNew":
  233.364 ▒(99.9%) 205.925 us/op [Average]
  (min, avg, max) = (170.199, 233.364, 615.403), stdev = 136.207
  CI (99.9%): [27.439, 439.290] (assumes normal distribution)


# JMH 1.12 (released 243 days ago, please consider updating!)
# VM version: JDK 1.8.0_92, VM 25.92-b14
# VM invoker: C:\Java\jdk1.8.0_92\jre\bin\java.exe
# VM options: -Dfile.encoding=windows-1252 -Duser.country=IN -Duser.language=e
# Warmup: 10 iterations, 1 s each
# Measurement: 10 iterations, 1 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: benchmark.ChainMapJMHTest.measurePutPerfOld

# Run progress: 50.00% complete, ETA 00:00:23
# Fork: 1 of 1
# Warmup Iteration   1: 364.439 us/op
# Warmup Iteration   2: 264.317 us/op
# Warmup Iteration   3: 277.000 us/op
# Warmup Iteration   4: 260.935 us/op
# Warmup Iteration   5: 292.389 us/op
# Warmup Iteration   6: 299.834 us/op
# Warmup Iteration   7: 249.320 us/op
# Warmup Iteration   8: 284.442 us/op
# Warmup Iteration   9: 255.265 us/op
# Warmup Iteration  10: 1989.096 us/op
Iteration   1: 247.082 us/op
Iteration   2: 276.607 us/op
Iteration   3: 254.561 us/op
Iteration   4: 293.803 us/op
Iteration   5: 258.470 us/op
Iteration   6: 541.386 us/op
Iteration   7: 272.238 us/op
Iteration   8: 291.476 us/op
Iteration   9: 304.710 us/op
Iteration  10: 281.543 us/op


Result "measurePutPerfOld":
  302.188 ▒(99.9%) 130.056 us/op [Average]
  (min, avg, max) = (247.082, 302.188, 541.386), stdev = 86.024
  CI (99.9%): [172.132, 432.243] (assumes normal distribution)


# Run complete. Total time: 00:00:46

Benchmark                          Mode  Cnt    Score     Error  Units
ChainMapJMHTest.measurePutPerfNew  avgt   10  233.364 ▒ 205.925  us/op
ChainMapJMHTest.measurePutPerfOld  avgt   10  302.188 ▒ 130.056  us/op

**Comment by AbfrmBlr** [comment]
checkl this branch for multi-threaded test results and jmh tests. https://github.com/AbfrmBlr/ehcache3/tree/issue-1448

**Comment by AbfrmBlr** [comment]
Though the change reflects a little improvement, we are still talking about these numbers for 10000 puts. Given the perf results, we have decided to park it for now and take it up again when this really becomes a bottle neck

**Comment by ljacomet** [comment]
Closing since we do not plan on acting upon it - might re-open an issue later if needed.
