### ISSUE TITLE
Review Generics

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#145]
On all types referenced from `Cache<K, V>`:
 - `CacheLoader` & `CacheWriters`
 - `Eviction` & `Expiry`
 - `Store`
 - others... ?

I think we got some wrong... Sort of started at the `EvictionPrioritizer` (i.e. the `Comparator`), `EvictionVeto` (i.e. the `Predicate`) and the `Expiry` when working on #101, as I tried pushing the `CacheConfigurationBuilder` generics a bit further.

**Comment by alexsnaps** [comment]
This may well be obsolete now, or around `CacheLoader` & `CacheWriter` unification at least...

**Comment by sreekanth-r** [comment]
I took a look at the generics in the API class they all look fine to me.

I believe this issue can be closed now.
