### ISSUE TITLE
TimeoutException when setting up a large cluster

### ISSUE THREAD

**Issue by kcleereman** [ehcache/ehcache3#1451]
When setting up a connection to a large cluster, the client will throw a TimeoutException because it takes longer than expected for the server to allocate the cluster.

Client code to reproduce the exception (note the cluster size of "(64, MemoryUnit.GB)" - this size will throw the TimeoutException, but if we only allocate 8gb then we don't get the TimeoutException or the AssertionError):

```
  final URI clusterURI = URI.create("terracotta://localhost:9510/cachemanager");
  PersistentCacheManager cacheManager = null;

  final CacheManagerBuilder<PersistentCacheManager> clusteredCacheManagerBuilder =
      CacheManagerBuilder.newCacheManagerBuilder()
          .with(ClusteringServiceConfigurationBuilder.cluster(clusterURI)
              .autoCreate().defaultServerResource("primary-server-resource")
          )
          .withCache("clustered-cache", CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, byte[].class,
              ResourcePoolsBuilder.newResourcePoolsBuilder()
                  .with(ClusteredResourcePoolBuilder.clusteredDedicated(64, MemoryUnit.GB))));
  while (true) {
    try {
      cacheManager = clusteredCacheManagerBuilder.build(true); // this throws the TimeoutException
      break;
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
```

**Comment by kcleereman** [comment]
The active server blocks while a passive initializes: for a 128gb clustered cache the active blocks for approx. one minute while the passive initializes its off-heap store, and for a 512gb clustered cache the active blocks for approx. four minutes while the passive initializes its off-heap store

**Comment by henri-tremblay** [comment]
The behavior is "normal". Allocating such a amount takes time. The default timeout is 20 seconds. If you change it in the clustering service configuration (the lifecycle timeout) to something long, it should work.

I'm however looking at optimizing the allocation so we won't have this issue anymore.
