### ISSUE TITLE
Statistics Testing: Eviction Disk and Clustered

### ISSUE THREAD

**Issue by gibsong** [ehcache/ehcache3#1455]
Add tests to make sure the Eviction stats are correct for Disk and Clustered.

**Comment by gibsong** [comment]
This will include standalone and clustered testing of the following Eviction stats:
EvictionCount
EvictionLatencyMaximum
EvictionLatencyMinimum
EvictionLatencyAverage
EvictionRate

**Comment by chrisdennis** [comment]
@mathieucarbou could you close this if it's been done.

**Comment by mathieucarbou** [comment]
@chrisdennis @fossf : we decided to only have `Cache:EvictionCount` at the end. 
For this stat, unit test is done (correctness of value) and wiring up to M&M in system test is done also.
