### ISSUE TITLE
Add 'copying' CacheConfigurationBuilder factory method to support inline modification of configuration

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#1465]
In order to support programatic tweaking of CacheConfiguration objects (and indirectly Configurations) we should add the ability to seed a CacheConfigurationBuilder with an existing Configuration object.  This would then allow us to build a cache configuration that is derived from a proposed configuration in some sensible way.

**Comment by ljacomet** [comment]
Funny, I had the same thought earlier this week - so I am for it!
