### ISSUE TITLE
Missing package version in Export-Package header

### ISSUE THREAD

**Issue by nenko-tabakov** [ehcache/ehcache3#1475]
The MANIFEST.MF in ehcache-3.1.2 and ehcache-3.1.3 does not provide package version in the Export-Package header. While this won't prevent the jar from resolving in OSGI environment it might cause confusion and/or bad linking if a consumer bundle has versions in their Import-Package header.

**Comment by henri-tremblay** [comment]
Looking at the `MANIFEST.MF`, the exported packages should look like `org.ehcache;version="3.1.3"`

**Comment by ljacomet** [comment]
Looking at OSGi documentation, we should try to leverage http://bnd.bndtools.org/chapters/170-versioning.html and see if it works that way.

Of course we may then have to do some filtering on the files to apply the version from the project build file ...

**Comment by chrisdennis** [comment]
I think that the move to the `bnd` plugin under #2562 should handle this.  I've assigned it to myself and will close when that is confirmed.

**Comment by chrisdennis** [comment]
Resolved by merging of #2562
