### ISSUE TITLE
Warn when builders instance are not used - either built or used as source for a new builder

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#1483]
With the builder pattern we have adopted, you may forget to use a builder and thus miss some configuration and realise it only much later.
Another issue is the overloaded static `heap` method - see #1296 - which if used instead of the instance one could again cause the loss of builder state.

Idea to improve this: have a finalizer on `Builder` instances that will log whenever a builder gets reclaimed without having been used.

**Comment by chrisdennis** [comment]
This may be a reasonable enhancement, but the logging is unlikely to help much, and in the 6 years since this was filed I'm not aware of any customer or user needing help with this behavioral 'quirk'. The Javadoc also explicitly warns users about this behavior.
