### ISSUE TITLE
Request SPI change: Suggest a postInit method for service initialization

### ISSUE THREAD

**Issue by rkavanap** [ehcache/ehcache3#1509]
Since there is no start order in ehcache services, it creates a problem to initialize a service that may have some sort of dependency on another service.

The suggested workaround is to do a lazy initialization in all entry methods. While this works, there is something less OOey about this. The code duplicates. It is also error prone, as when a new method gets added in the service that needs this initialization, it may inadvertently gets missed out.

On the other end of the spectrum, it may be very difficult to build a start order within ehcache. So the request is that ehcache manager call a postInit() method AFTER all services have started up. This entails a SPI change.

**Comment by ljacomet** [comment]
After discussions with @chrisdennis we ended up deciding on different solution:
* Services will now fail to load if their dependency chain is not resolved
* Services will be started after their dependencies are started

This resolves the problem described above and even allows to formally declare that the `DefaultDiskResourceService` depends on the `LocalPersistenceService`. PR #1524 addressed the bulk of it, although there still needs to be some clean up around services and service factories.
