### ISSUE TITLE
DefaultLocalPersistenceServiceTest test failing on windows

### ISSUE THREAD

**Issue by AbfrmBlr** [ehcache/ehcache3#1511]
org.ehcache.impl.persistence.DefaultLocalPersistenceServiceTest > testFailsIfDirectoryDoesNotExistsAndIsNotCreated FAILED
    java.lang.AssertionError at DefaultLocalPersistenceServiceTest.java:91

org.ehcache.impl.persistence.DefaultLocalPersistenceServiceTest > testFailsIfDirectoryExistsButNotWritable FAILED
    java.lang.AssertionError at DefaultLocalPersistenceServiceTest.java:62

**Comment by henri-tremblay** [comment]
I tried it on Windows 10 and it worked perfectly. @AbfrmBlr can you investigate? The test is quite simple and on Windows it should in fact be bypassed because the `assumeTrue` should fail because setWritable is failing on Windows.

**Comment by AbfrmBlr** [comment]
I am on Windows 7 so will investigate this further.

**Comment by henri-tremblay** [comment]
I retried on Windows 7. Still working. So I'm officially passing the ball.

**Comment by AbfrmBlr** [comment]
Ok this fails intermittently. These tests pass intermittently on windows 7, I will do some investigation and update the issue.

**Comment by ljacomet** [comment]
@AbfrmBlr Any news on this?

**Comment by fossf** [comment]
no longer fails
