### ISSUE TITLE
MessageTrackerTest.testMessageTrackAndApplyMultiThreaded fails abruptly on cloudbees

### ISSUE THREAD

**Issue by AbfrmBlr** [ehcache/ehcache3#1520]
Either the test is racy or the MessageTracker itself has bug. I have observed this failing once on cloudbees

**Comment by AbfrmBlr** [comment]
This might also be due to that fact the operations return before retirement messages are applied. This might result in duplicate message accounting error prone

**Comment by henri-tremblay** [comment]
Fixed by replacing with platform message tracker
