### ISSUE TITLE
EhcacheStateServiceImpl is not thread safe

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#1525]
While the entity usage guarantees some protection because of the concurrency key mechanism, there still need to be thread safe with regards to messages happening on different concurrency keys.

For example, calls to `org.ehcache.clustered.server.EhcacheStateServiceImpl#getStore` will happen concurrently with `org.ehcache.clustered.server.EhcacheStateServiceImpl#createStore` but that means writing and reading to a non thread safe data structure.

**Comment by AbfrmBlr** [comment]
This should close #1418 as well.
