### ISSUE TITLE
Resource usage statistics

### ISSUE THREAD

**Issue by gibsong** [ehcache/ehcache3#1530]
Implement server side statistics.  Add stats for server side resource usage.

Update by @mathieucarbou:
- [x] Implement the observers (PR #1552 )
- [ ] Implement the stats (like StandardEhcacheStatistics) on the management providers for serevr stores and pools (depends on #1551)

**Comment by gibsong** [comment]
Here is the pull request: https://github.com/ehcache/ehcache3/pull/1552

**Comment by mathieucarbou** [comment]
@gibsong : i updated this ticket description to reflect the work done and that has to be done.

**Comment by mathieucarbou** [comment]
@gibsong : why did you close it ? it is still in progress!
