### ISSUE TITLE
Consider option for CacheLoaders to operate in conditional mutative paths

### ISSUE THREAD

**Issue by timeck** [ehcache/ehcache3#154]
For cache operations that are conditional based on existing values in the cache, putIfAbsent(), replace(), should the CacheLoader (if present) be used to load a value and thus influence the original operation?

A little more information about where this came from:
https://groups.google.com/d/msg/ehcache-dev/MXyAvaAAv1o/VR3gcZESuxAJ

**Comment by ljacomet** [comment]
Fairly confident this is obsolete - prioritizing to confirm

**Comment by ljacomet** [comment]
All CAS operations (`putIfAbsent(K, V)`, `replace(K, V)`, `replace(K, V, V)` and `remove(K, V)`) use the following guard:
`if (useLoaderInAtomics && cacheLoaderWriter != null) {`
where `useLoaderInAtomics` is only ever set to false in a default JSR-107 setup.
All native `CacheManager` / `Cache` construction set it to true and so does the `Jsr107Service` if configured properly.

Given this, nothing to be done here, so closing.
