### ISSUE TITLE
PR builds don't report tests results anymore

### ISSUE THREAD

**Issue by anthonydahanne** [ehcache/ehcache3#1540]
PR builds failing because of test failures don't report the list of failing tests anymore.
For example, it says "Test result (no failures)" https://ehcache.ci.cloudbees.com/job/ehcache3-pull-requests/3197/jdk=Oracle%20JDK%201.8(latest),label_exp=standard,testVM=8/ 

when actually there were tests failing : 
https://ehcache.ci.cloudbees.com/job/ehcache3-pull-requests/3197/jdk=Oracle%20JDK%201.8(latest),label_exp=standard,testVM=8/consoleFull

That forces developers to load the full console log; that's not very convenient and is clearly a regression

**Comment by akomakom** [comment]
Wrong junit publisher expression now that there is a test-results/test/ subdirectory.  Corrected in this job.  I don't see any others but if I missed other jobs with this issue, let me know.
