### ISSUE TITLE
put() returns before mutation is applied on passive

### ISSUE THREAD

**Issue by esebasti** [ehcache/ehcache3#1542]
I am observing it in my local environment. It seems mutation is replicated to passive through entity messenger but client doesn't wait for retire ack.  Is it expected?

**Comment by AbfrmBlr** [comment]
Put should only return after retire ack. Infact as I remember all the messages by default wait for retire ack. By the way how are you able to observer this ?

**Comment by esebasti** [comment]
Yes. Client receives retire ack before returning put call but the problem still remains same as active sends retire ack before mutation  is completed on passive.

**Comment by esebasti** [comment]
It is platform issue and being tracked by https://github.com/Terracotta-OSS/terracotta-core/issues/324

**Comment by esebasti** [comment]
Closing it as this issue was fixed in terracotta-core.
