### ISSUE TITLE
Enhance API to programmatically configure persistence directory when used as JCache provider

### ISSUE THREAD

**Issue by bwaldvogel** [ehcache/ehcache3#1545]
I’m referring to the question ["How to set the persistence directory to java.io.tmpdir" in ehcache-users](https://groups.google.com/d/msg/ehcache-users/SqoXe0Kdd3o/Br-Uo2nABQAJ).

Cache persistence can be configured programmatically using the native Ehcache API.
Example:
```java
CacheManagerBuilder.newCacheManagerBuilder()
    .with(CacheManagerBuilder.persistence(getStoragePath() + File.separator + "myData")
```

The [Ehcache 3.x JSR-107 documentation](http://www.ehcache.org/documentation/3.1/107.html) does not show a way to achieve this if Ehcache is used as JSR-107 provider.

Introduce a mechanism to configure the cache persistence (eg. the directory) programmatically when Ehcache is used as JCache provider.

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***

To be clear, this can be done as JCache offers `CachingProvider.getCacheManager(java.net.URI, java.lang.ClassLoader, java.util.Properties)` and we could use the `Properties` for this.

However, as soon as you want to benefit from Ehcache specific features in JCache, you will have to configure all your caches [using Ehcache APIs](http://www.ehcache.org/documentation/3.1/107.html#building-the-configuration-using-ehcache-apis).

Given this, I am interested to know more about your use case and what this feature will enable for you. Care to explain a bit more?

**Comment by alexsnaps** [comment]
@bwaldvogel I think you look at the problem from the wrong angle:

 - If you want to configure, using a config file, a JSR107 `Cache(Manager)`, you have to fall back to vendor specific configs (in this case an ehcache XML config file): http://www.ehcache.org/documentation/3.1/107.html#getting-jsr-107-caches-configured-through-ehcache-xml 
 - If you already configure `Cache` and `CacheManager` instance using the 107 APIs, Ehcache still lets you configure its 107 module in XML to make use of templates to "enhance" your 107 caches with Ehcache specific features (such as using disk): http://www.ehcache.org/documentation/3.1/107.html#supplement-jsr-107-configurations
 - Or, in that latter case, if you can change the code to use Ehcache specific types, you can configure a 107 Cache using Ehcache configs: http://www.ehcache.org/documentation/3.1/107.html#building-the-configuration-using-ehcache-apis 

I'm not entirely sure how this relates to the `java.io.tmpdir` issue though...

**Comment by bwaldvogel** [comment]
I’m currently configuring the JSR107 `Cache(Manager)` with this workaround:

```java
javax.cache.spi.CachingProvider cachingProvider = Caching.getCachingProvider();
Resource configLocation = context.getResource("classpath:ehcache.xml");
javax.cache.CacheManager cacheManager = cachingProvider.getCacheManager(configLocation.getURI(), cachingProvider.getDefaultClassLoader(), new Properties());
org.ehcache.config.CacheConfiguration<Object, Object> cacheConfiguration = CacheConfigurationBuilder.newCacheConfigurationBuilder(Object.class, Object.class,
	ResourcePoolsBuilder
		.heap(100)
		.disk(1, MemoryUnit.MB, true))
	.withExpiry(Expirations.timeToLiveExpiration(Duration.of(1, TimeUnit.HOURS)))
	.build();

cacheManager.createCache("myCache", Eh107Configuration.fromEhcacheCacheConfiguration(cacheConfiguration));
```

The `ehcache.xml`:
```xml
<eh:config xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
           xmlns:eh='http://www.ehcache.org/v3'
           xsi:schemaLocation="http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core-3.1.xsd">

    <eh:persistence directory="cache"/>

</eh:config>
```

I would like to get rid of the `ehcache.xml` and configure the persistence directory programmatically to be able to define it dynamically. Is it possible?

**Comment by alexsnaps** [comment]
@bwaldvogel Do I understand the issue right: what you are missing is a way to instantiate a JSR-107 `javax.cache.CacheManager ` with the underlying `org.ehcache.CacheManager` pre-configured. While this works using XML, as you did in the snippet above, you'd ideally want to achieve this solely programmatically... is that right? 

There may be a way already, I'd have to look into this a bit... but if there is not, this seems like a perfectly valid request to me.

**Comment by bwaldvogel** [comment]
@alexsnaps: yes, that’s pretty much what I meant.

**Comment by alexsnaps** [comment]
I looked a bit into this today:
```java
    CachingProvider provider = Caching.getCachingProvider("org.ehcache.jsr107.EhcacheCachingProvider");
    EhcacheCachingProvider ehcacheCachingProvider = (EhcacheCachingProvider) provider;
    ehcacheCachingProvider.getCacheManager(ehcacheCachingProvider.getDefaultURI(), createMyConfig() );
```

And `createMyConfig()` a config like so:
```java
  private org.ehcache.config.Configuration createMyConfig() {
    final File location = new File(System.getProperty("java.io.tmpdir")); // Or some other location from some random properties file
    return new DefaultConfiguration(this.getClass().getClassLoader(), new DefaultPersistenceConfiguration(location));
  }
```

I _think_ this should be about right...

**Comment by alexsnaps** [comment]
If that's correct, @ljacomet, maybe that's something worth adding to the doc?

**Comment by bwaldvogel** [comment]
It works for me, thanks.

**Comment by ljacomet** [comment]
@bwaldvogel Thanks for taking the time to report this indeed works for you.

@alexsnaps Indeed!
