### ISSUE TITLE
UserManagedCacheBuilder tries to create serializers that aren't needed

### ISSUE THREAD

**Issue by henri-tremblay** [ehcache/ehcache3#1554]
Can be reproduce by launching demo-01 with logging in demo. You will see warnings about serializers that can't be found (you need to open http://localhost:8080 to actually get the log).

This cache manager is using heap storage only and the keys and values of its only cache are stored by reference. So the serializer won't ever be used. There is no point in creating it nor looking for it.

**Comment by chrisdennis** [comment]
Fixed by #3122
