### ISSUE TITLE
Cache manager creation event is not logged

### ISSUE THREAD

**Issue by kedar031** [ehcache/ehcache3#1565]
Client version:

```
Implementation-Version: 3.2.0-SNAPSHOT 8951010795d604c762ead57db1e71f9
 d6d74367f
```

cache manager creation event is not logged by Active/Passive entity

**Comment by ljacomet** [comment]
Can you describe the kind of information you think is relevant and that you would want to see logged?

**Comment by kedar031** [comment]
Expecting following validations when user creates cachemanager on cluster with passive(s)
- On success, a simple event log (preferably INFO mode) like "EVENT: cachemanager `mycache` created" on both active and passive would do.
-On failure, event failure logged on Active without any trace on passive.

**Comment by chrisdennis** [comment]
Pretty sure entity creation is logged on the servers already.
