### ISSUE TITLE
References to obsolete 'fixed' and 'shared'

### ISSUE THREAD

**Issue by kedar031** [ehcache/ehcache3#1566]
[Ehcache documentation ](http://www.ehcache.org/documentation/3.1/clustered-cache.html#cache-manager-configuration-and-usage-of-server-side-resources) still refers to "fixed" and "shared" instead of `.clusteredDedicated` and `.clusteredShared` in the description

**Comment by ljacomet** [comment]
Fix needs to exist in `release/3.1` as well.
