### ISSUE TITLE
Missing cache entries on mirror.

### ISSUE THREAD

**Issue by esebasti** [ehcache/ehcache3#1577]
This happens when replicaion & sync operations are mixed up by bringing up mirror when series of mutations are progressing in active. It can be reproduced by the below test case. Here are the steps performed by test.

1)Start one server to become active
2)Perform put operations in multiple threads
3)Start mirror while put operations are progressing
4)Failover and verify the entries on new active which doesn't match with the entries on original active.

    //start one server first
    control.start(control.getTerracottaServer(0));
    //Create cache manager
    LOG.info("Started one server: " + control.getTerracottaServer(0).getServerSymbolicName());
    CacheManagerBuilder<PersistentCacheManager> builder = CacheManagerBuilder.newCacheManagerBuilder()
        .with(ClusteringServiceConfigurationBuilder.cluster(clusterURI)
            .autoCreate()
            .defaultServerResource("primary-server-resource")
            .resourcePool("resource-pool-a", 128, MemoryUnit.MB)
            .resourcePool("resource-pool-b", 128, MemoryUnit.MB, "secondary-server-resource"));
    PersistentCacheManager cacheManager = builder.build(true);
    //Create cache
    final Cache<Long, String> cache = cacheManager.createCache("cache1", CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, String.class,
        ResourcePoolsBuilder.newResourcePoolsBuilder()
            .with(ClusteredResourcePoolBuilder.clusteredDedicated("primary-server-resource", 128, MemoryUnit.MB))));

    //Spawn threads to perform put operations and start mirror in the middle of operations
    final int numEntriesActive = 3000;
    final int threads = 3;
    Callable<Void> task = new Callable<Void>() {
      @Override
      public Void call() throws Exception {
        for (; ; ) {
          int key = counter.incrementAndGet();
          if (key > numEntriesActive) {
            break;
          }
          cache.put((long)key, "value");
          Thread.sleep(5);
        }
        return null;
      }
    };
    ExecutorService executorService = Executors.newFixedThreadPool(threads);
    Collection<Future<Void>> futures = new ArrayList<Future<Void>>();
    for (int i = 0; i < threads; ++i) {
      futures.add(executorService.submit(task));
    }
    //start mirror while put operations are progressing on active`
    control.start(control.getTerracottaServer(1));

    for (Future<Void> f : futures) {
      f.get();
    }
    executorService.shutdown();

    //stop active so mirror takes over and compare the number of entries there on mirror
    control.stop(control.getTerracottaServer(0));
    int numEntriesOnMirror = 0;
    for (int i = 1; i <= numEntriesActive; ++i) {
      if (cache.get((long)i) != null) {
        ++numEntriesOnMirror;
      }
    }
    //this fails as number of entries in mirror less than expected.
    assertThat(numEntriesOnMirror).isEqualTo(numEntriesActive);

**Comment by cschanck** [comment]
Albin, how do you know that the mirror is up and fully replicated before you kill the active? A mirror is not really there until the passive replication is done, right? 

Does the "control.start(control.getTerracottaServer(1));" imply not just that the server is started but that replication is complete? My suspicion is that the mirror has not completed sync, leading to the behavior you see.

**Comment by chrisdennis** [comment]
It's not clear to me that this is a bug.  A better test of this would be having a bunch of counters being incremented by Client A, and Client B observing the counts.  The only "misbehavior" here would be if during or after the failure the Client B observes the counts dropping.  Only observing missing entries could just be an indication of the passive being aggressive about eviction.
