### ISSUE TITLE
Implement CopyProvider that abstracts SerializationProvider away in the by-value on-heap store

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#158]

**Comment by ljacomet** [comment]
Offer an API to do by value caching without relying on `Serialization`

**Comment by albinsuresh** [comment]
Here is a proposal for the user-facing APIs for store-by-value caching.

When store-by-value is enabled for a cache the user can configure the cache with custom `Copier` classes for keys and values to be used for copying. The user can create a copier by implementing the `Copier<T>` interface.

```java
public interface Copier<T> {
  /**
   * Creates a copy of the instance passed in.
   *
   * @param obj the instance to copy
   * @return the copy of the {@code obj} instance
   */
  T copy(T obj);
}

```

And the user would configure the copiers as follows:

```java

    CacheConfiguration<Description, Person> cacheConfiguration = CacheConfigurationBuilder.newCacheConfigurationBuilder()
        .add(new OnHeapStoreServiceConfiguration().storeByValue(true)) // <1>
        .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder().heap(10, EntryUnit.ENTRIES).build())
        .add(new DefaultCopierConfiguration<Description>(DescriptionCopier.class,
            CopierConfiguration.Type.KEY)) //// <2>
        .add(new DefaultCopierConfiguration<Person>(PersonCopier.class,
            CopierConfiguration.Type.VALUE)) //// <3>
        .buildConfig(Description.class, Person.class);

    CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
        .withCache("cache", cacheConfiguration)
        .build(true);

    Cache<Long, String> cache = cacheManager.getCache("cache", Long.class, String.class);

    cache.put(1L, "one");
    assertThat(cache.get(1L), equalTo("one"));

    cacheManager.close();

```

1. By default, objects stored on-heap are stored by reference. If you wish to store them by value (which requires
    copying them) then you have to set storeByValue to true.
2. Configure the copier to be used for keys. *DescriptionCopier* in this case  as the keys are *Description* objects.
3. Configure the copier to be used for values. *PersonCopier* in this case as the values are *Person* objects.

The custom types and the corresponding copiers used in the above code snippet are the following(just for reference):

```java

  private static class Description {
    int id;
    String alias;

    Description(Description other) {
      this.id = other.id;
      this.alias = other.alias;
    }
  }

  private static class Person {
    String name;
    int age;

    Person(Person other) {
      this.name = other.name;
      this.age = other.age;
    }
  }

  private static class DescriptionCopier implements Copier<Description> {

    @Override
    public Description copy(final Description obj) {
      return new Description(obj);
    }
  }

  private static class PersonCopier implements Copier<Person> {

    @Override
    public Person copy(final Person obj) {
      return new Person(obj);
    }
  }

```

Comments / feedback???

**Comment by ljacomet** [comment]
I like the general feel of the proposal as it matches existing `Serializer` usage.

Few questions that may be more implementation than high level design:

* How does this defaults? I want _by-value_ but do not configure anything else.
* Copy happens both on `put` and `get`?

**Comment by albinsuresh** [comment]
1. As for the defaults: if a copier is not configured, the serializers are used
2. JSR-107 mandates copying for both get and put. A snippet from the JSR:

"The default mechanism, called store-by-value, instructs an implementation to make a copy of application provided keys and values prior to storing them in a Cache and later to return a new copy of the entries when accessed from a Cache."

Are you suggesting added support for seperate `copyOnRead` and `copyOnWrite` configurations?

**Comment by albinsuresh** [comment]
Updated proposal with the new `Transformer` service:

With the introduction of transformers, the decision whether a cache is byValue or byRef is taken based on the registered transformer service. The user can configure the cache with an implementation of the `Transformer<O, T>` interface.

```java
public interface Transformer<O, T> {

  /**
   * Transform an object from its original form to a transformed form.
   *
   * @param original the object in its original form
   * @return the transformed form of the original object
   */
  T transform(O original);

  /**
   * Revert an object from its transformed form to the original form.
   *
   * @param transformed the transformed form of the object
   * @return the object in its original form
   */
  O revert(T transformed);

  /**
   * Check the equivalence of an object between its original and transformed forms.
   *
   * @param original the object in its original form to be compared
   * @param transformed the object in transformed form to be compared
   * @return true if the representations in the original and transformed forms are equivalent; false otherwise
   */
  boolean compareAcross(O original, T transformed);

  /**
   * Check the equivalence of two objects in their transformed forms.
   *
   * @param t1 the first object in the transformed form
   * @param t2 the second object in the transformed form
   * @return true if the transformed forms are equivalent; false otherwise
   */
  boolean compareTransformed(T t1, T t2);
}
```

We provide two helper transformers to the user to make the store-by-value and store-by-reference configurations easier. If the user wants a store-by-value cache he can choose to extend the `CopyTransformer<T>` class and just implement the _copy()_ method in it instead of implementing the `Transformer<O, T>` directly and implementing all the methods in it.

Similarly, if the user wants a store-by-reference cache, he can configure the cache with the `IdentityTransformer<T>` implementation directly.

The cache configuration with *transformers* would go as follows:

```java
    CacheConfiguration<Description, Person> cacheConfiguration = CacheConfigurationBuilder.newCacheConfigurationBuilder()
        .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder().heap(10, EntryUnit.ENTRIES).build())
        .add(new DefaultTransformerConfiguration<Description, Description>(IdentityTransformer.class,
            TransformerConfiguration.Type.KEY)) //// <1>
        .add(new DefaultTransformerConfiguration<Person, Person>(PersonCopier.class,
            TransformerConfiguration.Type.VALUE)) //// <2>
        .buildConfig(Description.class, Person.class);
```

1. Configure the transformer to be used for keys. Here we have configured it with the `IdentityTransformer`.
2. Configure the transformer to be used for values. Here we are using a custom `PersonCopier` transformer that extends the CopyTransformer for that purpose.

The `CopyTransformer` and `IdentityTransformer`(both provided by ehcache) for reference:

```java
public class IdentityTransformer<T> implements Transformer<T, T> {

  @Override
  public T transform(final T original) {
    return original;
  }

  @Override
  public T revert(final T transformed) {
    return transformed;
  }

  @Override
  public boolean compareAcross(final T original, final T transformed) {
    return compareTransformed(original, transformed);
  }

  @Override
  public boolean compareTransformed(final T t1, final T t2) {
    return t1.equals(t2);
  }
}



public abstract class CopyTransformer<T> implements Transformer<T, T> {

  @Override
  public T transform(final T original) {
    return copy(original);
  }

  @Override
  public T revert(final T transformed) {
    return copy(transformed);
  }

  @Override
  public boolean compareAcross(final T original, final T transformed) {
    return compareTransformed(original, transformed);
  }

  @Override
  public boolean compareTransformed(final T t1, final T t2) {
    return t1.equals(t2);
  }

  public abstract T copy(T other);

}
```

**Comment by albinsuresh** [comment]
In addition, if no transformers are configured, the cache will default to byRef storage(using the IdentityTransformer).
Future work: Provide a transformer that internally uses the serialization service for the transformation.

**Comment by albinsuresh** [comment]
Falling back to the initial proposal of Copiers. If a user does configure a custom copier of his own, the IdentityCopier will be used. The IdentityCopier does not really "copy" anything but returns the input object as it is and thus making a store-by-reference effect.

We will also provide another custom copier; the `SerializingCopier`; that internally uses serialization to perform the copying. So the user can choose to use this copier directly if he does not want to implement a copier on his own and still wants store-by-value.

**Comment by albinsuresh** [comment]
There is a bug around expiry events in by-value caches. The bug is a side effect of the id of value holders being lost when entries are moved from the higher tiers to the on-heap tier. This also needs to be fixed as part of this Copier work as the buggy code is revamped as part of this PR.

**Comment by albinsuresh** [comment]
As per the discussions we had, the `Copier` interface has changed. Here is the new `Copier` interface:
```java
public interface Copier<T> {
  /**
   * Creates a copy of the instance passed in.
   *
   * @param obj the instance to copy
   * @return the copy of the {@code obj} instance
   */
  T copyOnRead(T obj);

  /**
   * Creates a copy of the instance passed in.
   *
   * @param obj the instance to copy
   * @return the copy of the {@code obj} instance
   */
  T copyOnWrite(T obj);
}
```

**Comment by ljacomet** [comment]
After discussions with @alexsnaps and @lorban, I believe we need to revise the behaviour in case of using a template to override a JSR-107 configuration.

Currently PR #557 documents that no configuration will force by-ref.
We need to change that to an explicit override. That is:
* No copier config in template means use JSR-107 by-ref/by-val setting
* Copier in template means by-val
  * Unless copier is an `IdentityCopier` which then means by-ref
