### ISSUE TITLE
Ehcache 2-arg replace does not delegate to a 2-arg replace in the writer.

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#159]
Most of the concurrent methods currently delegate to equivalent concurrent methods on the CacheWriter interface.  This doesn't happen for the 2-arg replace - we should think about aligning all this stuff.

**Comment by alexsnaps** [comment]
@chrisdennis do you still believe this should be done? If so, we may want to discuss that tomorrow; if not can you close this (and label it as `invalid`)?

**Comment by chrisdennis** [comment]
We're fixing this under #163.
