### ISSUE TITLE
fix reprobeLength stat

### ISSUE THREAD

**Issue by gibsong** [ehcache/ehcache3#1601]
This stat is currently not implemented due to a cast from long to int.

**Comment by chrisdennis** [comment]
@mathieucarbou Is this a genuine problem that needs fixing?

**Comment by mathieucarbou** [comment]
@chrisdennis : I think this is related to the comment inside `ServerStoreImpl#getReprobeLength()` and the interface `OffHeapMapStatistics#reprobeLength()`
.
If we look at all the `reprobeLength()` / `getReprobeLength()` methods in Ehcache, their signatures do not always match. These are all internal stuff so it can be changed easily.

So it is not related to M&M at all but much more to the fact that Ehcache is not consistent I think.

M&M does not use this statistic, though, it doesn't mean we cannot expose it in Ehcache if we fix that.

**Comment by mathieucarbou** [comment]
@fossf @chrisdennis : this issue being assigned to me, do I need to take any action on it ?

**Comment by chrisdennis** [comment]
If it's not needed/desired by M&M then I'm inclined to not care about the typing inconsistencies.
