### ISSUE TITLE
Caching null values

### ISSUE THREAD

**Issue by anwfr** [ehcache/ehcache3#1607]
It looks like caching NULL values is not supported by Ehcache 3.

> A NullPointerException is raised from EhCache.put
> Caused by: java.lang.NullPointerException: null
> 	at org.ehcache.core.Ehcache.checkNonNull(Ehcache.java:615) ~[ehcache-3.1.3.jar:3.1.3 5a797f067d9718c1be978f5fdf2e05a87502b1c0]
> 	at org.ehcache.core.Ehcache.checkNonNull(Ehcache.java:621) ~[ehcache-3.1.3.jar:3.1.3 5a797f067d9718c1be978f5fdf2e05a87502b1c0]
> 	at org.ehcache.core.Ehcache.put(Ehcache.java:193) ~[ehcache-3.1.3.jar:3.1.3 5a797f067d9718c1be978f5fdf2e05a87502b1c0]
> 	at org.ehcache.jsr107.Eh107Cache.put(Eh107Cache.java:181) ~[ehcache-3.1.3.jar:3.1.3 5a797f067d9718c1be978f5fdf2e05a87502b1c0]

Can you confirm that this is intended behavior? Thx

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***

Indeed, you cannot cache a null value, this is also the behaviour of the JCache specification.

If you need this in your application, either create a sentinel value or wrap your values from your application.
