### ISSUE TITLE
Broken dependencies for ehcache-server module on Maven central

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#1615]
`ehcache-server` is deployed on Maven central with unaccessible dependencies (management-*):

http://repo1.maven.org/maven2/org/ehcache/modules/ehcache-server/3.2.0.beta1/ehcache-server-3.2.0.beta1.pom

Since `ehcache-server` is not meant to be used as a transitive dependency, we could just exclude this module from being deployed in central ? The kit is right, management dependencies are there.

**Comment by ljacomet** [comment]
Not deploying to Central would mean having to deploy to an internal location, making the release process more complicated.

As indeed it is not made to be used as a dependency, I do not find the issue major and would rather stick with a simpler deploy model.
