### ISSUE TITLE
Add GET, PUT, UPDATE, REMOVE, EVICT, and EXPIRE stats (standalone and clustered)

### ISSUE THREAD

**Issue by gibsong** [ehcache/ehcache3#1633]
Refactor statistics to register only specific operations.  Start at Cache level and once this is working implement for each tier.

Do for the following statistics/operations:
**1. Hit**

- Cache: The Cache Hit statistic is the sum of these 8 operation outcomes:

     1. BulkOps.GET_ALL_HITS
     2. CacheOperationOutcomes.GetOutcome.HIT_NO_LOADER
     3. CacheOperationOutcomes.GetOutcome.HIT_WITH_LOADER
     4. CacheOperationOutcomes.PutIfAbsentOutcome.PUT
     5. CacheOperationOutcomes.ReplaceOutcome.HIT
     6. CacheOperationOutcomes.ReplaceOutcome.MISS_PRESENT
     7. CacheOperationOutcomes.ConditionalRemoveOutcome.SUCCESS
     8. CacheOperationOutcomes.ConditionalRemoveOutcome.FAILURE_KEY_PRESENT

**Questions:**
Q1. Eh107CacheStatisticsMXBean.getHits() and getMiss() both add outcome CacheOperationOutcomes.PutIfAbsentOutcome.PUT to calculate the hit and miss sums. Isn't this operation outcome counted twice?  Shouldn't it only be counted as a Miss?

Q2. why is BulkOps.GET_ALL_HITS used in Eh107CacheStatisticsMXBean.getHits() instead of CacheOperationOutcomes.GetAllOutcome.SUCCESS?

- Tiers: TODO

**2. Miss**

- Cache: The Cache Miss statistic is the sum of these 6 operation outcomes:
     1. BulkOps.GET_ALL_MISS
     2. CacheOperationOutcomes.GetOutcome.MISS_NO_LOADER
     3. CacheOperationOutcomes.GetOutcome.MISS_WITH_LOADER
     4. CacheOperationOutcomes.PutIfAbsentOutcome.PUT
     5. CacheOperationOutcomes.ReplaceOutcome.MISS_NOT_PRESENT
     6. CacheOperationOutcomes.ConditionalRemoveOutcome.FAILURE_KEY_MISSING

**Question:** 
why is BulkOps.GET_ALL_MISS used in Eh107CacheStatisticsMXBean.getMisses() instead of CacheOperationOutcomes.GetAllOutcome.FAILURE?

- Tiers: TODO

**3. Put**
**Question**
Do i need to implement Put stats? I think I recall you saying they didn't make sense.

- Cache: The Cache Put statistic is the sum of these 5 operation outcomes:
     1. BulkOps.PUT_ALL
     2. CacheOperationOutcomes.PutOutcome.PUT
     3. CacheOperationOutcomes.PutOutcome.UPDATED
     4. CacheOperationOutcomes.PutIfAbsentOutcome.PUT
     5. CacheOperationOutcomes.ReplaceOutcome.HIT

- Tiers: TODO

**4. Update (Replace)**
**Question:**
Are update and replace the same?  The google doc references update, but there are only replace observers and outcomes.

- Cache: The Cache Update statistic is the sum of 2 operation outcomes:
     1. CacheOperationOutcomes.ReplaceOutcome.HIT
     2. CacheOperationOutcomes.PutOutcome.UPDATED

- Tiers: TODO

**5. Remove**

- Cache: The Cache Remove statistic is the sum of these 3 operation outcomes:
     1. BulkOps.REMOVE_ALL
     2. CacheOperationOutcomes.RemoveOutcome.SUCCESS
     3. CacheOperationOutcomes.ConditionalRemoveOutcome.SUCCESS

**Question:** 
why is BulkOps.REMOVE_ALL used in Eh107CacheStatisticsMXBean.getCacheRemovals() instead of CacheOperationOutcomes.RemoveAllOutcome.SUCCESS?

- Tiers: TODO

**6. Evict**

- Cache: The Cache Evict statistic is the sum of 1 operation outcome:
     1.  StoreOperationOutcomes.EvictionOutcome.SUCCESS

- Tiers: N/A The authoritative tier is the only tier that does eviction, thus we only need this tiers eviction count and this will be used as the cache eviction count.

**7. Expire** - There is no expiration observer on cache or clustered.  I only see an expiration observers on tiers: OnHeap, OffHeap and Disk.  Is this correct?
- Cache: TODO
- Tiers: TODO

No Ratios - this will be calculated in the TMS.
No Rates - this will be calculated in the TMS
No Latencies for now.

**Comment by gibsong** [comment]
iTrac https://itrac.eur.ad.sag/browse/TDB-1301

**Comment by ljacomet** [comment]
Had a long discussion with @gibsong @GaryWKeim @mathieucarbou and @chrisdennis on this - more info to come later but expect what's to be collected to change quite a lot.

**Comment by mathieucarbou** [comment]
@anthonydahanne : FYI.

**Comment by gibsong** [comment]
@ljacomet I updated my initial comment and added some questions within this comment.

**Comment by mathieucarbou** [comment]
@ljacomet @gibsong : would it be better to close this and move to #1684 the discussion ?

Stat computation will happen in TMS now....

The only goal of the `StandardEhcacheStatistics` now is to output all Ehcache counter values, in the form: `Tier:operation:outcom`, i.e. `Cache:get:HitNoLoader`, `Cache:get:HitWithLoader`, etc.
TMS wil ldo the Cache:Hit computation based on what is done in the google doc and the jsr107 mbean as example.

**Comment by mathieucarbou** [comment]
as discussed with @gibsong, closing since this is a work item logged in #1684
