### ISSUE TITLE
Decouple event creation from event firing (as a way to resolve current issues)

### ISSUE THREAD

**Issue by vfunshteyn** [ehcache/ehcache3#165]
As described here, the currently chosen model of delivering events (at cache level, within lambda compute functions) may fire mutative events too optimistically: https://groups.google.com/forum/#!topic/ehcache-dev/N_UTJKIlCNI

While this may be undetectable by 107's TCK, in a longer term we may want to do something about it.

**Comment by ljacomet** [comment]
Timeboxed investigation: 1 day then discuss with team

**Comment by AbfrmBlr** [comment]
One obvious way to solve this is to push all the event firing responsibility at Stores. This will essentially require modifying the internal data structures used by respective Stores. In this way we control that an event is only fired when the mutation in Store is successful, maintaining contract for event listeners provided by JSR spec.

The pros is that it works, but the cons is that it will require extensive testing to make sure that behavior of event firing remains same across the Stores(which is not the case as of now) as every Store gets to manipulate the event firing mechanism.

For the local stores, current event firing mechanism is not an issue actually but in case of clustered stores, this is require a change.

For all the local stores, even if the event is fired before the actual mutation  is done in data structure, the failure at store can only be attributed to reasons which cause system failure, and recovering back from it is anyways not possible like OOME, disk failure etc.

**Comment by AbfrmBlr** [comment]
Just clarification in case it is not properly conveyed :- The idea is to modify code flow in Authoritative tiers as those are the places which source of truth for all mutations.

**Comment by ljacomet** [comment]
From dev meeting on July 30th, we discussed that the end result of the event subsystem should be a decoupling between event creation and event firing.

Issue title and type updated to reflect this.

**Comment by rishabhmonga** [comment]
Please follow the link to find proposed approach :
https://groups.google.com/d/msg/ehcache-dev/EJNFrstWM8c/tk8bKUeiAwAJ

**Comment by rishabhmonga** [comment]
As per discussion, the contract of event notification will change, depending on what kind of listeners are registered. In the case where any of the listeners is `ORDERED`, `EventOrdering` for all listeners will become `ORDERED`

**Comment by rishabhmonga** [comment]
In edge cases for example where updating a mapping, with `OFFHEAP` or `DISK` present, causes that mapping to be evicted before the updated mapping can be added. Here, the order of the update and eviction events is not correctly reported. This is due to the fact that the update event is created before the eviction events are generated. Since the put operation happens as a result of call to a memoized method, a new update event will never be generated, thus causing incorrect event ordering. Handling this edge case would mean maintaining the event order queue at event dispatch rather than at event creation. But since event dispatch takes place in worker threads, the calling thread's thread-local event order cannot be used. As per today's discussion, this scenario would not be handle right now. However a (ignored) test case has been added to verify this scenario when its handled.

**Comment by rishabhmonga** [comment]
```java
public void onEvent(CacheEvent<K, V> event) {
    eventThreadLocal.add(cacheEventWrapper);
//Catering to multiple `Cache` events for the same key by marking the prior ones failed
    markFailedCacheEventsInThreadLocal()	
    
if(Ordered Listeners Present) {
      keyBasedEventQueueMap.get(event.getKey()).add(cacheEventWrapper);
    }
  }

  public void fireEventsInThreadLocal() {
    while (!eventThreadLocal.get().isEmpty()) {
      dispatchEvent(eventThreadLocal.get().remove());
    }
  }

  private void dispatchEvent() {
    cacheEventWrapper.markFireable();
    if(cacheEventWrapper != keyBasedEventQueue.peek()) {
      // wait for event to get fired
      return;
    } else {
      while(keyBasedEventQueue.peek().isFireable || keyBasedEventQueue.peek) {

//fire event for all sync Listeners
        Future f = eventDispatcher.dispatch(cacheEventWrapper, syncListenerSet);	

//fire event for all aSync Listeners        
eventDispatcher.dispatch(cacheEventWrapper, aSyncListenerSet);	

//wait for sync firing to complete
        f.get();	

        cacheEventWrapper.markFired();
        keyBasedEventQueue.remove();
      }
    }
    // if queue empty remove queue from map;
  }
```

**Comment by rishabhmonga** [comment]
````
public void onEvent(CacheEvent<K, V> event) {
    eventThreadLocal.add(cacheEventWrapper);
//Catering to multiple `Cache` events for the same key by marking the prior ones failed
    markFailedCacheEventsInThreadLocal()   
 
if(Ordered Listeners Present) {
      keyBasedEventQueueMap.get(event.getKey()).add(cacheEventWrapper);
    }
  }
 
  public void fireEventsInThreadLocal() {
    while (!eventThreadLocal.get().isEmpty()) {
      dispatchEvent(eventThreadLocal.get().remove());
    }
  }
 
  private void dispatchEvent() {
    cacheEventWrapper.markFireable();
    if(cacheEventWrapper != keyBasedEventQueue.peek()) {
      // wait for event to get fired
      return;
    } else {
      while(!keyBasedEventQueue.isEmpty() || keyBasedEventQueue.peek().isFireable) {
 
//fire event for all sync Listeners
        Future f = eventDispatcher.dispatch(cacheEventWrapper, syncListenerSet);   
 
//fire event for all aSync Listeners       
eventDispatcher.dispatch(cacheEventWrapper, aSyncListenerSet); 
 
//wait for sync firing to complete
        f.get();   
 
        cacheEventWrapper.markFired();
        keyBasedEventQueue.remove();
      }
    }
    // if queue empty remove queue from map;
  }
 
````

**Comment by ljacomet** [comment]
PR #574 from @albinsuresh made me realise that we have an issue. The `OnHeapStore.iterator()` can expiry entries and doing so does fire an event. But callers will not go through the _firing_ step which is handled only at the `Cache` level for the moment.

**Comment by ljacomet** [comment]
There have been discussions on pushing the whole eventing responsibility down to the store, if that happens, then we need to clean up code as suggested in #215.

**Comment by ljacomet** [comment]
Resuming work on this.

From what we learned at past attempts, the following remains to be done:
* Move all eventing down to the `Store` level
* Make sure there is near zero operations overhead when no listeners are configured
