### ISSUE TITLE
Implement missing client clusteredStore stats

### ISSUE THREAD

**Issue by gibsong** [ehcache/ehcache3#1670]
These passThroughStatistics always return -1.  These stats need to be implemented:
1. mappings
2. maxMappings
3. allocateMemory
4. occupiedMemory

**Comment by ljacomet** [comment]
No, they are correct. On the client side, the clustered store has no mappings, neither notion of max mappings nor of memory consumption.

**Comment by mathieucarbou** [comment]
Is it worth keeping them then ? Because the fact is that they are seen by management, thus collected. It's  resource consumption for nothing.

**Comment by ljacomet** [comment]
They need to be kept for consistency and being able to return values to stats user when the authority is a clustered tier.
