### ISSUE TITLE
Improve failure handling when no offheap-resource are available

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#1675]
Currently, we have to create the entity and fail on the first invoke - which is usually the configure one.

When Terracotta-OSS/terracotta-apis#181 is integrated, this should be changed so that we can fail entity creation instead, effectively preventing any entity to exist unless there is at least one offheap-resource defined.

**Comment by AbfrmBlr** [comment]
This is one is obsolete now as the work has started for cache as entities.
