### ISSUE TITLE
Evicted entries are not same between active & passive

### ISSUE THREAD

**Issue by esebasti** [ehcache/ehcache3#1688]
I am observing during a test that evicted entries from offheap store due to resource constraint between active & passive are not same always. Is it expected?

**Comment by esebasti** [comment]
Here is the test case.

    //start one server
    control.start(control.getTerracottaServer(0));

    //cache manager configuration
    final CacheManagerBuilder<PersistentCacheManager> builder = CacheManagerBuilder.newCacheManagerBuilder()
        .with(ClusteringServiceConfigurationBuilder.cluster(clusterURI)
            .autoCreate()
            .defaultServerResource("primary-server-resource")
            .resourcePool("resource-pool-a", 256, MemoryUnit.MB)
            .resourcePool("resource-pool-b", 256, MemoryUnit.MB, "secondary-server-resource"))
        .withCache("cache1", CacheConfigurationBuilder.newCacheConfigurationBuilder(Integer.class, Byte[].class,
            ResourcePoolsBuilder.newResourcePoolsBuilder()
                .with(ClusteredResourcePoolBuilder.clusteredDedicated("primary-server-resource", 2, MemoryUnit.MB)))
            .add(ClusteredStoreConfigurationBuilder.withConsistency(Consistency.STRONG)));
    PersistentCacheManager cacheManager = builder.build(true);
    Cache<Integer,Byte[]> cache = cacheManager.getCache("cache1",Integer.class,Byte[].class);

    //Load large number of entries on cache to trigger eviction.
    int counter = 1;
    int numEntries = 3 * 1024;
    for(; counter <= numEntries/2; ++counter) {
      cache.put(counter, new Byte[1024]);
      Thread.sleep(1);
    }
    //start passive & continue with load.
    control.start(control.getTerracottaServer(1));
    for(; counter <= numEntries; ++counter) {
      cache.put(counter, new Byte[1024]);
      Thread.sleep(1);
    }

    //Evicted entries on active
    counter = 1;
    List<Integer> evictedKeysOnActive = new ArrayList<Integer>();
    for(; counter <= numEntries; ++counter) {
      if (cache.get(counter) == null) {
        evictedKeysOnActive.add(counter);
      }
    }

    //Failover to get evicted entries on passive
    control.stop(control.getTerracottaServer(0));
    waitForActive();
    List<Integer> evictedKeysOnPassive = new ArrayList<Integer>();
    counter = 1;
    for(; counter <= numEntries; ++counter) {
      if (cache.get(counter) == null) {
        evictedKeysOnPassive.add(counter);
      }
    }

    assertThat(evictedKeysOnPassive.size()).isEqualTo(evictedKeysOnActive.size());
    assertThat(evictedKeysOnPassive).isEqualTo(evictedKeysOnActive);

**Comment by ljacomet** [comment]
This is as designed and accounted for in the synchronisation logic.
