### ISSUE TITLE
Add notifications on server entities (SYNC_START and SYNC_END)

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#1700]
@GaryWKeim @anthonydahanne : FYI

**Comment by chrisdennis** [comment]
You call this a feature request? You've been talking to PM too much.

**Comment by mathieucarbou** [comment]
@GaryWKeim @anthonydahanne @chrisdennis @fossf : I think that in M&M we wanted to know when a sync starts, end, and its duration, by using `syncEntityEnd` and `syncEntityStart`. This has never been done.

We have implemented an example of how it could be done (at least a starting point) in `PassiveCacheServerEntity` in tc-platform: which is our testing entity for system tests.

**Comment by chrisdennis** [comment]
Doesn't this belong as a feature request against https://github.com/Terracotta-OSS/terracotta-core ? That way you could monitor sync-ing of all entities, and then maybe put that all in the context of a larger server sync.
