### ISSUE TITLE
Resource pool created even when allocation fails

### ISSUE THREAD

**Issue by henri-tremblay** [ehcache/ehcache3#1714]
If we fail to allocate a clustered resource pool, the pool is still created (probably in some invalid state).

To reproduce, launch a TCServer in local with the following configuration

```xml
<?xml version="1.0" encoding="UTF-8"?>
<tc-config xmlns="http://www.terracotta.org/config"
             xmlns:ohr="http://www.terracotta.org/config/offheap-resource">

  <plugins>
    <config>
      <ohr:offheap-resources>
        <ohr:resource name="primary-server-resource" unit="GB">1</ohr:resource>
      </ohr:offheap-resources>
    </config>
  </plugins>
</tc-config>
```

The launch the following test. The first creation will fail (requested memory is too low) and the second will also fail (pool already exist).

The second creation should have work.

```java
public class AlreadyExists {

    @Test
    public void test() {
        try {
            createCacheManager(10);
        } catch(StateTransitionException e) {
            assertEquals(InvalidOperationException.class, getRootCause(e).getClass());
        }
        createCacheManager(100);
    }

    private static PersistentCacheManager createCacheManager(long size) {
        ClusteringServiceConfigurationBuilder clusteringServiceConfigurationBuilder = ClusteringServiceConfigurationBuilder.cluster(URI.create("terracotta://localhost:9510"));
        ServerSideConfigurationBuilder serverSideConfigurationBuilder = clusteringServiceConfigurationBuilder.autoCreate()
            .defaultServerResource("primary-server-resource");

        CacheManagerBuilder<PersistentCacheManager> cacheManagerBuilder =
            CacheManagerBuilder.newCacheManagerBuilder()
                .with(serverSideConfigurationBuilder)
                .withCache("test-cache", CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, String.class,
                    ResourcePoolsBuilder.newResourcePoolsBuilder()
                        .with(ClusteredResourcePoolBuilder.clusteredDedicated(size, MemoryUnit.KB))
                ).add(new ClusteredStoreConfiguration(Consistency.EVENTUAL)));

        return cacheManagerBuilder.build(true);
    }

    private static Throwable getRootCause(Throwable e) {
        Throwable current = e;
        while(current.getCause() != null) {
            current = current.getCause();
        }
        return current;
    }
}
```

**Comment by AbfrmBlr** [comment]
The `ServerStore` initialization fails due to too low memory requirement, because some math went wrong during `OffHeapChainMap` initialization. Due this fact, that pool allocation was successful, server store creation failed which failed to clean up already done pool allocation. The fix is simple to do the clean up, but I am confused, Is there a lower limit for sizing caches? If yes then we should rather validate that before allocating pool itself.

**Comment by AbfrmBlr** [comment]
For a clustered cache, minimum amount of memory is 2KB * No. of segments. Since no. of segments per cache is 16(which is hardcoded for now), the minimum memory required for successful allocation is 32 KB.

**Comment by AbfrmBlr** [comment]
For dedicated resource pools this can be calculated, but this can really misfire with shared resource pools, wondering what can be the minimum for shared resource pools.
