### ISSUE TITLE
Logging of life cycle operations in server log

### ISSUE THREAD

**Issue by esebasti** [ehcache/ehcache3#1717]
Result of life cycle operations need to be logged and available in server logs(both active & passive if applicable)

1)Creation of cache manager
2)Client connecting to cache manager
3)Creation of cluster store
4)Client connecting to cluster store
5)Client disconnecting from cluster store
6)Destroy of cluster store
7)Client disconnecting from cache manager
8)Destroy of cache manager

**Comment by ljacomet** [comment]
Requires Terracotta server changes

**Comment by ljacomet** [comment]
A terracotta-platform release with terracotta-oss/terracotta-platform#246 will enable this.

**Comment by ljacomet** [comment]
This has been fixed on master through the merge of #1753
