### ISSUE TITLE
Mirror doesn't fail fast

### ISSUE THREAD

**Issue by esebasti** [ehcache/ehcache3#1733]
Server doesn't crash when creating cluster store fails on mirror(ex: due to resource constraint). There is no indication of this failure to client until fail over happens to mirror and it tries to perform some operation on new active.

**Comment by ljacomet** [comment]
Looks like we swallow all exceptions in the `EhcachePassiveEntity.invoke`. This is wrong. For lifecycle issue, we need to let them escape so that the crash model of the server is exercised. Otherwise we are delaying the problem to the failover ... and risk loosing a cluster then.
