### ISSUE TITLE
Provide means to enforce ordering for xml schema processing

### ISSUE THREAD

**Issue by albinsuresh** [ehcache/ehcache3#1761]
Provide a way to define an order in which extension schemas are looked up and processed by the Ehacache xml configuration parser. Such requirement will arise when an existing ehcache extension schema like the clustered extension is extended further. In that case the ehcache clustered extension should be loaded and processed before the new extension is processed.

**Comment by chrisdennis** [comment]
Fixed as of 3.10.0 (e7e4d17484e1f2972addd3cab6243545ebf1e1ca)
