### ISSUE TITLE
Compute correctly tier statistics

### ISSUE THREAD

**Issue by henri-tremblay** [ehcache/ehcache3#1774]
Currently stats on tiers (returned by the `StatisticsService`) are calculated simply but should in fact follow these rules:

|Hit	|Miss	|Put	|Update	|Removal	|Expiry	|Eviction|
|----|---------|----|---------|---------|---------|--------|
|No	 | No	|No	  |No	|No	|It	|No
|Yes|	Yes|	No	|No	|No	|depends|	No
|Yes|	Yes|	No	|No	|No	|on|	No
|Yes|	Yes|	No	|No	|No	|what|	No
|Yes|	Yes|	Yes	|Yes|	No|	we	|Yes
|Yes|	Yes|	No	|No	|Yes|	check	|No
|Yes|	Yes|	Yes	|Yes|	No|	expirations|	Yes
|Yes|	Yes|	Yes, if setValue was called	|Yes, if setValue was called	|Yes, if remove was called	| |Yes
|Yes|	Yes|	Yes, if setValue was called	|Yes, if setValue was called	|Yes, if remove was called	| |Yes
|Yes|	Yes|	No	|No	|Yes, if remove was called|	|	No
|No	 | No	|No	  |No	|No		| |Yes
|No	 | No	|Yes	|Yes	|No	| |	Yes
|No	 | No	|Yes	|Yes	|No	| |	Yes
|Yes|Yes|	Yes	|Yes	|No	| |	Yes
|No	 | No	|No	  |No	|Yes| |		No
|Yes|Yes|	No	|No	|Yes| |		No
|No	 | No	|No	  |No	|Yes| |		No
|No	 | No	|No	  |No	|Yes| |		No
|Yes|	Yes|	Yes	|Yes|	No|	|	Yes
|Yes|	Yes|	Yes	|Yes|	No|	|	Yes
|Yes|	No|	No	  |No	|No	| |	No

**Comment by anthonydahanne** [comment]
@henri-tremblay can you please reference the "spec" you relied on to gather those definitions ?
thank you !

**Comment by henri-tremblay** [comment]
Most of it is taken from JSR107 section 12.4.
