### ISSUE TITLE
FileBasedStateRepository uses the wrong classloader for deserialization

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#1785]
When we deserialize what could potentially be user classes we should make sure to use the cache (or cache managers) classloader otherwise we may not be able to access all the necessary classes.  The FileBasedStateRepository does not do this and could be deserializing classes that belong to the user (depending on what the consuming service is doing).  This type should probably use the following loaders in order: TCCL, Cache/CacheManager Loader, "Latest User Defined ClassLoader".

**Comment by vaibhavsrivastava07** [comment]
Fixed in:
#3140 - master
#3144 - release/3.9
