### ISSUE TITLE
Align naming in clustering documentation

### ISSUE THREAD

**Issue by albinsuresh** [ehcache/ehcache3#1854]
The terms "clustered" tier manager and "clustered" tier are still used in docs even though they were changed to "cluster tier manager" and "cluster tier" respectively in the code. The same needs to happen in the docs as well.

**Comment by ljacomet** [comment]
As I commented on the PR:

> First of all, changing builder APIs and XSDs is effectively an API change - so a no go.
> Second, I believe in XSD and builders, clustered makes sense as you describe what you want. While for entities, cluster makes more sense as it is a state of it.
> In short, we have I believe once again an overloaded term.
> When _tier_ is used to mean an Ehcache tier, like heap, then the prefix should be _clustered_. And when we use _cluster tier_ that describes the tier on the cluster.
