### ISSUE TITLE
Need for PoolAllocation sub interfaces

### ISSUE THREAD

**Issue by anthonydahanne** [ehcache/ehcache3#1856]
The interface PoolAllocation is directly implemented by Dedicated and Shared in the code base.

Having  2 new sub interfaces such as : DedicatedPoolAllocation and SharedPoolAllocation would allow the management and monitoring stack to provide sizes and resourcePoolNames for several implementations of Dedicated and Shared pools, via the ServerStoreSettingsManagementProvider

**Comment by mathieucarbou** [comment]
@ljacomet @anthonydahanne : so in conclusion... Do I start working on these new interfaces ? And also making the `ServerStoreSettingsManagementProvider` overridable (which is easy) ?

**Comment by anthonydahanne** [comment]
@mathieucarbou sorry I did not see your comment
so I have something working here for me; feel free to comment !
