### ISSUE TITLE
Fix randomly failing test: BasicClusteredCacheOpsReplicationWithMultipleClientsTest

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#1859]
I had to comment this test: `BasicClusteredCacheOpsReplicationWithMultipleClientsTest ` because it is randomly failing and prvent the PR build to pass.

See this PR: https://github.com/ehcache/ehcache3/pull/1852

```
Test Result (1 failure / +1)
org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationWithMultipleClientsTest.testBulkOps[consistency=STRONG]

```

then:

```
Test Result (1 failure / ±0)
org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationWithMultipleClientsTest.testBulkOps[consistency=EVENTUAL]
```

Seen with @GaryWKeim @anthonydahanne @gibsong @ankitamaurya

**Comment by AbfrmBlr** [comment]
Closing this as #1782 is for the same known problem..
