### ISSUE TITLE
The persistent flag for OffHeapDiskStore only works if you close the cache manager

### ISSUE THREAD

**Issue by kwesterfeld** [ehcache/ehcache3#1907]
In order for the persistent=true to work with a disk cache, I had to close the cache manager in order for it to write the index file.  In looking at the code, it seems close() is the only time the index file is written, and as a result the persistent capability of this tier is nearly useless for our use case.

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***

Indeed, that is the behaviour of the open source disk store, it is not crash proof. The documentation is [very](http://www.ehcache.org/documentation/3.3/tiering.html#persistent-tiers) [explicit](http://www.ehcache.org/documentation/3.3/getting-started.html#disk-persistence) about it.

So closing this as _won't fix_.

**Comment by kwesterfeld** [comment]
Thanks very much for the speedy response, and sorry I missed this in the documentation.   I tend to read code first, which is a bad habit!
