### ISSUE TITLE
When configuring Eh107Cache programmatically Mbeans are not registered

### ISSUE THREAD

**Issue by kubagruszka** [ehcache/ehcache3#1928]
When I try to instantiate `Eh107Cache` using `CacheConfigurationBuilder` and appropriate `Jsr107CacheConfiguration` the `CacheConfiguration` has set management and statistics enabled (proved by `ConfigStatsManagementActivationTest#testEnableCacheLevelProgrammatic`) but effectively the MBeans aren't registered. This is because the `Eh107CacheManager#enableManagement` and  `Eh107CacheManager#enableStatistics` are invoked only if we provide non `Eh107Configuration.Eh107ConfigurationWrapper` instance of configuration or during `Eh107CacheManager#refreshAllCaches` via `Eh107CacheManager#getCacheNames` which I've used as workaround to make it working for me. Please consider following code I use to instantiate the Eh107Cache:

```java
    public <K, V> Cache<K, V> createCache(Class<K> keyClass, Class<V> valueClass) {
        CachingProvider provider = Caching.getCachingProvider(EhcacheCachingProvider.class.getCanonicalName());
        CacheManager cacheManager = provider.getCacheManager();
        Configuration<K, V> configuration = createConfiguration(keyClass, valueClass);
        Cache<K, V> cache = cacheManager.createCache(getName(), configuration);
        //Following code is required to refresh the caches and actually perform the MBean registration
        //This seems to be a bug in EhCache107 implementation.
        cacheManager.getCacheNames();
        return cache;
    }

    private <K, V> Configuration<K, V> createConfiguration(Class<K> keyClass, Class<V> valueClass) {
        org.ehcache.config.CacheConfiguration<K, V> cacheConfiguration = CacheConfigurationBuilder.newCacheConfigurationBuilder(keyClass, valueClass,
                ResourcePoolsBuilder.heap(maxNrObjectsCached))
                .withExpiry(Expirations.timeToLiveExpiration(org.ehcache.expiry.Duration.of(timeToLive.toMilliseconds(), TimeUnit.MILLISECONDS)))
                .add(new Jsr107CacheConfiguration(ConfigurationElementState.ENABLED, ConfigurationElementState.ENABLED))
                .build();
        return Eh107Configuration.fromEhcacheCacheConfiguration(cacheConfiguration);
    }
```

**Comment by henri-tremblay** [comment]
You are absolutely right. I've noticed that some times ago and should have filed it. Thanks for the nice explanation and workaround.
