### ISSUE TITLE
cache cleaned to empty when i restart a server

### ISSUE THREAD

**Issue by tongheshang** [ehcache/ehcache3#1980]
I have two servers A and B, they can synchronize their cache in each other server. when server A was restarted for some reasons and another server B's cache became empty. But i think the restart one should get cache from server B, instead of  server B's cache cleaned to empty, that's right? How can i config ehcache.xml or code in .java file so that i can achieve the purpose?

**Comment by tongheshang** [comment]
I was puzzled by this question for a long time, can anybody help me?

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***

Given this is really a usage question more than a bug report, closing and asking for the conversation to happen on the mailing list.
