### ISSUE TITLE
destroyCache should use the "regular" removeCache method

### ISSUE THREAD

**Issue by anthonydahanne** [ehcache/ehcache3#1996]
in [EhcacheManager#683](https://github.com/ehcache/ehcache3/blob/e496850c8bf8191a30d7a783c80944c56d2cdc74/core/src/main/java/org/ehcache/core/EhcacheManager.java#L683) , ```destroyCache``` is calling ```removeAndCloseWithoutNotice``` that unfortunately does not trigger ```cacheRemoved```.

It can be problematic, since the user can destroy a cache programmatically without the monitoring capabilities knowing that a cache was indeed removed

**Comment by ljacomet** [comment]
I flagged this a bug since destroying a cache that is live on the cache manager effectively removes it first. So missing the notification is wrong.

**Comment by ljacomet** [comment]
Needs to be daggy fixed to 3.2, 3.3 and master

**Comment by ljacomet** [comment]
Looks like we have an ordering issue between the remove and the notification - see #2008
