### ISSUE TITLE
offheap warning messages should be tested

### ISSUE THREAD

**Issue by anthonydahanne** [ehcache/ehcache3#2063]
logging messages have been added in case of server side offheap resource depletion

https://github.com/ehcache/ehcache3/pull/2062/

we should write a system test (passthrough or galvan) to make sure those messages  appear on a given configured appender, when a server side offheap resource reaches depletion thresholds.

**Comment by chrisdennis** [comment]
You asking us to write a test in Ehcache that validates the behavior of platform code? If thats the case then it's a non starter.
