### ISSUE TITLE
Once the fix to Issue 2041 is merged we can removed the client state map

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#2087]
Once #2041 is fixed the `ClientState` objects and the map they are held in serve no purpose outside of the management code.  This means we can push the map down (or potentially remove it completely) inside the management code.

**Comment by anthonydahanne** [comment]
as seen with @mathieucarbou , we're currently not relying on the ClientStateSettingsManagementProvider now - so good to go
