### ISSUE TITLE
Have the ResilienceStrategy as a Service, so that we can override it

### ISSUE THREAD

**Issue by anthonydahanne** [ehcache/ehcache3#2095]
In Ehcache, around line #126 , we hard-wire the ResilienceStrategy : 
```
    if (store instanceof RecoveryCache) {
      this.resilienceStrategy = new LoggingRobustResilienceStrategy<K, V>(castToRecoveryCache(store));
    } else {
      this.resilienceStrategy = new LoggingRobustResilienceStrategy<K, V>(recoveryCache(store));
    }
```

It would be interesting to be able to customize the ResilienceStrategy, passing it as a service; an example of ResilienceStrategy would be "ThroughRuntimeExceptionResilienceStrategy" or "SendSMSResilienceStrategy"

**Comment by ljacomet** [comment]
Closing as duplicate of #52 - this is indeed the plan
