### ISSUE TITLE
Stale MBeans in Tomcat

### ISSUE THREAD

**Issue by cosenmarco** [ehcache/ehcache3#2103]
Hi, I think there's a bug with ehcache, JSR107 MBeans and Tomcat.
The steps to reproduce are the following:
1. Deploy the app on a fresh start of Tomcat and verify that MBeans are reporting statistics for the caches correctly
2. Re-deploy the app without restarting Tomcat and verify that the statistics are frozen to the last value before the re-deploy.

I'm now aware about any type of teardown that needs to be done when the webapp gets undeployed.

This is how I initialize everything:
```xml
<config
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xmlns:jsr107='http://www.ehcache.org/v3/jsr107'
  xmlns='http://www.ehcache.org/v3'>

  <service>
    <jsr107:defaults enable-management="false" enable-statistics="true"/>
  </service>

  <cache alias="organization" uses-template="heap-100-12h" />
  <cache alias="group" uses-template="heap-100-12h" />

  <cache-template name="heap-100-12h">
    <expiry>
      <ttl unit="hours">12</ttl>
    </expiry>
    <heap>100</heap>
  </cache-template>
</config>
```

And since I don't use Spring Boot but just Spring CDI:
```java
package com.xxxxxxxxx;

import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.CacheManager;
import org.springframework.cache.jcache.JCacheCacheManager;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.Resource;

import javax.annotation.Nonnull;
import javax.cache.Caching;
import javax.cache.spi.CachingProvider;
import javax.inject.Inject;
import java.io.IOException;

@Configuration
@Slf4j
public class CacheManagerFactory {
  private final ApplicationContext context;

  @Inject
  public CacheManagerFactory(@Nonnull ApplicationContext context ) {
    this.context = context;
  }

  @Bean("cacheManager")
  public CacheManager buildCacheManager()
      throws IOException {
    CachingProvider provider = Caching.getCachingProvider();
    Resource cacheConfig = context.getResource("classpath:ehcache.xml");
    javax.cache.CacheManager manager = provider.getCacheManager(cacheConfig.getURI(),
      CacheManagerFactory.class.getClassLoader());

    return new JCacheCacheManager(manager);
  }
}
```
Versions:
Tomcat 8.0.35
Ehcache 3.3.1
Spring 4.3.10

**Comment by cosenmarco** [comment]
Update: As a quick workaround I'm cleaning up the MBeans manually when the Spring context is destroyed and this seems to work.
Code (my factory implements DisposableBean now):
```java
  @Override
  public void destroy() throws Exception {
    log.info("Disposing CacheManagerFactory");

    javax.cache.CacheManager manager = retrieveCacheManager();

    // Setting up metrics for the various caches
    for(String cacheName : manager.getCacheNames()) {
      ObjectName objectName = getCacheObjectName(cacheName);
      if(objectName != null) {
        platformMBeanServer.unregisterMBean(objectName);
      }
    }
  }

  private ObjectName getCacheObjectName(String cacheName) {
    String objectName = "javax.cache:type=CacheStatistics,CacheManager=*,Cache=" + cacheName;
    try {
      Set<ObjectName> queryResult = platformMBeanServer.queryNames(ObjectName.getInstance(objectName), null);
      return queryResult.iterator().next();
    } catch (MalformedObjectNameException e) {
      log.warn("Malformed MBean name '{}'", objectName, cacheName);
    }
    return null;
  }

```

**Comment by henri-tremblay** [comment]
Interesting. Which version of Ehcache (minor version) are you using?

**Comment by cosenmarco** [comment]
@henri-tremblay see my first post:
Tomcat 8.0.35
Ehcache 3.3.1
Spring 4.3.10

**Comment by henri-tremblay** [comment]
I forgot one thing: Please can you ask these question to the mailing list first next time? Thanks.

When closing the `CacheManager`, it should unregister all MBeans. And the `CacheManager` should be closed when the application context is closed.

And normally, Spring calls `close` on any bean that is `Closeable`.

So, `Ehcache107CacheManager.close()` is never called in your case?

**Comment by cosenmarco** [comment]
> I forgot one thing: Please can you ask these question to the mailing list first next time? Thanks.

Sure thing. Thanks for answering, actually. I think it would be beneficial to specify in the README to discuss in the mailing list before opening issues here.

Apparently `Ehcache107CacheManager.close()` is not getting called. I do believe this is the case because the Bean I return is `org.springframework.cache.jcache.JCacheCacheManager` which is not a `Closeable`. I think the right strategy in this case is to call `close()` manually in the `destroy()` method, then.

**Comment by henri-tremblay** [comment]
You are right. It is only in contributing. I've did #2104 to add it.

I'm a bit surprised but you are right. The trick they do to solve that is to register the 107 `CacheManager` as a bean. That way, it gets closed correctly.

```
@Bean
public JCacheCacheManager cacheManager(CacheManager jCacheCacheManager) {
    return new JCacheCacheManager(jCacheCacheManager);
}

@Bean
public javax.cache.CacheManager jCacheCacheManager() throws IOException {
    CachingProvider provider = Caching.getCachingProvider();
    Resource cacheConfig = context.getResource("classpath:ehcache.xml");
    javax.cache.CacheManager manager = provider.getCacheManager(cacheConfig.getURI(),
      CacheManagerFactory.class.getClassLoader());

    return manager;
}
```
