### ISSUE TITLE
Support cache expiration at a particular time

### ISSUE THREAD

**Issue by benmccann** [ehcache/ehcache3#2110]
Right now I can only expire a cache after a certain number of seconds/minutes/hours/etc.

What I'd like to be able to do is say expire the cache at 1pm every day.

E.g. you might have a batch job that runs every day with an SLA of finishing at 3am. In my case, it's because I want to expire the cache after the stock market has closed for the day to get the latest market data.

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***

You can absolutely do that, since you can have custom expiration strategies. Have a look at the documentation on [expiry](http://www.ehcache.org/documentation/3.4/expiry.html).

**Comment by henri-tremblay** [comment]
If did an answer on [StackOverflow](https://stackoverflow.com/questions/44588373/does-ehcache-cache-have-any-option-of-auto-refreshing-without-any-scheduler-job) on a highly similar question. I'll put a summary here for the record.

Basically, you need to calculate the difference between the wanted expiration time and now. And set an expiry accordingly.

```java
    Expiry expiry = new Expiry() {
      @Override
      public Duration getExpiryForCreation(Object key, Object value) {
        long msUntilMidnight = LocalTime.now().until(LocalTime.of(13, 0), ChronoUnit.MILLIS);
        return Duration.of(msUntilMidnight, TimeUnit.MILLISECONDS);
      }

      @Override
      public Duration getExpiryForAccess(Object key, ValueSupplier value) {
        return null;
      }

      @Override
      public Duration getExpiryForUpdate(Object key, ValueSupplier oldValue, Object newValue) {
        return null;
      }
    };
```

**Comment by benmccann** [comment]
Thank you very much for the pointers
