### ISSUE TITLE
Avoid info ehcache logs

### ISSUE THREAD

**Issue by ShaiGivati464** [ehcache/ehcache3#2131]
Every time I save or load I get the following logs: 
.......created in EhcacheManager. 
.......removed from EhcacheManager.

and also: 
The index for data file ehcache-disk-store.data is more recent than the data file itself by 5ms : this is harmless. 

What do these logs mean? How can I avoid logging them?

**Comment by anthonydahanne** [comment]
hello,
please use the mailing list for questions, next time, it's available at : https://groups.google.com/forum/#!categories/ehcache-users/ehcache-core 

Ehcache3 relies on slf4j; with any slf4j implementations, it should be easy to silence such logs.
With logback : 

      <logger name="org.ehcache" level="WARN"/>

should silence such logs. Of course you could be more fine grained, and only select a given package : 

     <logger name="org.ehcache.core" level="WARN"/>

HTH, if you have any other questions, please use the mailing list - closing the issue
