### ISSUE TITLE
Investigate test failure: BasicClusteredCacheOpsReplicationMultiThreadedTest.testClear[consistency=STRONG]

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#2133]
This test has been failing a lot lately. Investigation is needed to see if it is simply a timeout / slow machine issue or if this is the manifestation of an underlying problem.

See https://ehcache.ci.cloudbees.com/job/ehcache3/1320/

**Comment by ljacomet** [comment]
I ended up disabling the test for now.

As stated in the `@Ignore`:
> This is currently unstable as if the clear does not complete before the failover, there is no future operation that will trigger the code in `ClusterTierActiveEntity.invokeServerStoreOperation` dealing with in-flight invalidation reconstructed from reconnect data

**Comment by chrisdennis** [comment]
This *should* be fixed (was fixed a while back) when the reconnect logic was revamped. We now correctly trigger the correct invalidations after all clients have reconnected but before reconnected clients are allowed to interact.
