### ISSUE TITLE
How to specify ehcache3 eviction strategy when cache is full ?

### ISSUE THREAD

**Issue by blling** [ehcache/ehcache3#2134]
How to specify ehcache3 eviction strategy when cache is full ?
`usingEvictionPrioritizer` is gone?

**Comment by blling** [comment]
Anyone knows?

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***

The eviction strategy is not configurable in Ehcache 3 so far.

**Comment by blling** [comment]
If not config, when cache is full what will happen? :)

**Comment by blling** [comment]
@ljacomet What is the default eviction strategy?

**Comment by ljacomet** [comment]
When the cache is full, it will evict. The exact strategy depends on the configured tier(s). One of the main reason this is not configurable is that we did not find a way to expose this and make sure it remains performant. And between heap and off heap tiers, remaining performant has real implications on what's available. If you want to know more,  check [this code](https://github.com/ehcache/ehcache3/blob/65a94df39f54442290a9cb39d381df6ee5886e3e/impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java#L134) for heap and [this code](https://github.com/Terracotta-OSS/offheap-store/blob/81037c9d2a0f14763e6241af29bf454ddac01cad/src/main/java/org/terracotta/offheapstore/AbstractOffHeapClockCache.java#L128) for offheap.

**Comment by DMMN1992** [comment]
Sorry to intrude but are you saying using the Expiry interface will not work on Ehcache 3?

The website describes using an Expiry interface and also Ehcache implements JSR 107 which includes an ExpirePolicy interface.

**Comment by ljacomet** [comment]
@dmmn1992 Expiry and eviction are two different concepts.

**Comment by blling** [comment]
Tks
