### ISSUE TITLE
The default evict strategy is a random evict strategy?

### ISSUE THREAD

**Issue by blling** [ehcache/ehcache3#2135]
[My first question is here #2134.]

But i have some problems after an experence.
I just use heap as store resource, but the evict strategy is not LRU as the code design [here](https://github.com/ehcache/ehcache3/blob/65a94df39f54442290a9cb39d381df6ee5886e3e/impl/src/main/java/org/ehcache/impl/internal/store/heap/OnHeapStore.java#L134), i test it, as a result it is a random evict strategy, i do not know if the code [here](https://github.com/ehcache/ehcache3/blob/65a94df39f54442290a9cb39d381df6ee5886e3e/impl/src/main/java/org/ehcache/impl/internal/concurrent/ConcurrentHashMap.java#L6376) is the reason?  Is it a bug?

Here is my ehcache config
```xml
    <cache alias="ehcache-data-httpinvokerconfig" uses-template="default-template">
        <value-type>com.xxx.xxxx.data.cached.HttpInvokerConfigCached</value-type>
    </cache>
    <cache-template name="default-template" >
        <key-type>java.lang.String</key-type>
        <expiry>
            <none/>
        </expiry>
        <resources>
            <heap unit="entries">20</heap>
        </resources>
    </cache-template>
```

Here is my test code, i let num 1 not accessed and and put one more entry, but the evict entry is not first. it is a random one
```java
    @Test
    public void will_discard_first_if_more_than_20() {
        EhcahceProvider ehcahceProvider = new EhcahceProvider();
        EhcacheHolder ehcacheHolder = new EhcacheHolder(ehcahceProvider.get());
        HttpInvokerConfigCache httpInvokerConfigCache = new HttpInvokerConfigEhcache(ehcacheHolder);

        HttpInvokerConfigCached httpInvokerConfigCached;
        for (int i=0; i < 20; i++) {
            httpInvokerConfigCached = new HttpInvokerConfigCached("cache" + i, "http://xxx.x.x", 1, 2, 3,4);
            httpInvokerConfigCache.putCache("cache" + i, httpInvokerConfigCached);
        }

        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        for (int ii = 0; ii < 20; ii++) {
            if(ii == 1) {
                continue;
            }
            httpInvokerConfigCached  = httpInvokerConfigCache.getCache("cache" + ii);
        }

        httpInvokerConfigCached = new HttpInvokerConfigCached("cache100", "http://xxx.x.x", 1, 2, 3,4);
        httpInvokerConfigCache.putCache("cache100", httpInvokerConfigCached);

        for (int iii = 0; iii < 20; iii++) {
            httpInvokerConfigCached = httpInvokerConfigCache.getCache("cache" + iii);
            if(httpInvokerConfigCached == null) {
                System.out.println("cachenull:" + iii);
            }
        }
    }
```
An error one output is here, not my expect `cachenull:1`
```text
   cachenull:7
```
How could it happend ?

**Comment by lorban** [comment]
As stated in the other issue you raised, a bug tracker is not the right place to ask questions. Please use the [ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) google group instead.

**Comment by lorban** [comment]
The eviction algorithm is not random (it actually is a pseudo-LRU one for the heap tier), despite the fact that it may appear to be -especially on small data sets-  but should be considered so. 
Per definition of a cache, its contents can disappear at any time, for any reason in any order.
