### ISSUE TITLE
Move Ehcache 3.5 to be Java 8 only

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#2138]
See [announcement on mailing list](https://groups.google.com/forum/#!topic/ehcache-dev/TQrpDVfnZXs)

**Comment by ljacomet** [comment]
This is flagged as `API` but the goal is to have 0 API impacts in this context. However, removing all the functional types introduced to copy Java 8 ones will have impact at the `SPI` level.

**Comment by henri-tremblay** [comment]
Can this be considered fixed now?

**Comment by henri-tremblay** [comment]
This is now done.
