### ISSUE TITLE
API changes report for Ehcache

### ISSUE THREAD

**Issue by lvc** [ehcache/ehcache3#2146]
Hi,

I'd like to share my results on API changes analysis for the library: https://abi-laboratory.pro/java/tracker/timeline/ehcache3/

The report is generated by the https://github.com/lvc/japi-compliance-checker tool for jars found at http://central.maven.org/maven2/org/ehcache/ehcache/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Report for Ehcache 2.x: https://abi-laboratory.pro/java/tracker/timeline/ehcache/

Thank you.

![ehcache3-2](https://user-images.githubusercontent.com/1517837/31161701-8479b8f8-a8e1-11e7-8bcb-2aeadeafec82.png)
![ehcache3-1](https://user-images.githubusercontent.com/1517837/31161702-847d34ba-a8e1-11e7-8f70-cfc9de82b87a.png)

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***

That's great, thanks for pointing us at it.

However, I would be interested to know if there is a possibility to limit the scanning to specific packages?
I browsed a number of the versions that have the lowest scores and all modifications are in what we define as internal packages.
While we will only be able to enforce that in Java 9, what would be really interesting is to validate that the API only grows and that the SPI only changes between minors.
Is that an option?

**Comment by lvc** [comment]
Hi,

It's possible to remove particular packages from the analysis. Should it check packages listed at http://www.ehcache.org/apidocs/3.4.0/index.html only?

    org.ehcache
    org.ehcache.config
    org.ehcache.config.builders
    org.ehcache.config.units
    org.ehcache.event
    org.ehcache.expiry
    org.ehcache.spi.copy
    org.ehcache.spi.loaderwriter
    org.ehcache.spi.persistence
    org.ehcache.spi.serialization
    org.ehcache.spi.service

Thank you.

**Comment by henri-tremblay** [comment]
This is indeed the external API. Everything else is internal stuff that
shouldn't be used directly.

**Comment by lvc** [comment]
Fixed report according to docs: https://abi-laboratory.pro/java/tracker/timeline/ehcache3/

Thank you.

![ehcache3-4](https://user-images.githubusercontent.com/1517837/31598589-2363a004-b257-11e7-8f60-e2b07e0d6834.png)

![ehcache3-3](https://user-images.githubusercontent.com/1517837/31598590-237f3666-b257-11e7-812a-1ab70ef01119.png)

**Comment by henri-tremblay** [comment]
Thanks for the report. Closing this since all changes here are expected
