### ISSUE TITLE
Ehcache interacts with the Expiry policy to supress firing events for values that immediately expire

### ISSUE THREAD

**Issue by timeck** [ehcache/ehcache3#215]
It was expected that interaction with cache expiration was a concern for Store implementations. 

To satisfy the expectations of jsr107 I needed to add some expiry checks in the cache itself. Specifically to cover the case of new cache values that are immediately expired (see `org.ehcache.Ehcache.newValueAlreadyExpired(K, V, V)`). When new values are already expired there should be no cache events fired. Since cache events are implemented in the Cache we need to deal with expiry.

**Comment by ljacomet** [comment]
Goal of this task is to define if we want to do some changes on this or leave code as is.

**Comment by ljacomet** [comment]
Not much can be done right now.

As the cache currently holds the responsibility of events and JSR-107 mandates that no events are fired for immediately expired values, we have no choice but to in advance look at the expiry before letting the store handle that.

However, in the context of #165, there have been discussion about pushing down the complete eventing system down to the store. If that becomes true, then we should indeed get rid of that code as everything could be handled at the store level.

I will thus close this issue and reference it from a comment on #165 to make sure it is taken into account if we go down that path.
