### ISSUE TITLE
No user control over unmarshalling

### ISSUE THREAD

**Issue by rahul-mittal** [ehcache/ehcache3#2175]
No user control over what is getting deserialized at client side when it receives StateRepository message response. Similarly, at server side only the objects of classes that represent the primitives or the ValueWrapper should get deserialized as part of StateRepository message.

**Comment by chrisdennis** [comment]
@AbfrmBlr @rahul-mittal Hey - only I'm allowed to 'skunk-works' things... could you guys add a description for this?

**Comment by rahul-mittal** [comment]
https://github.com/ehcache/ehcache3/pull/2191 merged to fix this issue
