### ISSUE TITLE
Ehcache at Entity level and identifier in Query cache not getting synced

### ISSUE THREAD

**Issue by manjush** [ehcache/ehcache3#2186]
Two applications use the same database, For example, A & B.

If A application delete the employee Id 8, but at the same time application B may be using this cached id of 8.

When query cache tries to get the Entity object based on the identifier, The Entity object will be null, but identifier will be present leads to an awkward situation.

I was trying to programmatically check whether that Entity id exists in Cache

```
Ehcache ehcache = cacheManager.getCache("com.model.Employee");
List<CacheKey> list = ehcache.getKeys();
boolean exists = list.stream().map(cacheKey -> (Long)cacheKey.getKey()).anyMatch(key-> key.equals(employeeId));
```
Is it possible to Dynamically set the query cache if Entity id exists , then  use cache , if it doesn't exist call from Database?

My Query cache

```
@QueryHints({@QueryHint(name = "org.hibernate.cacheable", value = "true"), @QueryHint(name="org.hibernate.cacheRegion", value="employees")})
List<Employee> findAll();
```
Cache Configuration
```
<cache name="com.model.Employee"
            maxEntriesLocalHeap="100" overflowToDisk="false" statistics="true" />

<cache name="employees" maxEntriesLocalHeap="1000" overflowToDisk="false" timeToLiveSeconds="60" statistics="true" /> 
```
Any best approach when two application uses separate CacheManager and use same database

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***

First of all, this is a duplicate from a post on the ehcache-users, why the repeat?
Also your question, while not mentioning any version, clearly uses Ehcache 2.x APIs.

Thus closing as unrelated and keep the conversation on the mailing list.

Regards.
Louis
