### ISSUE TITLE
how to monitor ehcache 3.3.1

### ISSUE THREAD

**Issue by sdmjhca** [ehcache/ehcache3#2190]
hi dear guys,
My current project uses ehcache to store a large number of key-values and I want to monitor ehcache's memory(off-heap) usage and how should I do it

**Comment by henri-tremblay** [comment]
Please ask such question on the [mailing list](https://groups.google.com/forum/#!forum/ehcache-users).

There are currently no official API for statistics. However, you can get a lot of them by doing something like:

```
StatisticsService service = new DefaultStatisticsService();
CacheManagerBuilder<PersistentCacheManager> clusteredCacheManagerBuilder =
            newCacheManagerBuilder()
                    .using(statisticsService)
```
