### ISSUE TITLE
Implement reconciliation client-server after failure

### ISSUE THREAD

**Issue by henri-tremblay** [ehcache/ehcache3#2203]
When a client manage to reconnect to a server, it should reconcile with it.

It sends a "what did I miss?" message and will receive a list of entries to invalidate on the caching tier.

Pending updates on the client are sent to the server and applied if not obsolete and will be processed if not obsolete.

**Comment by AbfrmBlr** [comment]
When clients get a disconnect event, we already invalidate everything on the caching tier and the connection is closed, which means all the pending updates would be lost.
Infact in some cases, the requests waiting for responses might end up having a successful change in state on the server, but client never managed to see the response. 
In those cases, client will get a StoreAccessException, but the operation might have been successful.
Connecting back actually means a fresh client server for the server. where client has not state and is starting from scratch(as good as that.)

**Comment by henri-tremblay** [comment]
I don't think this should be closed. The idea was really to performa reconciliation. That it can't be done right now is another problem.
