### ISSUE TITLE
Null check in org.ehcache.events.CacheEventNotificationServiceImpl.releaseAllListeners(CacheEventListenerFactory)

### ISSUE THREAD

**Issue by timeck** [ehcache/ehcache3#221]
There is a null check to make sure the factory is not null. Is this actually expected or is there some error checking or other code missing someplace higher in the stack? Without this null check 107 caches will fail to close

```
  @Override
  public void releaseAllListeners(CacheEventListenerFactory factory) {
    for (EventListenerWrapper wrapper: registeredListeners) {
      
      // XXX: should this null check be required (or is it an error state)? 
      if (factory != null) {
        factory.releaseEventListener(wrapper.listener);
      }
      registeredListeners.remove(wrapper);
    }
  }
```

**Comment by alexsnaps** [comment]
This null check is indeed fishy... I actually find the whole method fishy (which is further indicated by its comment). Anyways, fundamentally there is no guarantee that a listener was even created by this factory. I think that's what needs to be addressed.

I see a couple of ways to go about this. But I'd like to chat with @lorban about why this is currently the way it is, and how he envisioned fixing this method given his comment above.

**Comment by lorban** [comment]
The comment is Tim's, and he's the one who added the null check too. The method has originally been written by Vitaliy, I merely added the @Override annotation so I can't say much about the original intent.
