### ISSUE TITLE
A *very* large put can bring down the active and/or passive server.

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#2214]
If the OffHeapServerStore legitimately throws an OversizeMappingException (because the value presented is too large to fit in the offheap resourcre configured) then the propagating OversizeMappingException will cause the server to terminate.  Although this scenario is highly unlikely in a typical configuration we should prevent propagation of this exception and instead act as if the value was immediately evicted.

**Comment by rkavanap** [comment]
@chrisdennis , I am seeing a slightly different behavior for this test case, where the server does not crash (atleast the active) and put fails with oversized mapping exception and everything in cache getting evicted. so the client is able to do a get, only that it will not find anything in the cache as everything gets evicted (so put of a very large object that does not fit in cache acts almost like a cache.clear). Am I doing something wrong?

**Comment by rkavanap** [comment]
I think the ClusterTierActiveEntity consumes this exception, causing the exception NOT to be propagated further.
