### ISSUE TITLE
Disabled JSR107 TCK tests

### ISSUE THREAD

**Issue by timeck** [ehcache/ehcache3#222]
107/src/tck/resources/ExcludeList currently lists two tests to exclude based on issues filed against the TCK. 

At some point those TCK issues will be resolved. At that time we should stop excluding these tests

**Comment by sunnydas** [comment]
The tests still cause failures even though https://github.com/jsr107/jsr107tck/issues/61 seem to have been closed. I guess we will have to move this back to prioritized bucket until these tests are corrected. Please let me know if this understanding is correct.

**Comment by ljacomet** [comment]
As discussed in chat, we need to make sure the 1.0.1 tck indeed contains the change for issue jsr107/jsr107tck#61
If that's the case, then it could be that we have an issue on our side or another bug report may need to be filed.

**Comment by sunnydas** [comment]
org.jsr107.tck.management.CacheMBStatisticsBeanTest.testPutIfAbsent() is marked for 1.1.0

**Comment by sunnydas** [comment]
reference ; https://github.com/jsr107/jsr107tck/issues/63

**Comment by sunnydas** [comment]
For :  https://github.com/jsr107/jsr107tck/issues/61

The local does not seem to have changes as per : https://github.com/jsr107/jsr107tck/commit/f69ffd34c3202be76ec05d76cb49ad4f340d1f4d?diff=unified

The local version of CachingProviderClassLoaderTest seems to have :   Assert.assertSame(manager, provider.getCacheManager(provider.getDefaultURI(), classLoader)); , which does not reflect the changes ate the said line (#84), which is still causing the tests to fail. 

Please let me know if I am missing something here. 

For reference the error is:
----------------------------------------------------------------------------------------------------------------
java.lang.AssertionError: expected same:<Eh107CacheManager[urn:X-ehcache:jsr107-default-config]> was not:<Eh107CacheManager[urn:X-ehcache:jsr107-default-config]>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotSame(Assert.java:737)
	at org.junit.Assert.assertSame(Assert.java:680)
	at org.junit.Assert.assertSame(Assert.java:691)
	at org.jsr107.tck.spi.CachingProviderClassLoaderTest.getCacheManagerSingleton(CachingProviderClassLoaderTest.java:84)
-------------------------------------------------------------------------------------------------------

**Comment by sunnydas** [comment]
For reference the exception is:

java.lang.AssertionError:

<Eh107CacheManager[urn:X-ehcache:jsr107-default-config]> was not:<Eh107CacheManager[urn:X-ehcache:jsr107-default-config]>

at org.jsr107.tck.spi.CachingProviderClassLoaderTest.getCacheManagerSingleton(CachingProviderClassLoaderTest.java:84)

**Comment by chrisdennis** [comment]
I've created PR jsr107/jsr107tck#77 to try and get this fixed in the TCK.

**Comment by ljacomet** [comment]
I am closing this issue - there is no more work to be done until the next TCK release.
