### ISSUE TITLE
Could not get resource 'http://repo.terracotta.org/...'

### ISSUE THREAD

**Issue by adityai** [ehcache/ehcache3#2233]
When 'gradlew properties' is executed, I get the following error. How do we get around it? 

* Where:
Build file 'C:\work\workspaces\gitws\ehcache3\clustered\clustered-dist\build.gradle' line: 77

* What went wrong:
A problem occurred evaluating project ':clustered:clustered-dist'.
> Could not resolve all files for configuration ':clustered:clustered-dist:kit'.
   > Could not resolve org.terracotta.internal:terracotta-kit:5.4.0-pre14.
     Required by:
         project :clustered:clustered-dist
      > Could not resolve org.terracotta.internal:terracotta-kit:5.4.0-pre14.
         > Could not get resource 'http://repo.terracotta.org/maven2/org/terracotta/internal/terracotta-kit/5.4.0-pre14/terracotta-kit-5.4.0-pre14.pom'.
            > Could not GET 'http://repo.terracotta.org/maven2/org/terracotta/internal/terracotta-kit/5.4.0-pre14/terracotta-kit-5.4.0-pre14.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

**Comment by henri-tremblay** [comment]
We prefer user questions to be asked on the mailing list first and then create turned into an issue if needed.

This URL should be available. You might be behind a firewall requiring authentication.
