### ISSUE TITLE
read data from disk

### ISSUE THREAD

**Issue by Hansonnnn** [ehcache/ehcache3#2270]
How I can read  Serializable data from disk after sever stop? I can't find about it at you office.please help me ! wish your best regards!

**Comment by henri-tremblay** [comment]
We request to ask such question on the Ehcache mailing. This is not an issue, it is a support question. You just need to tell the disk to be persistent. See http://www.ehcache.org/documentation/3.4/tiering.html#disk-tier.

However, in case of the server crash, you will still lose the data. Keeping it is an enterprise feature. I will now close this issue.
