### ISSUE TITLE
ehcache sporadically removes item even when it is just updated

### ISSUE THREAD

**Issue by shengc** [ehcache/ehcache3#2275]
This behavior has been haunting us for really quite a while. Initially, I thought it was because the off-heap-store implementation does not have a strict strategy in place to enforce removal of the least recent updated item. https://github.com/ehcache/ehcache3/issues/1331 describes there was a bug in on-heap-store implementation that resulted in the most recent updated item got evicted first, but has been fixed starting 3.1.2. I updated ehcache to 3.1.2, and switched to on-heap-store. However the issue still exists. Following is a snippet of log from our process listening to the cache events. Ehcache was doing something funky by removing the item that's just been updated from its underlying store. 

    2018-02-06 11:04:05,295 DEBUG - case RecurringInqReqWF-hyzh7zd3cm8nqstu4hr8nppnk5 has been updated in cache
    2018-02-06 11:04:05,302 DEBUG - case RecurringInqReqWF-hyzh7zd3cm8nqstu4hr8nppnk5 has been updated in cache
    2018-02-06 11:04:05,311 DEBUG - case RecurringInqReqWF-hyzh7zd3cm8nqstu4hr8nppnk5 has been removed from cache

Even when the cache space is filled up, my understanding is ehcache will just start to remove item that is least recent updated. Is that right ?

**Comment by chrisdennis** [comment]
Ehcache will remove items when it runs out of space.  It will make an effort to target items that are of low value.  It makes no guarantee that the item it actually removes if the minimum by any utility metric.

I think it would be more productive if any further discussion on this issue occured on the [ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) mailing list.

**Comment by shengc** [comment]
Apologize I had to put it here, as the firm proxy largely blocks me from accessing any forum or email service. That said, we desperately rely on ehcache to not remove the item been recently updated,  is there any reasonable solution/workaround to prevent that from happening ?
