### ISSUE TITLE
Migrate Gradle compile dependency scope to api or implementation

### ISSUE THREAD

**Issue by henri-tremblay** [ehcache/ehcache3#2286]
The compile scope is now deprecated. Gradle has added two more precise scopes: api and implementation.

We should migrate our project to use them. It should speed up the build a bit by reducing the amount of transitive dependencies.

**Comment by chrisdennis** [comment]
Blocked by release work for now.  This is a good candidate for post EOC work though.

**Comment by chrisdennis** [comment]
Completed in 0d86134e6567a6f5516a11686cfd25f0b4a19f29
