### ISSUE TITLE
Issue with PoolSettingsProvider and PoolStatisticsProvider after failover

### ISSUE THREAD

**Issue by anthonydahanne** [ehcache/ehcache3#2289]
After a fail over, there is no longer pool server side stats nor capabilities.

**Comment by anthonydahanne** [comment]
to provide more context : we found a regression in ehcache3, where ehcache server stats do not show up after a fail over.
In tc platform, we already have [a test for stats after failover](https://github.com/Terracotta-OSS/terracotta-platform/blob/master/management/testing/integration-tests/src/test/java/org/terracotta/management/integration/tests/FailoverIT.java), this is why I believe this issue is particular to ehcache 3

**Comment by mathieucarbou** [comment]
I'll wait for @AbfrmBlr to complete our work for https://github.com/ehcache/ehcache3/pull/2293 first.
He has planned on changing some IT tests so I will take his updates before adding yours and see what's wrong.

**Comment by mathieucarbou** [comment]
@anthonydahanne @myronkscott : I think there's a bug in voltron. Some addNode() calls that we are doing are discarded by platform and never received from the `IStripeMonitoring` interface
