### ISSUE TITLE
Ehcache causing ERROR Unable to set localhost. This prevents creation of a GUID. when running on AWS lambda

### ISSUE THREAD

**Issue by manoj4068** [ehcache/ehcache3#2309]
0down votefavorite | ERROR Unable to set localhost. This prevents creation of a GUID. Cause was: ip-10-22-209-10: ip-10-22-209-10: Name or service not known (net.sf.ehcache.Cache:224) java.net.UnknownHostException: ip-10-22-209-10: ip-10-22-209-10: Name or service not known at java.net.InetAddress.getLocalHost(InetAddress.java:1505) at net.sf.ehcache.Cache.(Cache.java:222) at net.sf.ehcache.config.ConfigurationHelper.createCache(ConfigurationHelper.java:305) at net.sf.ehcache.config.ConfigurationHelper.createCaches(ConfigurationHelper.java:238) at net.sf.ehcache.CacheManager.addConfiguredCaches(CacheManager.java:816) at net.sf.ehcache.CacheManager.doInit(CacheManager.java:498) at net.sf.ehcache.CacheManager.init(CacheManager.java:394) at net.sf.ehcache.CacheManager.(CacheManager.java:269) at net.sf.ehcache.CacheManager.newInstance(CacheManager.java:1103) at net.sf.ehcache.CacheManager.newInstance(CacheManager.java:879) at net.sf.ehcache.CacheManager.create(CacheManager.java:860) at net.sf.ehcache.CacheManager.getInstance(CacheManager.java:894) at com.capitalone.stsedh.datawise.engine.lite.core.service.RuleExecutionServiceImpl.(RuleExecutionServiceImpl.java:50)Below is the error when I am using Ehcache to cache one of the variable in Java code in AWS lambda. Does it have a better solution.Does EhCache run on serverless Aws Lambda.
-- | --

May I know If EhCache has a better solution to handle this error when working with serverless architecture

**Comment by chrisdennis** [comment]
This isn't an Ehcache 3 issue. You'll need to file this here: https://jira.terracotta.org/jira/browse/EHC
