### ISSUE TITLE
Suggestion : continuous calls of StringBuilder.append 

### ISSUE THREAD

**Issue by o0lwj0o** [ehcache/ehcache3#2327]
Hi,
&nbsp;&nbsp;&nbsp;&nbsp;I have found some continuous calls about `StringBuilder.append(..)` in some files. For example, there are several continuous calls from line 241 to 245 in the file  https://github.com/ehcache/ehcache3/blob/master/clustered/client/src/main/java/org/ehcache/clustered/client/config/ClusteringServiceConfiguration.java. 
```Java
private String readablePoolsString() {
    StringBuilder pools = new StringBuilder("resourcePools:\n");
    serverConfiguration.getResourcePools().forEach((key, value) -> {
      pools.append("        ");
      pools.append(key);
      pools.append(": ");
      pools.append(value);
      pools.append("\n");
    });
    return pools.toString();
}
```
&nbsp;&nbsp;&nbsp;&nbsp;If it was achieved like `StringBuilder.append(..).append(..)append(..)`, it will promote its performance.

PS:
https://github.com/ehcache/ehcache3/blob/master/clustered/client/src/main/java/org/ehcache/clustered/client/internal/config/DedicatedClusteredResourcePoolImpl.java | 78-84

**Comment by henri-tremblay** [comment]
What makes you think it will be faster? `pools.append` returns `this` so both syntaxes should be identical. From a quick benchmark it seems indeed a tiny bit faster but nothing outside the error margin.

**Comment by chrisdennis** [comment]
As @henri-tremblay indicates, we're not convinced this will have any effect on performance, and this isn't performance sensitive code in the first place... voting for the status quo.
