### ISSUE TITLE
Add expired entry test cases to Ehcache unit tests

### ISSUE THREAD

**Issue by cljohnso** [ehcache/ehcache3#233]
Ehcache code for `put`, `putAll`, `putIfAbsent`, `replace(key, value)`, and `replace(key, oldValue, newValue)` is changed to add handling for "pre-expired" entries.  The existing unit tests do not cover this logic.  Tests for expired entry handling need to be added.

**Comment by ljacomet** [comment]
Merged PR #493. It would be good to document, like in a table, what are the expected events from the different operations on a cache, including with the special case of immediately expired values.
