### ISSUE TITLE
Why pay deserialization penalty on every get when using off heap?

### ISSUE THREAD

**Issue by ucjonathan** [ehcache/ehcache3#2351]
I've noticed (and confirmed with the documentation) that when you use an off heap store that everything gets serialized for storage and therefore has to be deserialized on every single get option.  It would seem like the best performance would come from the objects on the heap not requiring deserialization each access and then performing the serialization/deserialization on transition between on heap and off heap of data.  The on heap being the hottest data set and therefore not triggering any serialization operations upon access.  It also seems like having to deserialize something every time it's touched just because you're using off heap is generating a whole lot more memory garbage to ultimately be collected.  Am I missing something?

**Comment by chrisdennis** [comment]
No... but thats why you normally configure a heap tier/resource alongside the offheap tier/resource.  Are you proposing some change to the way the `TieredStore` works?

**Comment by ucjonathan** [comment]
Thanks for the quick reply.  I created a single cache that had 100 entries on heap and 100MB off heap.  I also was using a custom Kryo serializer.  We put some print statements into the serializer and notices it was using that for every single put/get operation as we tested pushing in several hundred entries to watch the behavior as the on heap reached capacity.  I was surprised to see it interacting with the serializer for all put/get operations.  Do you recommend creating two separate caches and manually having the evict from one causing a promotion to the other and vice versa?

**Comment by chrisdennis** [comment]
What you're seeing is likely a symptom of two things in the way the `TieredStore` works:
 1. The caching (heap) tier holds a subset of the elements in the authoritative (offheap) tier, i.e. the authoritative tier stores everything.  This means the authoritative tier is always written to when you put.
2. The caching (heap) tier does not get populated on put, i.e. we don't assume that a newly arriving value is hotter than the existing caching tier contents. I can understand that in some usecases this might not be optimal.

**Comment by henri-tremblay** [comment]
A put will always store to the authoritative tier. So offheap. And won't store in the heap. Then, a get will get the value offheap and put it on heap.

The heap will then be useful is hot entries are accessed again. Which is a normal caching pattern.

BTW, since this is not a bug per se, you should have asked it on the mailing list first.

**Comment by ucjonathan** [comment]
Observing the behavior that you describe.  I agree this is not a bug, but I thought it was.
