### ISSUE TITLE
ClusteredStore's lack of support for iterator breaks JSR-107 removeAll()

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#2364]
Since the 107 `Cache.removeAll()` method contract requires us to call both listeners and cache writers with every key deleted we rely on iterating the authoritative tier and removing each key individually.  This isn't implemented in the clustered tier (arguably for good reasons), but this leaves a hole in our 107 implementation. This hole is exposed by Spring since an "evictAll" mapped method in a spring bean ends up calling this method. Independently we could consider looking in to having Spring call `clear()` instead of `removeAll()` but I suspect there are esoteric Spring configurations that might need the notifications that `removeAll()` gives. To fix this I think a two pronged approach would be a good plan:

1. I think for non-loader-writer cases where are no listeners (probably the common case) we can dynamically choose to call clear directly since no will notice that trees are making noises as they fall.
2. We'll need to implement some way of iterating the keys in the clustered store for cases where a writer or listener are present.

We can probably treat the more complex/fuller solution with a lower priorirty since I think step 1 will solve the issue for the bulk of our users.

**Comment by MantisMan13** [comment]
I'm hitting this issues and need to support both non clusters and clustered ehcache configurations. This works fine when using my local non clustered configuration, but when adding the cluster servers to the config, my eviction class now fails. Is there any known work around to accomplish an evictions of a named cache when using clustered?

I'm using:
<dependency>
		  <groupId>org.ehcache</groupId>
		  <artifactId>ehcache</artifactId>
		  <version>3.6.2</version>
		</dependency>
		<dependency>
			<groupId>javax.cache</groupId>
			<artifactId>cache-api</artifactId>
			<version>1.1.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.ehcache</groupId>
			<artifactId>ehcache-clustered</artifactId>
			<version>3.6.2</version>
		</dependency>

My code:

@Autowired
public org.springframework.cache.CacheManager manager;

public void clearEhCacheByName(String cacheName) throws Exception{

		if(manager != null) {
			try {
				Cache thisCache = manager.getCache(cacheName);
				thisCache.clear();
			}catch (Exception e){
				throw e;
			}
        }

	}

The error:

java.lang.UnsupportedOperationException: Implement me
	at org.ehcache.clustered.client.internal.store.ClusteredStore.iterator(ClusteredStore.java:415)
	at org.ehcache.impl.internal.store.tiering.TieredStore.iterator(TieredStore.java:215)
	at org.ehcache.core.EhcacheBase$Jsr107CacheBase.removeAll(EhcacheBase.java:705)
	at org.ehcache.jsr107.Eh107Cache.removeAll(Eh107Cache.java:303)
	at org.springframework.cache.jcache.JCacheCache.clear(JCacheCache.java:105)
	at com.trifecta.src.ezreg.services.EhCacheEvictionServiceImpl.clearEhCacheByName(EhCacheEvictionServiceImpl.java:60)

**Comment by MantisMan13** [comment]
This is probably obvious, but the spring Advice call to evict a cache also fails with the same type of error.  For example: 
	@CacheEvict(cacheNames="wizardPageCache", allEntries=true)
	void updateWizardPage(@Param("title") String title, @Param("id") Long id, @Param("wizardTypeId") Long wizardTypeId);

causes:

Nov 21, 2018 10:15:45 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [ezreg] in context with path [] threw exception [Request processing failed; nested exception is java.lang.UnsupportedOperationException: Implement me] with root cause
java.lang.UnsupportedOperationException: Implement me
	at org.ehcache.clustered.client.internal.store.ClusteredStore.iterator(ClusteredStore.java:415)
	at org.ehcache.impl.internal.store.tiering.TieredStore.iterator(TieredStore.java:215)
	at org.ehcache.core.EhcacheBase$Jsr107CacheBase.removeAll(EhcacheBase.java:705)
	at org.ehcache.jsr107.Eh107Cache.removeAll(Eh107Cache.java:303)
	at org.springframework.cache.jcache.JCacheCache.clear(JCacheCache.java:105)
	at org.springframework.cache.interceptor.AbstractCacheInvoker.doClear(AbstractCacheInvoker.java:111)
	at org.springframework.cache.interceptor.CacheAspectSupport.performCacheEvict(CacheAspectSupport.java:473)
	at org.springframework.cache.interceptor.CacheAspectSupport.processCacheEvicts(CacheAspectSupport.java:463)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:421)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy163.updateWizardPage(Unknown Source)
	at com.trifecta.src.ezreg.daos.WizardPageDaoImpl.updateWizardPage(WizardPageDaoImpl.java:231)

We are caching a great deal of administrative configuration and when those get changed, we must expire the cached values and applying @CacheEvict  on our update methods was very convenient.  I'm not sure how to accomplish this otherwise. Is there a way I can more directly issue an eviction to a named cache? I do see the API provides a destroyCache(String cacheName) method as part of the resource pool, but I don't think I can use that as the caches would be in use by non admin users who consume the configuration data or other admin users. It seems like there must be some way when clustered to expire all contents of a cache and have that propagate across all of the other persistence nodes.  Any advice would be greatly appreciated.

**Comment by henri-tremblay** [comment]
So. Doing a clear instead of a remove doesn't work at the JSR107 level. Because than statistics are all wrong and the TCK doesn't like that.

Implementing the iterator is the way to code.

@MantisMan13 There is an easy workaround for you. You can inherit `JCacheCache` and override `clear()` to do

```
	@Override
	public void clear() {
		this.cache.clear();
	}
```

The impacts are:
1- No iteration is done anymore. The clear will be really fast
2- No notification about the removal of each entry is done. If you are not using a listener, this has no impact
3- The statistics MBean won't count the cleared entries as removal
4- If you have a loader-writer, the entries won't be deleted from the system of record (which is what you want I think)

**Comment by henri-tremblay** [comment]
Yes. I know. You need to keep an attribute in your extending class.

```java
    public static class MyJCacheCache extends JCacheCache {

        private final Cache<Object, Object> cache;
        
        public MyJCacheCache(Cache<Object, Object> cache) {
            super(cache);
            this.cache = cache;
        }

        @Override
        public void clear() {
            cache.clear();
        }
    }
```

Implementing the iterator is in the backlog by not planned yet from as far as I know.

For the autowiring, I'm not sure to follow you. You need to extend `JCacheCacheManager` as well. To return your own `JCacheCache`.

@snicoll Do you know why `removeAll` is called instead of `clear` here? We guessed it's to get the events but I want to be sure.

**Comment by MantisMan13** [comment]
@henri-tremblay   Ok, I think I'm on the right track. I had started creating a class like this:

```
package com.trifecta.src.ezreg.beans;

import org.springframework.cache.jcache.JCacheCache;

import javax.cache.Cache;

public class EhcacheJCacheCache extends org.springframework.cache.jcache.JCacheCache {
	
	private javax.cache.Cache<Object, Object> cache = null;

	public EhcacheJCacheCache(Cache<Object, Object> jcache) {
		super(jcache);
		this.cache = jcache;
	}
	
	@Override
	public void clear() {
		this.cache.clear();
	}

}

```
And was then thinking I would need to somehow create a custom version of the cacheManager class that we are setting up in the applicationContext.xml like so:

```
<bean id="ehCacheManager" class="org.springframework.cache.jcache.JCacheCacheManager">
		<property name="cacheManager">
		<bean class="org.springframework.cache.jcache.JCacheManagerFactoryBean" p:cacheManagerUri="file:C:\Program Files\Apache Software Foundation\Tomcat 7.0\webapps\ROOT\WEB-INF\classes\ehcache3.xml" />
		</property>
	</bean>
```
So if my new ehCacheManager becomes a call that is a subclass of JCacheCacheManager and I can override the import of JCacheCache to import EhcacheJCacheCache instead... That might then give me the clear() method that I need.  As it stands with the ehcach.xml config I'm using to work with the spring cache annotation, 

@Autowired
public org.springframework.cache.CacheManager manager;

does not provide the cache.getNativeCache() and the cache list returns empty when I tried using the javax.cache.CacheManager.  I think I would need to define all of my caches with the service:jsr107 namespace for those to list there, but when I tried that, they would not load for spring @Cacheable call I have set up.

**Comment by henri-tremblay** [comment]
You are right, you can do 

```        
      @Override
        public void clear() {
            getNativeCache().clear();
        }
```

If I recall correctly, to get the list of caches with JSR-107, you need to define them in the Jsr107 section.

Like this:
```xml
  <service> 
    <jsr107:defaults default-template="tinyCache"> 
      <jsr107:cache name="foos" template="clientCache"/> 
      <jsr107:cache name="byRefCache" template="byRefTemplate"/>
      <jsr107:cache name="byValCache" template="byValueTemplate"/>
      <jsr107:cache name="weirdCache1" template="mixedTemplate1"/>
      <jsr107:cache name="weirdCache2" template="mixedTemplate2"/>
    </jsr107:defaults>
  </service>
```

See http://www.ehcache.org/documentation/3.6/107.html

**Comment by MantisMan13** [comment]
@henri-tremblay @snicoll  I do see now what I was doing wrong trying to config the jsr107 cache names. I was not nesting them within the default name space. However, it seems that my ide is telling me I can not have a <jsr107:defualts> and a  <tc:cluster> as piers under the same service block. This makes me wonder if jsr107 is simply not compatible with a distributed ehcache?

**Comment by henri-tremblay** [comment]
@MantisMan13  Please don't put snicoll in copy. He is not on the Ehcache team. He is leading the Spring-Cache team which is why I asked him the question.

Of course JSR107 is compatible. I used it in our [sample](https://github.com/ehcache/ehcache3-samples/tree/master/fullstack). However, I do a programmatic configuration, not an XML one.

However, you should have two service blocks.

```
  <service>
    <tc:cluster>
      <tc:connection url="${cluster-uri}/testJCache"/>
      <tc:server-side-config auto-create="true"/>
    </tc:cluster>
  </service>

  <service>
    <jsr107:defaults default-template="tinyCache">
      <jsr107:cache name="foos" template="clientCache"/>
      <jsr107:cache name="byRefCache" template="byRefTemplate"/>
      <jsr107:cache name="byValCache" template="byValueTemplate"/>
      <jsr107:cache name="weirdCache1" template="mixedTemplate1"/>
      <jsr107:cache name="weirdCache2" template="mixedTemplate2"/>
    </jsr107:defaults>
  </service>
```

**Comment by MantisMan13** [comment]
@henri-tremblay  Ok, thankyou... So I was wondering if 2 blocks would work together or end up defining multiple caches. In my current config I have top level <cache> tags defining the named ehcaches. Would those remain and is the following a correct configuration?
`<ehcache:config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ehcache='http://www.ehcache.org/v3'
    xmlns:jsr107='http://www.ehcache.org/v3/jsr107'
    xmlns:tc='http://www.ehcache.org/v3/clustered'
    xsi:schemaLocation="
        http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core-3.6.xsd
        http://www.ehcache.org/v3/jsr107 http://www.ehcache.org/schema/ehcache-107-ext-3.6.xsd
        http://www.ehcache.org/v3/clustered http://www.ehcache.org/schema/ehcache-clustered-ext-3.6.xsd">

    <ehcache:service>
        <tc:cluster>
            <tc:connection url="terracotta://localhost:9410/clustered"/>
            <tc:server-side-config auto-create="true">
                <tc:default-resource from="main"/>
            </tc:server-side-config>
        </tc:cluster>
    </ehcache:service>


    <ehcache:service>
        <jsr107:defaults enable-management="true" enable-statistics="true">
            <jsr107:cache name="timedCache" template="ehcacheDefaults"/>
            <jsr107:cache name="audioFileCache" template="ehcacheDefaults"/>

        </jsr107:defaults>
    </ehcache:service>


    
    <ehcache:cache-template name="ehcacheDefaults">
        <ehcache:key-type copier="org.ehcache.impl.copy.SerializingCopier">java.lang.Object</ehcache:key-type>
        <ehcache:value-type copier="org.ehcache.impl.copy.SerializingCopier">java.lang.Object</ehcache:value-type>
        <ehcache:expiry>
            <ehcache:ttl unit="seconds">20</ehcache:ttl>
        </ehcache:expiry>
        <ehcache:resources>
          <ehcache:heap unit="entries">100</ehcache:heap>
          <ehcache:offheap unit="MB">1</ehcache:offheap>
          <tc:clustered-dedicated unit="MB">5</tc:clustered-dedicated>
        </ehcache:resources>
    </ehcache:cache-template>

    <ehcache:cache alias="timedCache" uses-template="ehcacheDefaults"/>
    <ehcache:cache alias="audioFileCache" uses-template="ehcacheDefaults"/>

</ehcache:config>`

**Comment by MantisMan13** [comment]
@henri-tremblay  so I'm getting stuck again. Maybe I'm pulling this off of the wrong class, but from either sources as my CacheManager
//@Autowired
//public org.springframework.cache.CacheManager manager;

@Autowired
public org.springframework.cache.jcache.JCacheCacheManager manager;

the manager.getCache(cacheName).getNativeCache()  return a pain old Object class. I've tried to cast it to a Cache type but can not seem to get the right cast.

for example: org.ehcache.Cache thisCache = ((org.ehcache.Cache) manager.getCache(cacheName).getNativeCache());

gives me a stack error of: java.lang.ClassCastException: org.ehcache.jsr107.Eh107Cache cannot be cast to org.ehcache.Cache 

and I can not find a package that gives me assess to the org.ehcache.jsr107.Eh107Cache class.  I could use another hint here. Many Thanks.

**Comment by henri-tremblay** [comment]
I start to feel I am debugging your code... Yes. The cache is an Eh107Cache that implements `javax.cache.Cache`. The actual `org.ehcache.Cache` is underneath.

**Comment by MantisMan13** [comment]
@henri-tremblay That was the hint I needed. Much obliged!  I'm afraid I'm just not at all failure enough with these classes and how they all inter-operate.

**Comment by chrisdennis** [comment]
I'm going to close this as a duplicate of #2440. Although this is technically a subtly different issue, once #2440 is fixed this should be fine.
