### ISSUE TITLE
Ehcache.putAll can report successful CacheWriter write as failure via BulkCacheWriterException

### ISSUE THREAD

**Issue by cljohnso** [ehcache/ehcache3#238]
`Ehcache.putAll` can report a successful write through `CacheWriter.writeAll` as a failure if multiple entries are presented to `CacheWriter.writeAll` and `writeAll` throws an exception *other* than `BulkCacheWriterException` after the `CacheWriter` successfully records one or more entries.  Should a different exception indicating uncertain results be thrown instead of the somewhat inaccurate `BulkCacheWriterException` that is now thrown?

**Comment by cljohnso** [comment]
Discussion during [Ehcache weekly dev meeting - 8 January 2015] (https://plus.google.com/events/c7lgves3acscvgr9l075240rrmg) led to the conclusion that (at least) all declared failed keys should be invalidated in `Store` so, whether or not the write via `CacheWriter` was successful, the next `Ehcache.get` access to any value declared failed will yield the value from the store-of-record.

Converting this issue to a BUG.

**Comment by ljacomet** [comment]
Working on this, I realised a number of tests have an invalid state from the start. That is the CacheStore knows mappings that are unknown of the LoaderWriter.
I have updated all these cases to start with a valid state, that is all Cache Store mappings are known to the LoaderWriter - which may in turn contain more mappings.
