### ISSUE TITLE
Trying to cast a StoreCastException to RuntimeException, swallowing underlying error

### ISSUE THREAD

**Issue by bmhm** [ehcache/ehcache3#2434]
Hi everyone,

When using a get operation, I get this exception:

```
java.lang.ClassCastException: java.lang.NoClassDefFoundError incompatible with java.lang.RuntimeException
	at org.ehcache.impl.internal.store.tiering.TieredStore.get(TieredStore.java:98)
	at org.ehcache.core.Ehcache.doGet(Ehcache.java:82)
	at org.ehcache.core.EhcacheBase.get(EhcacheBase.java:127)
```

This is the problematic line:

https://github.com/ehcache/ehcache3/blob/master/impl/src/main/java/org/ehcache/impl/internal/store/tiering/TieredStore.java#L98

The method catches a StoreAccessException. If it is not a StorePassThroughException, it will be casted to RuntimeException and thrown.

Since StoreAccessException is not a RuntimeException, we see the error above. And this is why we cannot see why the StoreAccessException is being thrown in the first place.

Proposed solutions (implement one of them):
* Make StoreAccessException a RuntimeException, if possible (and feasible).
* Wrap into another exception
* Change the signature of the TieredStore.get() method to allow throwing StoreAccessException.

Thanks!

**Comment by anthonydahanne** [comment]
how did you end up with NoClassDefFoundError at this line ?
can you please share the code that threw ?

**Comment by henri-tremblay** [comment]
Thanks for the investigation. However, the problem is somewhere else. We are not throwing a `StoreAccessException`. We are throwing `StoreAccessException.getCause()` which will always be a `RuntimeException`... Or an Error which is your case. You had a `NoClassDefFoundError`.

Still, you are right, we should also check for error to prevent the bad cast.

**Comment by bmhm** [comment]
Wow that was fast! Thanks!

I cannot share the specific code, but I can tell you what led to it and how I "fixed" it.

I was using a cache with an interface (implementing Serializeable) as Key and an Interfacearray (`InterfaceType[].class`) as value. The only implementation was generated by [https://github.com/immutables/immutables](https://github.com/immutables/immutables).

I think the problem occured by accessing the cache without the implementation class used elsewhere in the code.

I added the `@Serial.Version(value = 1234L)` annotation and removed the interning annotation (which causes immutables to use interned strings). 

Thanks for looking into this. I know that the thrown cause was generated by my code, but since also errors could occur, I really think your new approach is more correct.
