### ISSUE TITLE
Adapt CacheLoader.loadAll contract

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#245]
After discussions triggered by the generics around `CacheLoader`s, there is a proposition to adapt the contract of `org.ehcache.spi.loader.CacheLoader#loadAll` as follows:
* The returned map is only used to find back values mapped to the passed in keys, that is the key/value pair that is going to be installed in the cache is the `key` as found in the iterator passed in as argument and the value returned by `loadAllResult.get(key)`

`Ehcache` code needs to be adapted to reflect this contract update.

**Comment by timeck** [comment]
Happy to wait for the PR, but I don't understand what is changing from the description here. Sounds like it what the methods already does and I don't see how the ```loadAll()``` signature would change or how it affects generics
