### ISSUE TITLE
Regression between 3.5.2 and master : Failed to find provider with satisfied dependency set for interface

### ISSUE THREAD

**Issue by anthonydahanne** [ehcache/ehcache3#2451]
I used to be able to run such code with 3.5.2 : 

```
DefaultManagementRegistryConfiguration managementRegistryConfiguration = new DefaultManagementRegistryConfiguration()
        .setCacheManagerAlias(CM_NAME);
DefaultManagementRegistryService managementRegistry = new DefaultManagementRegistryService(managementRegistryConfiguration);
    managementRegistryConfiguration.addTags("pif", "paf", "pouf");

    CacheManagerBuilder cacheManagerBuilder = CacheManagerBuilder.newCacheManagerBuilder()
        .using(managementRegistry);
    CacheManager cacheManager = cacheManagerBuilder.build();

```

Now, (current master), it will throw when ```cacheManagerBuilder.build()``` is called: 

```
Exception in thread "main" java.lang.IllegalStateException: org.ehcache.core.internal.service.ServiceLocator$DependencyException: Failed to find provider with satisfied dependency set for interface org.ehcache.clustered.client.service.EntityService [candidates []]
	at org.ehcache.core.internal.service.ServiceLocator$DependencySet.build(ServiceLocator.java:321)
	at org.ehcache.core.EhcacheManager.resolveServices(EhcacheManager.java:146)
	at org.ehcache.core.EhcacheManager.<init>(EhcacheManager.java:119)
	at org.ehcache.core.EhcacheManager.<init>(EhcacheManager.java:109)
	at org.ehcache.config.builders.CacheManagerBuilder.newCacheManager(CacheManagerBuilder.java:114)
	at org.ehcache.config.builders.CacheManagerBuilder.build(CacheManagerBuilder.java:70)
	at AnthonyClient.start(AnthonyClient.java:107)
	at AnthonyClient.main(AnthonyClient.java:47)
Caused by: org.ehcache.core.internal.service.ServiceLocator$DependencyException: Failed to find provider with satisfied dependency set for interface org.ehcache.clustered.client.service.EntityService [candidates []]
	at org.ehcache.core.internal.service.ServiceLocator$DependencySet.lookupService(ServiceLocator.java:363)
	at org.ehcache.core.internal.service.ServiceLocator$DependencySet.lookupDependenciesOf(ServiceLocator.java:327)
	at org.ehcache.core.internal.service.ServiceLocator$DependencySet.build(ServiceLocator.java:302)
	... 7 more
```

**Comment by anthonydahanne** [comment]
cc @mathieucarbou

**Comment by mathieucarbou** [comment]
There has been a packaging decision in Ehcache when we introduced clustered: clustering is "automatically" activated if the classes are found on the classpath. This was an ugly hack decided because Ehcache people didn't want to have a new module (`management-clustered`) in Ehcache.

So because if this class detection done in `Clustering` class (https://github.com/ehcache/ehcache3/blob/master/management/src/main/java/org/ehcache/management/cluster/Clustering.java), it is possible that Ehcache tries to activate the clustering management stuff but the cache manager created is not clustered.

I think @chrisdennis wanted to look at that to make it cleaner.

The obvious way to fix that (and this is something that I think should be done) is to separate the code and have the `management` and `management-clustered` module, and then remove the auto-detection (that should have never been there IMO), and then let the user configure the clustering management service if he wants to use it, or, as @chrisdennis suggested, have a way to configure either a management service or a clustered management service depending on what is inside Ehcache's service loader.

**Comment by chrisdennis** [comment]
I disagree. We just need a proper way for the management code to express it's dependencies. Currently the DefaultManagementRegistryService declares:
```java
@ServiceDependencies({CacheManagerProviderService.class, StatisticsService.class, TimeSourceService.class, ExecutionService.class})
@OptionalServiceDependencies({
  "org.ehcache.clustered.client.service.EntityService",
  "org.ehcache.clustered.client.service.ClusteringService"})
```
What this currently means is:
> I depend on CacheManagerProviderService, StatisticsService, TimeSourceService and ExecutionService. And **if the classes are available are on the classpath** I also depend on EntityService and ClusteringService

This just isn't 'optional' enough, what we want is:
> I depend on CacheManagerProviderService, StatisticsService, TimeSourceService and ExecutionService. And **if they are available in the existing dependency set** I also depend on EntityService and ClusteringService.

The management code should be expressing lots of dependencies like this.  It wants to be able to manage/monitor many things that might be used by the customer... but only if the customer is actually using them.

**Comment by henri-tremblay** [comment]
I agree with @chrisdennis. This new definition of optional is what I would expect it to be. You get the service from the `ServiceLocator`, if it's there you use it.  If it's not you don't. Relying on the classpath always felt to me like a bad idea.

And yes, management needs to be able to auto-discover features it wants to monitor.

**Comment by mathieucarbou** [comment]
I agree with @chrisdennis too: this is what I wanted to say when writing: _I think @chrisdennis wanted to look at that to make it cleaner._

But we wouldn't need to do all that if we were able to split the code base.

**Comment by henri-tremblay** [comment]
The problem with a split code base is that the user needs to add a new jar for every new thing she wants to support. I prefer auto-discovery.

**Comment by lorban** [comment]
Since we all agree, let me have a shot at implementing @chrisdennis ' solution.

**Comment by anthonydahanne** [comment]
after building the merged PR locally, the issue was not happening again; it's fixed.
thanks all
