### ISSUE TITLE
Not able to build Ehcache source code version 2.10.4

### ISSUE THREAD

**Issue by jayanth-ganganahalli** [ehcache/ehcache3#2453]
Hi,
I am trying to build Ehcache from source code version 2.10.4 and I am getting "Failed to execute goal on project ehcache-terracotta-bootstrap: Could not resolve dependencies for project net.sf.ehcache.internal:ehcache-terracotta-bootstrap:jar:2.10.4-SNAPSHOT: Failure to find com.terracotta:clustered-entity-management:jar:0.10.0 in the local repository, [ERROR] "

Ideally, I am not able to find the com.terracotta:clustered-entity-management:jar file location from where I can download into my local repository. Please help me in resolving the same.

Below are the environment details:
OS:  Windows 7
Maven version: 3.3.9
Java version: OpenJDK 10.1

I have attached the log file for your reference.
[log1.txt](https://github.com/ehcache/ehcache3/files/2277895/log1.txt)

**Comment by jayanth-ganganahalli** [comment]
When I am trying to build the version 2.10.5, I am getting the below error:
"[ERROR] Failed to execute goal org.apache.maven.plugins:maven-toolchains-plugin:
1.1:toolchain (default) on project ehcache-root: Cannot find matching toolchain
definitions for the following toolchain types:
[ERROR] jdk [ vendor='Oracle Corporation' version='1.6' ]
[ERROR] Please make sure you define the required toolchains in your ~/.m2/toolch
ains.xml file."

I have attached the .m2/toolchains.xml file.
[toolchains.txt](https://github.com/ehcache/ehcache3/files/2277945/toolchains.txt)

**Comment by chrisdennis** [comment]
This is the issue tracker for Ehcache 3.  The issue tracker for Ehcache 2.x is here: https://jira.terracotta.org/jira/browse/EHC/

That said the answer to your two questions is:

1. Are you within a restrictive network, or do you have a mirror setup in maven?  That dependency is available here: http://www.terracotta.org/download/reflector/releases/com/terracotta/clustered-entity-management/0.10.0/clustered-entity-management-0.10.0.pom.  For example I can
```
 curl -L http://www.terracotta.org/download/reflector/releases/com/terracotta/clustered-entity-management/0.10.0/clustered-entity-management-0.10.0.pom
<?xml version="1.0" encoding="UTF-8" standalone="no"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>forge-parent-ee</artifactId>
    <groupId>org.terracotta.forge</groupId>
    <version>3.7</version>
  </parent>

  <groupId>com.terracotta</groupId>
  <artifactId>clustered-entity-management</artifactId>
  <version>0.10.0</version>
  <packaging>jar</packaging>

  <name>clustered-entity-management</name>
...
```
2. You need to have a 1.6 JDK installed on your machine and correctly recorded in your toolchains.xml to be able to build the 2.x releases: https://maven.apache.org/guides/mini/guide-using-toolchains.html
