### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by RadhakrishnanKandasamy** [ehcache/ehcache3#2479]
Is there any discussion forum available for ehcache? I need to know whether we can use ehcache without ehcache.xml configuration? If yes what is the default cache configuration that is used by ehcache.

**Comment by henri-tremblay** [comment]
The mailing list is referenced on https://github.com/ehcache/ehcache3/blob/master/CONTRIBUTING.adoc.

No. You need configuration. Not having cache configuration is craziness. However, you can do it programmatically. So without `ehcache.xml`. See https://github.com/ehcache/ehcache3-samples/blob/master/basic/src/main/java/org/ehcache/sample/BasicProgrammatic.java.
