### ISSUE TITLE
Add semantical `unlimited|infinite` for heap size.

### ISSUE THREAD

**Issue by marceloverdijk** [ehcache/ehcache3#2496]
I'm currently using a high number to define an unlimited/infinite cache like:

```
<cache alias="Countries" uses-template="default">
    <heap unit="entries">1000</heap>
</cache>
```

Upfront I know there will be approx 250 countries so I basically don't want to think about the max size.
At the moment it is not possible to specify a heap cache without a number.

As @henri-tremblay also suggested this could save a save an increment and number comparison at insertion. However it's doubtable if it is worth the effort.
See https://groups.google.com/forum/#!category-topic/ehcache-users/ehcache-core/lce8TqMOxEA

**Comment by ljacomet** [comment]
Not having an unlimited value was a design decision when work started on Ehcache 3.

Allowing a cache to grow out of bonds would enable Ehcache to bring down a JVM with an `OutOfMemoryError`, which goes against the goal of resiliency in Ehcache, that is transparent caching failures.

And it does not fit with the purpose of caching which is about trading increased memory usage for reduced latency, as a performance optimisation.

I understand it makes the getting started easier, but experience was that easy starting sometimes ended up causing real production grief.

**Comment by marceloverdijk** [comment]
@ljacomet I understand the design decision and the reasoning. So I'm fine with it.

However, even setting a max size to 100 could bring down the JVM as you don't know how big the objects are being stored.
I fully agree that by configuring a number people need to think about it, which could avoid real production grief. That being said, I could think of an explicit infinite option like `<heap inifinite="true"></heap>`. But is it worth it..

**Comment by chrisdennis** [comment]
> Upfront I know there will be approx 250 countries so I basically don't want to think about the max size.

So set the cache size to 1000 and be done.  There are two scenarios here:

1. You have a known upper bound on the size of the universe of all elements. Then set the limit to somewhere above that (and beneath infinity to avoid any risk of OOME). If you want to push things here you can always pick `Integer.MAX_VALUE` or such.
2. You have no known upper bound on the size of the universe of all elements. Then set the limit to a reasonable value beneath infinity to avoid any risk of OOME.

There is no scenario where choosing infinity is necessary (or even makes sense).

**Comment by henri-tremblay** [comment]
Yes. Setting to a 1000 was my solution on the mailing list.

The only scenario I see is: 
* I know I have a limited number of values.
* I know it won't overflow
* So I don't care about setting a limit and checking it
* I would prefer the 5-10 nanoseconds provided by removing the check

I agree it is not a high priority. And using a normal HashMap might be a better fit in the case.

**Comment by marceloverdijk** [comment]
I'm using Ehcache for Hibernate second-level cache and want to cache some reference tables.
I don't want to put any limits on these caches as they will not be that big, but you don't know exactly how big. Think about Country, Product Category, etc. tables.

As I'm using it in combination with Hibernate second-level cache I can't use simple `HashMap` ro refer to manually. Also simply using `Integer.MAX_VALUE` is not an option as I'm using a xml configuration. But basically this is what I would like to use. Use some pseudo value instead of an reasonable value.
`Integer.MAX_VALUE` is also used as a semantical infinite value in this case :-)

It's not a big deal btw, I can/will simply use something like `9999` .

**Comment by henri-tremblay** [comment]
Make sense @marceloverdijk . In the Hibernate second-level cache context, it makes total sense to stick with Ehcache.
