### ISSUE TITLE
Who can help me  ?  Ehcache 3.4.0   Custom Serializers  get Error : Method threw 'org.ehcache.spi.serialization.SerializerException' exception. Cannot evaluate org.ehcache.impl.internal.store.offheap.LazyOffHeapValueHolder.toString()

### ISSUE THREAD

**Issue by EstarG** [ehcache/ehcache3#2502]
hello , I see the  document (http://www.ehcache.org/blog/2016/05/12/ehcache3-serializers.html#disqus_thread) and then write example， but invoke 'cache.getAll()' get null and debug get error : Method threw 'org.ehcache.spi.serialization.SerializerException' exception. Cannot evaluate org.ehcache.impl.internal.store.offheap.LazyOffHeapValueHolder.toString()

invoke "cache.get()" can get correct value . 

![image](https://user-images.githubusercontent.com/3282626/47481983-daddcc00-d867-11e8-82a8-c5e403d133cd.png)

```java
public class SerializerTest {
    CacheManager dataCacheManager = null;
    Cache        myCache          = null;

    @Test
    public void test() {

        try {

            CacheConfiguration<String, TestVO> dataCacheConfig = CacheConfigurationBuilder
                .newCacheConfigurationBuilder(
                    String.class,
                    TestVO.class,
                    ResourcePoolsBuilder.newResourcePoolsBuilder().heap(10)
                        .offheap(10, MemoryUnit.MB)).withExpiry(Expirations.noExpiration())
                .withValueSerializer(new HessianSerializer()).build();
            dataCacheManager = CacheManagerBuilder.newCacheManagerBuilder()
                .withCache("Test", dataCacheConfig).build(true);
            myCache = dataCacheManager.getCache("Test", String.class, TestVO.class);

            for (int i = 0; i < 10; ++i) {
                TestVO testVO = new TestVO("k" + i, "v" + i);
                myCache.put("key" + i, testVO);
            }
            System.out.println("get key0=" + myCache.get("key0"));
            System.out.println("get key1=" + myCache.get("key1"));

            // get null , debug get error : Method threw 'org.ehcache.spi.serialization.SerializerException' exception. Cannot evaluate org.ehcache.impl.internal.store.offheap.LazyOffHeapValueHolder.toString()
            System.out.println("getAll=" + myCache.getAll(Sets.newHashSet("key0", "key1")));

        } catch (Throwable tr) {
            System.out.println("ehcache error : " + tr);
            Assert.assertTrue(false);
        }
    }

    class HessianSerializer implements Serializer<TestVO> {

        private final HessianSerUtils HESSIAN_SER_UTILS = new HessianSerUtils();

        public HessianSerializer(ClassLoader loader) {
            //no-op
        }

        public HessianSerializer() {
            //no-op
        }

        @Override
        public ByteBuffer serialize(TestVO object) throws SerializerException {

            try {
                return ByteBuffer.wrap(HESSIAN_SER_UTILS.serialize(object));
            } catch (IOException e) {
                e.printStackTrace();
            }
            return null;
        }

        @Override
        public TestVO read(ByteBuffer binary) throws ClassNotFoundException, SerializerException {
            try {
                return (TestVO) HESSIAN_SER_UTILS.deserialize(binary.array());
            } catch (IOException e) {
                e.printStackTrace();
            }
            return null;
        }

        @Override
        public boolean equals(TestVO object, ByteBuffer binary) throws ClassNotFoundException,
                                                               SerializerException {
            return object.equals(read(binary));
        }
    }
}
```

debug find invoke "cache.put()" , the data in cache is : 
![image](https://user-images.githubusercontent.com/3282626/47482901-68222000-d86a-11e8-8653-8340842198b8.png)

I'm sorry  , My English is very poor. but who can help me ? why ?

**Comment by henri-tremblay** [comment]
Where can we find `HessianSerUtils`?

**Comment by henri-tremblay** [comment]
Ok. There is indeed something odd. I managed to reproduce a similar issue (but not identical so knowing where to find `HessianSerUtils` is still relevant).

```
import org.ehcache.Cache;
import org.ehcache.CacheManager;
import org.ehcache.config.CacheConfiguration;
import org.ehcache.config.builders.CacheConfigurationBuilder;
import org.ehcache.config.builders.CacheManagerBuilder;
import org.ehcache.config.builders.ResourcePoolsBuilder;
import org.ehcache.config.units.MemoryUnit;
import org.ehcache.expiry.Expirations;
import org.ehcache.spi.serialization.Serializer;
import org.ehcache.spi.serialization.SerializerException;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class SerializerTest {

  public static class TestVO implements Serializable {
    private String key;
    private String value;

    public TestVO(String key, String value) {
      this.key = key;
      this.value = value;
    }

    public String getKey() {
      return key;
    }

    public String getValue() {
      return value;
    }
  }

  CacheManager dataCacheManager = null;
  Cache myCache = null;

  @Test
  public void test() {
    CacheConfiguration<String, TestVO> dataCacheConfig = CacheConfigurationBuilder
        .newCacheConfigurationBuilder(
            String.class,
            TestVO.class,
            ResourcePoolsBuilder.newResourcePoolsBuilder().heap(10)
                .offheap(10, MemoryUnit.MB)).withExpiry(Expirations.noExpiration())
        .withValueSerializer(new HessianSerializer()).build();
    dataCacheManager = CacheManagerBuilder.newCacheManagerBuilder()
        .withCache("Test", dataCacheConfig).build(true);
    myCache = dataCacheManager.getCache("Test", String.class, TestVO.class);

    for (int i = 0; i < 10; ++i) {
      TestVO testVO = new TestVO("k" + i, "v" + i);
      myCache.put("key" + i, testVO);
    }

    // get null , debug get error : Method threw 'org.ehcache.spi.serialization.SerializerException' exception. Cannot evaluate org.ehcache.impl.internal.store.offheap.LazyOffHeapValueHolder.toString()
    Map<String, TestVO> result = myCache.getAll(new HashSet(Arrays.asList("key0", "key1")));
    assertEquals(2, result.size());
    assertNotNull(result.get("key1"));
    assertNotNull(result.get("key2"));
  }

  static class HessianSerializer implements Serializer<TestVO> {

    @Override
    public ByteBuffer serialize(TestVO object) throws SerializerException {
      try(ByteArrayOutputStream bOut = new ByteArrayOutputStream();
          ObjectOutputStream out = new ObjectOutputStream(bOut)) {
          out.writeObject(object);
          out.flush();
        return ByteBuffer.wrap(bOut.toByteArray());
      } catch (IOException e) {
        throw new SerializerException(e);
      }
    }

    @Override
    public TestVO read(ByteBuffer binary) throws ClassNotFoundException, SerializerException {
      try(ObjectInputStream in = new ObjectInputStream(new ByteArrayInputStream(binary.array()))) {
        return (TestVO) in.readObject();
      } catch (Exception e) {
        throw new SerializerException(e);
      }
    }

    @Override
    public boolean equals(TestVO object, ByteBuffer binary) throws ClassNotFoundException,
        SerializerException {
      return object.equals(read(binary));
    }
  }
}
```

**Comment by chrisdennis** [comment]
I think I know whats going on here... will report back in a few minutes.

**Comment by chrisdennis** [comment]
Your bug is in attempting to call `ByteBuffer.array()` without checking whether `ByteBuffer.hasArray()` is `true`. Even if the byte buffer has an array you need to offset all your access by `ByteBuffer.arrayOffset()` since your buffer could just be a slice of a larger buffer.

**Comment by henri-tremblay** [comment]
I'm not sure. That's the problem he had. But, @chrisdennis, can you give the code solving the issue?

**Comment by EstarG** [comment]
hi @henri-tremblay @chrisdennis : 

here is  HessianSerUtils：
`import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

import com.alipay.sofa.platform.cache.hessian.OperationRoleSerializerFactory;
import com.caucho.hessian.io.Hessian2Input;
import com.caucho.hessian.io.Hessian2Output;
import com.caucho.hessian.io.SerializerFactory;


public class HessianSerUtils {

    public byte[] serialize(Object obj) throws IOException {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        Hessian2Output output = new Hessian2Output(bos);
        output.setSerializerFactory(getSerializerFactory());
        output.writeObject(obj);
        output.close();
        return bos.toByteArray();
    }

    public Object deserialize(byte[] content) throws IOException {
        ByteArrayInputStream bis = new ByteArrayInputStream(content);
        Hessian2Input input = new Hessian2Input(bis);
        input.setSerializerFactory(getSerializerFactory());
        Object obj = input.readObject();
        input.close();
        return obj;
    }

    private static SerializerFactory _serializerFactory = null;

    synchronized public static final SerializerFactory getSerializerFactory() {
        if (_serializerFactory == null) {
            _serializerFactory = new SerializerFactory();

            _serializerFactory.addFactory(new OperationRoleSerializerFactory());
        }
        return _serializerFactory;
    }
}`


and @henri-tremblay  your code has the same problom : 
![image](https://user-images.githubusercontent.com/3282626/47541176-ed5d1180-d90a-11e8-8fe3-699bfe4c4c01.png)
![image](https://user-images.githubusercontent.com/3282626/47541232-24332780-d90b-11e8-98ed-8c42b8306705.png)

I think I need to learn ByteBuffer， can you help me solve this problem ? 

chrisdennis  : 'I think I know whats going on here... will report back in a few minutes.'       where is report ?   Very looking forward to。   

I'm sorry My English is very poor, very thanks @henri-tremblay @chrisdennis

**Comment by chrisdennis** [comment]
The simplest solution here would be to use an instance of [`ByteBufferInputStream`](https://github.com/ehcache/ehcache3/blob/0d9707020e9683af8d5e0bcf5ccc3ca4e6f5ea65/impl/src/main/java/org/ehcache/impl/internal/util/ByteBufferInputStream.java). Of course that class isn't public API though.

The alternative would be to write a utility method something like this:
```java
if (buffer.hasArray()) {
  int start = buffer.arrayOffset() + buffer.position();
  return new ByteArrayInputStream(copyOfRange(buffer.array(), start, start + buffer.remaining());
} else {
  byte[] array = new byte[buffer.remaining()];
  buffer.get(array);
  return new ByteArrayInputStream(array);
}
```

**Comment by EstarG** [comment]
> The simplest solution here would be to use an instance of [`ByteBufferInputStream`](https://github.com/ehcache/ehcache3/blob/0d9707020e9683af8d5e0bcf5ccc3ca4e6f5ea65/impl/src/main/java/org/ehcache/impl/internal/util/ByteBufferInputStream.java). Of course that class isn't public API though.
> 
> The alternative would be to write a utility method something like this:
> 
> ```java
> if (buffer.hasArray()) {
>   int start = buffer.arrayOffset() + buffer.position();
>   return new ByteArrayInputStream(copyOfRange(buffer.array(), start, start + buffer.remaining());
> } else {
>   byte[] array = new byte[buffer.remaining()];
>   buffer.get(array);
>   return new ByteArrayInputStream(array);
> }
> ```

can you give me a  example ？ very thanks。

**Comment by EstarG** [comment]
@henri-tremblay @chrisdennis  Very thanks, I have solved this problem。

` @Override
        public TestVO read(ByteBuffer binary) throws ClassNotFoundException, SerializerException {
            try {

                if(binary.hasArray()) {
                    return (TestVO) HESSIAN_SER_UTILS.deserialize(binary.array());
                } else {
                    byte[] array = new byte[binary.remaining()];
                    binary.get(array);
                    return (TestVO) HESSIAN_SER_UTILS.deserialize(array);
                }

            } catch (IOException e) {
                e.printStackTrace();
            }
            return null;
        }`
