### ISSUE TITLE
why is the off-heap occupiedMemory  out of the heap occupiedMemory  so many times ?

### ISSUE THREAD

**Issue by EstarG** [ehcache/ehcache3#2509]
I debug the code, find the data in offheap useed  9.69M  by  Hessian serialize .   but in heap the data used  47.13M ?  so many times, why ? 

![image](https://user-images.githubusercontent.com/3282626/47830213-e3815580-ddc5-11e8-8d80-a4b52c1bd37f.png)

this is my log of cache memery: 
![image](https://user-images.githubusercontent.com/3282626/47830080-4c1c0280-ddc5-11e8-8097-676f33f955cb.png)

I'm Not found in the official documentation.

I am sorry, my English is very poor.

**Comment by henri-tremblay** [comment]
Hi. I should have told you that the first time but the issue tracker is not a helpdesk. We ask our users to ask questions on the [mailing list](https://groups.google.com/forum/#!forum/ehcache-users) first. If they turn out to be issues, we will tell you to create one.

At first sight, this is not crazy. Hessian will keep only the data. Java has a full-fledge object. For example an Integer is 16 bytes. And a stored "int" is 4.

**Comment by EstarG** [comment]
> Hi. I should have told you that the first time but the issue tracker is not a helpdesk. We ask our users to ask questions on the [mailing list](https://groups.google.com/forum/#!forum/ehcache-users) first. If they turn out to be issues, we will tell you to create one.
> 
> At first sight, this is not crazy. Hessian will keep only the data. Java has a full-fledge object. For example an Integer is 16 bytes. And a stored "int" is 4.


very sorry，I will go to mailing list next time.  and , Can you explain the 'onHeapKeyOffset'  'chmTreeBinOffset'   to me?   or have documents  ?    why every maping in cache add (96+56)B ?

**Comment by henri-tremblay** [comment]
**chmTreeBinOffset:** Ehcache stores entries in a tweaked ConcurrentHashMap. This HashMap stores entries in an Object called the TreeBin. It has always the same size. To we add this size to the size of the entry itself to calculate the cache size.

** onHeapKeyOffset:** Same kind of thing. When a `KeyCopier` is used, the key is wrapped in a `CopiedOnHeapKey`.  So we calculate the size of this object and add it to any key size.

One thing is strange though. It seems to be used even without a `KeyCopier`. @AbfrmBlr Do you know why we add `onHeapKeyOffset` all the time?
