### ISSUE TITLE
BasicClusteredWriteBehindTest is failing randomly

### ISSUE THREAD

**Issue by henri-tremblay** [ehcache/ehcache3#2517]
This test keeps failing on CI.

Example is https://dev.azure.com/TerracottaCI/ehcache/_build/results?buildId=339&view=logs

I don't know if it shows an actual problem or it is just unstable.

**Comment by AbfrmBlr** [comment]
Still failing https://dev.azure.com/TerracottaCI/ehcache/_build/results?buildId=379&view=logs

**Comment by henri-tremblay** [comment]
Here the test seem to have deadlock: https://dev.azure.com/TerracottaCI/ehcache/_build/results?buildId=405&view=logs

**Comment by ramsai1729** [comment]
@henri-tremblay I don't see any client/server logs for failing tests, is there a way to get them?

**Comment by henri-tremblay** [comment]
There are no failing test. The buuld got stuck on the test and then timed out

**Comment by ramsai1729** [comment]
I am not asking for this particular test failure, can't find client/server logs for any failed tests. BTW how do you know this test got stuck?

**Comment by henri-tremblay** [comment]
No idea. I think we should add a rule to timeout and see where we are stuck. @akomakom Are the server logs somewhere? 

```
    @Rule
    public Timeout timeout = new Timeout(1000, TimeUnit.MILLISECONDS);
```

**Comment by akomakom** [comment]
@henri-tremblay nothing is currently saved.  We can, I believe, have the job attach arbitrary artifacts to the build.  Alternatively, if you can have the Timeout logic print out the logs to stdout, that would be part of the build output in azure.

**Comment by henri-tremblay** [comment]
Yes. That's what I will do right now.

**Comment by henri-tremblay** [comment]
@ramsai1729 Please merge #2528 and rebase this PR. IT should help debugging

**Comment by henri-tremblay** [comment]
@ramsai1729 @akomakom Have you seen it failing lately?

**Comment by ramsai1729** [comment]
AFAIK no recent failures.

**Comment by henri-tremblay** [comment]
Let's consider it fixed.
