### ISSUE TITLE
Replace "old" DiskStore with "new" DiskStore

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#252]
Wire it _all_ in and have CRUD ops implemented (and wired) at the `Store` level

**Comment by alexsnaps** [comment]
Wire it _all_ in and have CRUD ops implemented (and wired) at the `Store` level

**Comment by ljacomet** [comment]
May require some work in offheap library

**Comment by ljacomet** [comment]
As part of this, `StoreEventListenerTest` StoreSPITest should be split between expiry and eviction.
This would allow all store impls to pass the expiry ones while the count based eviction remains an issue for stores where the natural unit is memory.
