### ISSUE TITLE
StandardEhcacheStatisticsTest.getCacheGetHitMissLatencies

### ISSUE THREAD

**Issue by GaryWKeim** [ehcache/ehcache3#2523]
This tests fails daily on Windows.

Failed : org.ehcache.management.providers.statistics.StandardEhcacheStatisticsTest.getCacheGetHitMissLatencies - Stack Trace
--
Cause : java.lang.AssertionError: Expecting: <149714630L> to be greater than or equal to: <150000000L>

**Comment by henri-tremblay** [comment]
Closed by #2524
