### ISSUE TITLE
Waiting on lock - com.terracotta.toolkit.object.serialization.customLifespanSerializedMapValue

### ISSUE THREAD

**Issue by Alfred6556** [ehcache/ehcache3#2547]
Our ColdFusion 2016 application server uses distributed Terracotta cache. This morning our server came to a standstill. A lock was causing requests to pile up. They were all waiting for the lock, com.terracotta.toolkit.object.serialization.customLifespanSerializedMapValue. 

I cannot find anything about this on the web. Do you know what kind of object this is? Do you also have any idea how we canprevent this in future?  

![image](https://user-images.githubusercontent.com/45388372/49942312-3f6eec00-fee5-11e8-8c6c-c84956e69945.png)

**Comment by Alfred6556** [comment]
Sorry, Henri. 
I came here by accident. My intention was to post in the user forum.

**Comment by henri-tremblay** [comment]
Yes please. This is also an Big Memory issue I think. Not an Ehcache 3 or Terracotta server issue. So closing this.

**Comment by Alfred6556** [comment]
Hi Henri, 

Thank you for the information and for your kindness. I shall duly look in the direction of Big Memory.
