### ISSUE TITLE
Add event notification verification to Ehcache unit tests

### ISSUE THREAD

**Issue by cljohnso** [ehcache/ehcache3#261]
The `Ehcache` unit tests in the `EhcacheBasic*Test` classes do not validate event notification.  This checking needs to be added.

**Comment by sunnydas** [comment]
Have added separate events test for the ehcachebasic*Test(s) , did not revert the original basicTests to exclude events. Please let me know if that is Ok.

**Comment by sunnydas** [comment]
I found it easier to inlcude EhcacheCrudbase in the eventing tests as a few things were reused in the test,
