### ISSUE TITLE
Equivalent configuration from ehcache 2.x to 3.x 

### ISSUE THREAD

**Issue by maniprabu101993** [ehcache/ehcache3#2622]
Many of the xml configuration present in the 2.x version doesn't have equivalent configuration in 3.x version.

What is the equivalent tag for overflowToDisk="false", diskPersistent="false", memoryStoreEvictionPolicy="LRU" in 3.x XML configuration.

**Comment by chrisdennis** [comment]
This isn't a bug... these kind of usability questions are usually best addresses on the ehcache mailing list: ehcache-users@googlegroups.com.

The fragments you describe above don't really describe a complete cache configuration, and the memory store eviction policy is not configurable in Ehcache 3. With a little bit of speculation you probably want something like this.

```xml
<ehcache:config xmlns:ehcache='http://www.ehcache.org/v3'>
  <ehcache:cache alias="your-cache">
    <ehcache:key-type>com.example.KeyClass</ehcache:key-type>
    <ehcache:value-type>com.example.ValueClass</ehcache:value-type>
    <ehcache:heap>10000</ehcache:heap>
  </ehcache:cache>
</ehcache:config>
```

**Comment by maniprabu101993** [comment]
I want to know ,what is the cache eviction mechanism used in ehcache 3.x
version if there is no cache eviction mechanism specified in XML or by
code?whether it uses LRU approach by default?I asked the same question in
google groups and didn't received any reply from anyone

**Comment by chrisdennis** [comment]
Which eviction algorithm is used depends on what resources are configured and is intentionally left unspecified to allow different store implementations to make an appropriate choice. That said the eviction algorithms used by the various stores can be consider "approximate LRU" in the same sense that the default eviction behavior in Ehcache 2.x was as well.
