### ISSUE TITLE
Writebehind Cache not clearing mappings

### ISSUE THREAD

**Issue by pavanmn18** [ehcache/ehcache3#2624]
Hi,

I am using EhCache 3.5.2.
I used the following code to create WriteBehind Cache. 

```java
CacheManager cacheManager
	        = CacheManagerBuilder.newCacheManagerBuilder()
	        .using(PooledExecutionServiceConfigurationBuilder.newPooledExecutionServiceConfigurationBuilder() 
	            .defaultPool(defaultPoolName, 0, defaultMaxPoolSize)
	            .pool(defaultWriteBehindPoolName,writeBehindPoolMinSize, writeBehindPoolMaxSize)
	            .build()).with(new CacheManagerPersistenceConfiguration(new File(dirName)))
	        .withDefaultWriteBehindThreadPool(defaultWriteBehindPoolName)
	        .using(statisticsService)
	        .build(true); 
cacheManager.createCache(cacheName,
	            CacheConfigurationBuilder.newCacheConfigurationBuilder(Class.forName(key.getName()), Class.forName(value.getName()),
	                                          ResourcePoolsBuilder.newResourcePoolsBuilder().heap(heapSize, EntryUnit.ENTRIES).disk(disk, MemoryUnit.MB,true))
	            .withLoaderWriter(ehM.new MapCacheLoaderWriter())
	               .add(WriteBehindConfigurationBuilder
	                    .newBatchedWriteBehindConfiguration(2, TimeUnit.SECONDS, 500).
	                    .queueSize(1000)
	                    .concurrencyLevel(10).disableCoalescing()));
```

However when I am trying to refresh the data by calling the clear method on this cache -it doesn't remove the mappings. Only if I call  remove explicitly on keys its removing the mapping.
Same thing works perfectly with a normal PersistentCache.
Any suggestions /ideas why this might be happening?

Regards,
Pavan

**Comment by chrisdennis** [comment]
The `clear()` method is explicitly documented to not do anything with the `CacheLoaderWriter`.
```java
  /**
   * Removes all mappings currently present in the {@code Cache}.
   * <p>
   * It does so without invoking the {@link CacheLoaderWriter} or any registered
   * {@link org.ehcache.event.CacheEventListener} instances.
   * <em>This is not an atomic operation and can potentially be very expensive.</em>
   */
  void clear();
```
What you're asking the cache to do isn't (currently) possible given the definition of the `CacheLoaderWriter`.  The loader-writer doesn't have the ability to "remove" all the backing systems contents, it only supports removing identified keys.

What you're trying to achieve might better accomplished by coordinating for the cache clear and DB clear (drop, truncate or whatever) to occur as two separate actions that the application performs while coordinating and controlling the user transaction load to prevent perceived discrepancies.

**Comment by pavanmn18** [comment]
Thanks for the response Chris! I hadn't noticed the javadoc of clear method. Any plans of supporting clear in the future(for writebehind)?
