### ISSUE TITLE
how to invoke <T> T get(Object key, @Nullable Class<T> type) in interface cache

### ISSUE THREAD

**Issue by rancho00** [ehcache/ehcache3#2625]
I looked through a lot of materials but I didn't see any cases, please

**Comment by chrisdennis** [comment]
This looks like it might be a Spring usage problem. Regardless, these kinds of user problems (unless they are clear bugs) are best addressed via the mailing list: ehcache-users@googlegroups.com

If you could post your problem there in more detail then someone may be able to help you.
