### ISSUE TITLE
CacheConfiguration and CacheStatistics MBeans are registered again and again

### ISSUE THREAD

**Issue by evernat** [ehcache/ehcache3#2641]
Following #1928, CacheConfiguration and CacheStatistics MBeans are registered again for each call to `Caching.getCachingProvider().getCacheManager().getCacheNames()` (that is to `Eh107CacheManager.getCacheNames()`).

For example, the following code using the JSR107 api with Ehcache v3.7.1:
```java
MutableConfiguration conf = new MutableConfiguration();
conf.setManagementEnabled(true);
conf.setStatisticsEnabled(true);
Caching.getCachingProvider().getCacheManager().createCache("test", conf);
Caching.getCachingProvider().getCacheManager().getCacheNames();
Caching.getCachingProvider().getCacheManager().getCacheNames();
Caching.getCachingProvider().getCacheManager().getCacheNames();
```

gives the following logs:
```
15:32:57.025 [http-nio-8080-exec-2] INFO  org.ehcache.core.EhcacheManager - Cache 'test' created in EhcacheManager.
15:32:57.086 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheConfiguration,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.088 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.100 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheConfiguration,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.103 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.110 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheConfiguration,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.111 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.112 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheConfiguration,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.113 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
```

Registering MBeans again and again in `CacheManager.getCacheNames()` seems not needed and not efficient.
I suggest to check if MBeans are already registered, using `config.isManagementEnabled()` and `config.isStatisticsEnabled()` in `Eh107Cache`, before registering MBeans in `Eh107CacheManager.refreshAllCaches()`.

**Comment by evernat** [comment]
By the way, regreshAllCaches() is called in getCacheNames() for #523

**Comment by anthonydahanne** [comment]
hello, and thanks for the report.
I have not yet investigated, but if you could raise a PR, that'd be awesome (and would help us get to is faster)
thanks again !

**Comment by evernat** [comment]
A snapshot build is available at:
http://javamelody.org/downloads/javamelody-core-1.78.0-SNAPSHOT.jar

**Comment by evernat** [comment]
PR #2642

**Comment by JohannesBe** [comment]
I think this issue should be raised in priority. As of now there is no good way to initialize caches in spring + EhCache 3, without initializing them twice. Multiple problem are having this problem: see also https://stackoverflow.com/a/65836250/1493235

**Comment by linghengqian** [comment]
https://github.com/ehcache/ehcache3/pull/2642 , Why is this pull request still not merged?

**Comment by linghengqian** [comment]
I'm not sure if I'm doing it wrong on the `master` branch, but my local testing of the #2642 solution doesn't solve the problem. Are there any friends willing to submit a new PR for verification?

**Comment by linghengqian** [comment]
I created a new PR to resolve the conflict of merging the master branch in the old PR. Reference https://github.com/ehcache/ehcache3/pull/2991
