### ISSUE TITLE
Re-sync ConcurrentHashMap fork

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#2654]
Our version of CHM has a bug which makes calling a compute within a compute livelock, see: https://stackoverflow.com/questions/56214217/why-ehcache-3-7-1-deadlock-in-org-ehcache-impl-internal-concurrent-concurrenthas

This apparently has been fixed in JDK 12, so we should re-sync our fork with the latest version to get that fix and possibly some more.

**Comment by ben-manes** [comment]
You can apply just this patch if resync’ing is too burdensome. This was the fix Doug applied when I reported it, due to a user discovering it similarly.

http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/main/java/util/concurrent/ConcurrentHashMap.java?r1=1.313&r2=1.314

**Comment by chrisdennis** [comment]
Covered under: #3064
