### ISSUE TITLE
How to implement Real-time Synchronization data from memory to disk  in Ehcache 3.x ?

### ISSUE THREAD

**Issue by frank1998819** [ehcache/ehcache3#2655]
How to implement Real-time Synchronization data from memory to disk  in Ehcache 3.x ?

when application exception shutdown or restart it will lose data,  I hope to achieve the effect with Ehcache 2.6+ , such as the following ehcache2.6.xml config: 

-     <cache  name="test" ...> 
-  	   <persistence strategy="localRestartable"  synchronousWrites="true" />
-      </cache> 

after any restart, data that was last in the cache will automatically load from disk into the RestartStore.

so that  How to implement Real-time Synchronization data from memory to disk  in Ehcache 3.x ?  How can I config it  in Ehcache 3.x ?

Thanks in advance.

**Comment by chrisdennis** [comment]
The open source disk store (as you have configured above) will correctly restore the contents of the cache only if the environment is cleanly shutdown. If the cache is not cleanly shutdown then the cache will not recover it's contents. Resilient disk stores are currently a commercial feature only. Sorry!
