### ISSUE TITLE
How to implement Real-time Synchronization data from memory to disk in Ehcache 3.8? 

### ISSUE THREAD

**Issue by ehgplus** [ehcache/ehcache3#2686]
How to implement Real-time Synchronization data from memory to disk in Ehcache 3.8? 
after any restart,  cache will automatically load from disk into the RestartStore. , such as the following ehcache3.8.xml config:
```xml
    <eh:cache-template name="default">
        <eh:key-type>java.lang.String</eh:key-type>
        <eh:value-type>java.lang.Object</eh:value-type>
        <eh:resources >
            <eh:heap>2000</eh:heap>
            <eh:offheap unit="MB">100</eh:offheap>
            <eh:disk persistent="true" unit="MB">500</eh:disk>
        </eh:resources>
    </eh:cache-template>
    <eh:cache alias="login_user_info" uses-template="default">
        <eh:loader-writer>
            <eh:class>org.ehcache.docs.plugs.ListenerObject</eh:class>
            <eh:write-behind thread-pool="cache2Pool">
                <eh:batching batch-size="5">
                    <eh:max-write-delay>10</eh:max-write-delay>
                </eh:batching>
            </eh:write-behind>
        </eh:loader-writer>
        <eh:listeners dispatcher-thread-pool="cache2Pool"/>
        <eh:disk-store-settings thread-pool="defaultDiskPool"  writer-concurrency="2"/>
    </eh:cache>
```

failed，
so that How to implement Real-time Synchronization data from memory to disk in Ehcache 3.8? How can I config it in Ehcache 3.8?
Thanks in advance.

**Comment by chrisdennis** [comment]
The open source disk store (as you have configured above) will correct restore the contents of the cache only if the environment is cleanly shutdown. If the cache is not cleanly shutdown then the cache will not recover it's contents. Resilient disk stores are currently a commercial feature only. Sorry!
