### ISSUE TITLE
DiskWriteThreadPool may cause OOM in some Scenes

### ISSUE THREAD

**Issue by jianliu** [ehcache/ehcache3#2707]
I am testing disk write and heap size using version  Ehcache3.8.1  ,and I want to store datas at disk when cache datas come to the heap size,but now I find OOM,the code is here：
jvm options: -Xms350m -Xmx350m

		CacheManagerBuilder<PersistentCacheManager> cacheManagerBuilder = CacheManagerBuilder.newCacheManagerBuilder()
				.with(CacheManagerBuilder.persistence(new File("D:\\ehcache\\" + System.currentTimeMillis(), "data")));

		cacheManagerBuilder = cacheManagerBuilder.withCache("sample",CacheConfigurationBuilder.newCacheConfigurationBuilder(String.class, byte[].class,

		ResourcePoolsBuilder.newResourcePoolsBuilder()
								.heap(300, MemoryUnit.MB)
								.offheap(500, MemoryUnit.MB)
								.disk(20, MemoryUnit.GB, true)
				).withExpiry(ExpiryPolicyBuilder.timeToLiveExpiration(Duration.ofDays(1))));

		PersistentCacheManager persistentCacheManager = cacheManagerBuilder.build(true);
		Cache<String, byte[]> cache = persistentCacheManager.getCache("sample", String.class, byte[].class);

		for (int i = 1; i < 20000; i++) {
			//this is 100K 
			cache.put(i + "", new byte[100000]);   //write too fast ,and DiskWriteThreadPool cache task in queue
		}

well,I set heap size to 300M, and expect to cache 300M data in heap memory, and put 20000s item,the size of a item is 100KB

Now OOM is happend ,and I dump the heap and use jhat to find what happend, Finally, I find the reason is FileBackedStorageEngine$FileWriteTask  has 3455 instances,and every task has a valuebuffer hold 100056B,the queued task use up the heap at last.

So I continue to find why there is so many task,and find DiskWriteThreadPool executorService use a queue:new LinkedBlockingQueue() ,the default capcity is Integer.MAX_VALUE, and it is hard to change the queueSize.

		writer = this.executionService.getOrderedExecutor(this.poolAlias, new LinkedBlockingQueue());

In general，if the write/put is too fast,the task will cache in the queue, and finally OOM, if I add Thread.sleep(10) in the for loop, OOM will not happend.
The only way I find is try to change OnDemandExecutionService's code, and do not use the default queue.
Is there someway to avoid this, I am warried about my app put too fast to OOM?

**Comment by jianliu** [comment]
I had use SPI to change the class: OnDemandExecutionService's method implementation, and do not use the pass paramter:queue ,instead, I define a new queue where cap is 5.
But I don't think this is the best way to avoid OOM,because it is a little stiff.

**Comment by jdimeo** [comment]
Has this been solved? I wrote about this here too: https://stackoverflow.com/questions/59777140/unbounded-diskwritethreadpool-causing-memory-leak-in-ehcache
