### ISSUE TITLE
Need Some Detail Build And Deploy Wiki

### ISSUE THREAD

**Issue by geekMessi** [ehcache/ehcache3#2710]
Are there any detail wiki about how to build from source ? However ,  I build failed at some release branch.
And Are there any detail wiki about delopying the Ehcache Server/Terracotta Server?
Need some detail and precision documents.

**Comment by chrisdennis** [comment]
I'm slightly confused about what is that you're trying to do. If you want to build the source code you can use the gradle wrapper script:
```
./gradlew assemble
```
or (`gradlew.bat` on windows). The documentation on how to use the server is here: http://www.ehcache.org/documentation/3.8/clustered-cache.html
