### ISSUE TITLE
Require capability - osgi.ee; (&(osgi.ee=JavaSE)(version=9.0))

### ISSUE THREAD

**Issue by saurabhgupta1233** [ehcache/ehcache3#2717]
I am not an expert but when i added ehcache 3.8.x. I started getting this error.

Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle SaurabhPlugin:SaurabhPlugin [374]: Unable to resolve 374.0: missing requirement [374.0] osgi.ee; (&(osgi.ee=JavaSE)(version=9.0))

I believe this error means the osgi ee container should be able to provide java 9 capability. 
Please let me know if i am wrong.

**Comment by chrisdennis** [comment]
Ehcache requires:
```
Require-Capability: osgi.extender;filter:="(&(osgi.extender=osgi.component)(version>=1.3.0)(!(version>=2.0.0)))",osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
```
Knowing why your environment wants 9.0 would require more introspection of the configured bundles and logs.
