### ISSUE TITLE
the countBasedBackEnd class cause OOM

### ISSUE THREAD

**Issue by DiscordLzh** [ehcache/ehcache3#2719]
There is a OOM,becasue of too many countBasedBackEnd instance.  so I want to know the use of this class。 and  why they can't be gc.

**Comment by chrisdennis** [comment]
Any `Ehcache 2.x` heap cache sized with a count will have a `CountBasedBackEnd` instance backing it. I suspect you need to look at how many caches you are creating and that those caches are appropriately sized.

You might also want to think about upgrading to use Ehcache 3.
