### ISSUE TITLE
Is it possible to do cache concept with queryDSL?

### ISSUE THREAD

**Issue by RamyaAshika** [ehcache/ehcache3#2720]
Hi all,Please help me to sort out this. I'm currently working in spring boot application with spring data JPA and to retrieving the results I'm using QueryDSL and I'm trying to apply ehcache concept here.

    @CachePut(value = "ticketsearchcache", key = "#result.toString()", condition = "#result != null")
    	public Person savePerson(Person p) throws Exception {
    
    		Person test= serviceRequestRepository.save(p);
    		return test;
    	}

and to retrieve the results I'm using query dsl as well as I'm applying cacheable here.

    @Cacheable(value = "ticketsearchcache", key = "#srchCriteriaCtx.toString()")
    public List<Person> findByServiceRequestNumberAndDivisionAndDateCreated(SearchCriteriaContext srchCriteriaCtx) throws ParseException {
    
    		QServiceRequest sr = QServiceRequest.serviceRequest;
    		queryFactory = new JPAQueryFactory(em);
    		BooleanBuilder where = new BooleanBuilder();
    		List<Tuple> serReqList = new ArrayList<>();
    		OrderSpecifier<Date> specifier = sr.dateCreated.desc();
    	
    		serReqList = queryFactory
    				.select(sr.serviceRequestNumber, sr.dateCreated, sr.serialNumber, sr.trackingNumber)
    				.from(sr).leftJoin(sr.pc, pc).leftJoin(sr.printer, printer).leftJoin(sr.storeClosing, storeClosing).where(where)
    				.orderBy(specifier).fetch();
    
    		List<Person > searchResults = new ArrayList<Person >();
    
    
    		for (Tuple row : serReqList) {
    			Person result = new Person ();
    
    			result.setServiceRequestNumber(row.get(0, String.class));
    			result.setDateCreated(row.get(1, Date.class));
    			result.setSerialNumber(row.get(2, String.class));
    			result.setTrackingNumber(row.get(3, String.class));
    				searchResults.add(result);
    		
    		}
    		
    		return searchResults;
    	}

When I'm doing this, the cacheput is not at all working and in other cases it throws classcast exception cannot cast to list like this. Any suggestions will be appreciated.

**Comment by chrisdennis** [comment]
I think you'd be better off taking this to one of the spring forums. I believe they recommend asking on [stackoverflow.com](stackoverflow.com) first.
