### ISSUE TITLE
BootstrapCacheLoader replacement in Ehcache 3

### ISSUE THREAD

**Issue by panosmir** [ehcache/ehcache3#2749]
Hello,
I'm trying to migrate from EhCache 2.x to 3.x. In my 2.x configuration file, I had something this:
`<bootstrapCacheLoaderFactory
            class="net.sf.ehcache.distribution.RMIBootstrapCacheLoaderFactory"/>
`
And in Java I was using the `cache.bootstrap();`. I'm trying a replacement to replicate the above configuration, I read all the documentation but I could find anything. Is functionality completely removed from Ehcache 3.x?
Thanks in advance.

**Comment by chrisdennis** [comment]
There is no RMI replication support in Ehcache 3.x. It should be pretty simple to implement using an appropriately configured cache listener however.
