### ISSUE TITLE
Fix failing tests in Linux PR builds

### ISSUE THREAD

**Issue by saurabhagas** [ehcache/ehcache3#2758]
`BasicCacheOpsMultiThreadedTest` and `EventsFailureBehaviorTest` fail on linux PR builds. Once such instance was: https://dev.azure.com/TerracottaCI/ehcache/_build/results?buildId=4041&view=results. (The tests were ignored to be able to proceed further).

**Comment by chrisdennis** [comment]
Not sure why they were failing... but I don't think they do now.
