### ISSUE TITLE
[osgi] javax.xml.bind import incompatible with Java 8

### ISSUE THREAD

**Issue by amarkevich** [ehcache/ehcache3#2760]
Version: 3.8.1
MANIFEST.MF Import-Package: javax.xml.bind;version="[2.3,3)",javax.xml.bind.annotation;version="[2.3,3)",javax.xml.bind.annotation.adapters;version="[2.3,3)"

Avoid version range to support Java 8 [1] without additional dependencies.

1. https://github.com/apache/karaf/blob/master/assemblies/features/base/src/main/filtered-resources/resources/etc/jre.properties#L424-L429

**Comment by amarkevich** [comment]
#2761

**Comment by chrisdennis** [comment]
Fixed by #2858 - the import is now `[2.2, 3)` so the 2.2.8 exports from Java 8 will satisfy it.
