### ISSUE TITLE
How to know the result of synchronizing cache between servers?

### ISSUE THREAD

**Issue by Gannalyo** [ehcache/ehcache3#2765]
Hi!
So far, in my app, it was successful to synchronize cache between servers.

I want to make it be better....
How can I be sure the cache has been synchronized to another server successfully?

Thanks so much!

**Comment by chrisdennis** [comment]
This is either custom usage of Ehcache 3 beyond the scope of the product, or it's referring to the use of RMI (or similar) replication in Ehcache 2. Either way this doesn't seems like an Ehcache 3 issue. If I'm mistaken, please clarify and reopen this issue.
