### ISSUE TITLE
the method that most conusuming 

### ISSUE THREAD

**Issue by githubcheng2978** [ehcache/ehcache3#2773]
when I pressure the application which use the ehcache.3.2.2 . there is a problem was fund via a JVM tool  Jvisualvm .  

the screenshot is follow:
![image](https://user-images.githubusercontent.com/22095448/80793625-378f1500-8bca-11ea-8ec0-0ce9ffef0bc6.png)

there is writeLock in the code source . 

after  the cache was initalized and then  it will not be modified  .   so I don`t think necessary to wirte lock

**Comment by chrisdennis** [comment]
This is likely because you're faulting and flushing to/from the offheap store as the heap store is not big enough to hold your entire hot set. If you make the heap tier bigger you'll reduce that fault/flush rate and reduce this contention.
