### ISSUE TITLE
Implement default `CacheEventListenerFactory`

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#278]
As stated initially when the feature was implemented:

```
        // XXX this assumes a new instance returned for each call - yet args are always the same. Is this okay?
```

Obviously this isn't right like so... We need to either have the `CacheEventListenerFactory` configure all listeners at once, or pass each `CacheEventListenerConfiguration` to the service.

We need to:
 - Have a a `DefaultCacheEventListenerFactory` à la `DefaultCacheLoaderWriterFactory`
 - Solve the problem around multiple configs per Cache & what they return
 - Enable `CacheEventListener` in XML

**Comment by ljacomet** [comment]
From last public dev meeting: we will support multiple listeners through configuration

**Comment by lorban** [comment]
I added a few more remarks to PR #361. Hopefully you can sort them out, add the required commits to the PR and then get them merged in again.
