### ISSUE TITLE
Entity getting deleted when an entity is updated in cache post 3.6.3 version

### ISSUE THREAD

**Issue by Saurabh29** [ehcache/ehcache3#2784]
Hi All,

This is a very critical bug which I am facing post 3.6.3, when an entity is update in cache it removes the entity. I am able to consistently reproduce this problem for all version after 3.6.3. 

To debug this further I added listeners for REMOVED and from the log I can see that entity getting removed. To make sure that it is not because of syncronization I set <event-firing-mode>SYNCHRONOUS</event-firing-mode>. 

Please let me know if I have to enable logs to give more details.

Regards
Saurabh

**Comment by chrisdennis** [comment]
If the failure is reproducible then the best thing to do is attach a test case that show the bug. This will not only allow us to more easily understand precisely what behavior you are seeing, but also allow for easier diagnosis and fixing (if there is indeed a bug).

**Comment by Saurabh29** [comment]
Able to reproduce the problem, please let me know if what log level need to be set to share the logs.
In the mean time will try to write sample program to reproduce the issue in standalone program.

Thanks for quick response.

**Comment by Saurabh29** [comment]
Please note I saw the same issue with 3.6.3 as well when I enable the log. I can able to reproduce the problem consistently

**Comment by chrisdennis** [comment]
Without a reproducible test case, or at a minimum a configuration and a description of such a test case this stands no chance of being fixed (or being proven to be a bug). Please reopen if you can provide enough information to reproduce this independently.
