### ISSUE TITLE
How to implement web caching in ehcache2 on ehcache3

### ISSUE THREAD

**Issue by ft0907** [ehcache/ehcache3#2790]
I am using ehcache2 now, but I migrated to ehcache3 first, and encountered one of the biggest problems, that is, the web caching module does not know how to deal with it? Are there any good suggestions, thank you!
The following is the code I processed on ehcache2, obviously there is no SimplePageCachingFilter related interface method on ehcache3

```java
public class PageCachingFilter extends SimplePageCachingFilter {
    /**
     * 执行过滤器
     *
     * @param request  HttpServletRequest
     * @param response HttpServletResponse
     * @param chain    FilterChain
     */
    @Override
    protected void doFilter(HttpServletRequest request, HttpServletResponse response, FilterChain chain) throws Exception {
        if (response.isCommitted()) {
            throw new AlreadyCommittedException("Response already committed before doing buildPage.");
        }
        logRequestHeaders(request);
        PageInfo pageInfo = buildPageInfo(request, response, chain);
        if (pageInfo.isOk()) {
            if (response.isCommitted()) {
                throw new AlreadyCommittedException("Response already committed after doing buildPage" + " but before writing response from PageInfo.");
            }
            writeResponse(request, response, pageInfo);
        }
    }

}
```

**Comment by linghengqian** [comment]
- This question is a bit surprising to me because I don't understand what you're doing. 

- If you just need to cache filtered authentication information, you can simply register it with Spring Security and then take the cache out of The CacheManager of Spring Cache while processing the corresponding logic.

**Comment by ft0907** [comment]
不是缓存认证，是页面缓存，chcache2是有页面缓存的，而chcache3是没有页面缓存了，我现在是想平滑迁移，尽量不该动太大的情况下直接迁移，其他的api替换都没问题，主要是这个页面缓存有点问题。因为chcache3删除SimplePageCachingFilter这个类，如果我要想支持，就必须重新一个页面实现，或者是直接删除页面缓存逻辑！

**Comment by linghengqian** [comment]
Page caching is a strange concept for me. Because if you use a template engine like thymeleaf, its own page cache is not related to Ehcache. If it is the NodeJS side, the SPA's cache is on the middleware.😳

**Comment by chrisdennis** [comment]
Not a candidate for inclusion in the main project. This could potentially become a "recipe" in some repository of "this is how you use the product" but there are no plans for such a thing at this point.
