### ISSUE TITLE
Wrong package name: org.ehcache.clustered.common.internal.Store

### ISSUE THREAD

**Issue by AlBundy33** [ehcache/ehcache3#2796]
a least eclipse complains about the name because you're using
org.ehcache.clustered.common.internal.Store
and
org.ehcache.clustered.common.internal.store

**Comment by chrisdennis** [comment]
Sounds to me like this is an Eclipse bug. Although we could probably rename the `clustered/ehcache-common/src/test/java/org/ehcache/clustered/common/internal/Store` directory there's no reason this shouldn't work.

**Comment by AlBundy33** [comment]
maybe it's because ntfs filenames are note case-sensitive (I'm working on windows)

**Comment by AlBundy33** [comment]
net tested but I hope it's fixed
