### ISSUE TITLE
ehcache 3.8.1 - jaxb dependency issue

### ISSUE THREAD

**Issue by simpleusr** [ehcache/ehcache3#2797]
Hi,

Previously I asked the same same question in other platforms but since I could not receive an answer:

https://stackoverflow.com/questions/62774018/ehcache-3-8-1-jaxb-dependency-issue

https://groups.google.com/forum/#!category-topic/ehcache-users/ehcache-core/2maeqj4vVME

I am trying to use ehcache v3.8.1 on a bownfield project that is deployed in j2ee application server.

Maven pom.xml file for latest ehcache version (3.8.1) declares that it has a direct dependecy to jaxb:

```
<dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>2.3.1</version>
      <scope>compile</scope>
    </dependency>
```
From source code I can see that org.ehcache.xml package uses jaxb classes.

The dependency was added in 3.7.1 version. 3.7.0 version does NOT have this dependency but it still has the org.ehcache.xml package that uses jaxb classes. I guess this addition was done after removal of jaxb modules from the JDK as part of JEP 320 (http://openjdk.java.net/jeps/320)

My question: Do I really have to include org.glassfish.jaxb->jaxb-runtime and its transitive dependencies in the application server classpath?

I think loading jaxb artifacts from app server classpath should suffice, but I could not be sure.

PS: Currently I could manage to use ehcache by just including ehcache-3.8.1.jar in application server classpath but I am using pogrammaic configuration and I am wondering if problems will occur if I switch to xml configuration.

Regards

**Comment by chrisdennis** [comment]
This is to make sure everything works properly in Java9+ JVMs where JAXB is no longer a part of the JVM (by default). As long as there is a JAXB implementation on the classpath then you're fine.
