### ISSUE TITLE
Illegal reflective access by org.ehcache.sizeof.ObjectGraphWalker

### ISSUE THREAD

**Issue by nikowitt** [ehcache/ehcache3#2800]
Hi there,
while using ehcache 3.8.1, with Java 11, the following warning occurs:
   [junit] WARNING: Illegal reflective access by org.ehcache.sizeof.ObjectGraphWalker (file:/home/jenkins2/workspace/...)/trunk/WebContent/WEB-INF/lib/ehcache-3.8.1.jar) to field java.lang.String.value

Regards,
Niko

**Comment by chrisdennis** [comment]
The `ObjectGraphWalker` by necessity uses reflection to walk and size the object graph. You can silence these warnings by opening the various modules/packages to Ehcache in JPMS or you can stop using byte based sizing. For now those are the only practical solutions.
