### ISSUE TITLE
Closing a persistent cache manager leaks a file descriptor

### ISSUE THREAD

**Issue by mark-christiaens** [ehcache/ehcache3#2808]
Using this test application:
```
import org.ehcache.Cache;
import org.ehcache.CachePersistenceException;
import org.ehcache.PersistentCacheManager;
import org.ehcache.config.builders.CacheConfigurationBuilder;
import org.ehcache.config.builders.CacheManagerBuilder;
import org.ehcache.config.builders.ExpiryPolicyBuilder;
import org.ehcache.config.builders.ResourcePoolsBuilder;
import org.ehcache.config.units.EntryUnit;
import org.ehcache.config.units.MemoryUnit;

import java.io.File;

public class Main {
    public static void main(String[] args) throws CachePersistenceException {
        PersistentCacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
                .with(CacheManagerBuilder
                        .persistence(new File("/tmp/ehcache_test")))
                .withCache("my_cache",
                        CacheConfigurationBuilder
                                .newCacheConfigurationBuilder(String.class, String.class,
                                        ResourcePoolsBuilder.newResourcePoolsBuilder()
                                                .heap(10, EntryUnit.ENTRIES)
                                                .disk(32, MemoryUnit.KB, true)) // Ehcache minimal needs
                                .withExpiry(ExpiryPolicyBuilder.noExpiration()))
                .build(true);

        Cache<String, String> cache = cacheManager.getCache("my_cache", String.class, String.class);

        cache.put("my_key", "my_value");

        String actual_value = cache.get("my_key");

        if (!actual_value.equals("my_value")) {
            System.err.println("Wrong actual value: " + actual_value);
            System.exit(-1);
        }

        cacheManager.close();
        cacheManager.destroy();

        System.out.println("Closed everything: done");
    }
}
```
I run this in a debugger and put a breakpoint on the final line (the `System.out ...`).  While the process is suspended in this breakpoint, I list the file descriptors that the process has in use.  I see that one file descriptor for the cache is still open.    It seems that `destroy` does not close all file descriptors.

**Comment by chrisdennis** [comment]
I would be good to get a heap dump of the JVM when in this state to confirm. I'm pretty confident however that what you're seeing is a un-GC'ed (but unreachable) MappedByteBuffer. Until the JVM GC's the heap it's not practical to clear these.

**Comment by mark-christiaens** [comment]
I modified the test by adding an explicit GC call:

```
...
        cacheManager.close();
        cacheManager.destroy();

        System.gc();

        System.out.println("Closed everything: done");
...
```
I put my breakpoint at the `System.out`.  Linux still claims there's an open file (that is deleted by the `destroy` call):
```
lsof -p 31097 | grep my_cache
java    31097 mchristi  DEL    REG               0,38             859531 /tmp/ehcache_test/file/my_cache_fa0f3c6d3242cb1f02e8ea878be8b47996b0b8f8/offheap-disk-store/ehcache-disk-store.data
```
I took a heap dump at this point:

[dump.hprof.gz](https://github.com/ehcache/ehcache3/files/4982709/dump.hprof.gz)

**Comment by mark-christiaens** [comment]
I suspect this is the stack trace where the file is allocated:
```
java.io.RandomAccessFile.open(String, int) RandomAccessFile.java
java.io.RandomAccessFile.<init>(File, String) RandomAccessFile.java:243
org.ehcache.impl.persistence.DefaultLocalPersistenceService.internalStart() DefaultLocalPersistenceService.java:87
org.ehcache.impl.persistence.DefaultLocalPersistenceService.start(ServiceProvider) DefaultLocalPersistenceService.java:75
org.ehcache.core.spi.ServiceLocator.startAllServices() ServiceLocator.java:128
org.ehcache.core.EhcacheManager.init() EhcacheManager.java:577
org.ehcache.config.builders.CacheManagerBuilder.build(boolean) CacheManagerBuilder.java:75
```

**Comment by chrisdennis** [comment]
The trace you reference is the lock file... 100% it's not that. I still think my first instinct is right... that this a remnant memory mapped file. The `DEL` in the FD descriptor in the `lsof` output indicates that this is for a memory mapped file that has been deleted. I suspect it's not in the heap dump because you've only included reachables... when what we want is everything in the dump including objects that are not reachable or not yet GC'ed. I also suspect that if you pull the VM to a safepoint with the debugger immediately after calling System.gc() you may also interfere with the freeing of these buffers. I would try the following: System.gc() in a loop with a 2 second sleep in between, and then a `watch lsof -p <pid>` in another shell. If the file descriptor stays open then we may still have a problem. In that case grab a heap dump from the running JVM that includes unreachable objects.

**Comment by mark-christiaens** [comment]
I've changed the test to perform the GC in a loop as you suggested and indeed, the file descriptor disappears.  

The reason why I'm investigating this is that we have a unit test that creates a cache and afterwards needs to remove the cache (by wiping the entire folder of the cache).  This fails on Windows because a file is in use.  Do you know of an elegant way to remove the entire folder without resorting to repeatedly GC-ing?

**Comment by chrisdennis** [comment]
Generally I would encourage you to avoid reusing the same path, but if thats is unavoidable or unworkable then rhere is a utility now used in Ehcache (but not in a released version) that handles this: https://github.com/Terracotta-OSS/terracotta-utilities/blob/master/tools/src/main/java/org/terracotta/utilities/io/Files.java

It works by renaming the file/directory and then attempting to delete it. If the delete of the renamed files fails it hands the delete off to a background worker to delete the file at a later date. The rename will still guarantee that the path is available for reuse though, so it 'looks' like the delete works immediately either way. Available from maven central as: `org.terracotta:terracotta-utilities-tools:0.0.5`

**Comment by mark-christiaens** [comment]
Thanks for all the suggestions!
