### ISSUE TITLE
Is ehcache 3.9 ready for production use?

### ISSUE THREAD

**Issue by moonfruit** [ehcache/ehcache3#2834]
I have noticed that Ehcache 3.9 was already released and was deployed to maven central.
But I cannot found a release note for it, and even there is nothing about 3.9 on [the Ehcache website](https://www.ehcache.org/).
So I am wondering if Ehcache 3.9 is ready for production use?

**Comment by chrisdennis** [comment]
3.9.0 is in the process of being released. Due to other commitments I wasn't able to finish the release process very promptly and so a lot of the ancilliary tasks have been left for later. The tag and maven central release are final though and as safe to use as any other x.y.0 release.

**Comment by moonfruit** [comment]
Thank you!
