### ISSUE TITLE
Support Request: Caching Strings is slower than Caching Objects

### ISSUE THREAD

**Issue by concon121** [ehcache/ehcache3#2844]
While working on optimizing the performance of a service, it was suggested we could try caching the string representations of objects, rather than the objects themselves as we end up serving back the JSON String format anyway.

Upon testing this theory, I've found that performance degrades by a significant amount when getting back from the cache.  

String implementation:
```
"averagePutTime": 102.0652,
"averageGetTime": 17.502258,
```

Object implementation:
```
"averagePutTime": 3051.6936,
"averageGetTime": 6.2924027,
```

As you can see from these metrics, the put time is massively faster with the string, but the get time is around 3 times slower.  

I've gone through heap dumps and gc logs and nothing seems to be amiss.  Is there any reasonable explanation for why this might be?

**Comment by chrisdennis** [comment]
Do you have the cache configuration and Ehcache version you are using?

**Comment by concon121** [comment]
EhCache version 3.8.1

We're using JCache via annotations

Very little configuration being set, mostly just rely on default settings.  What we have set is below:

Expiry Policy: Eternal
Management: Enabled
Statistics: Enabled

For the string implementation:

store by value: false

as this showed to improve response time.

**Comment by chrisdennis** [comment]
Apologies for the long delay. The performance difference here is likely related to the cost of serializing the Objects (which is somehow more expensive than calculating the toString()). If you can share the object implementation then I could probably figure out what that is. Reopen this if you want me to take a look.
