### ISSUE TITLE
EhcacheCachingProvider.getCacheManager inconsistent logic

### ISSUE THREAD

**Issue by cdalexndr** [ehcache/ehcache3#2852]
Calling `EhcacheCachingProvider.getCacheManager` with `Configuration` parameter has different logic depending if cache manager already exists:

- if cache manager doesn't exist, create it and create associated caches from provided configuration
- if cache manager already exists, return it

In case when cache manager already exists, **no new caches** are created from configuration.
This method should have same logic, regardless of cache manager existance.

Use case:
Testing hibernate second level cache creates a cache manager with hibernate specific caches.
After that, testing application cache with custom configuration **doesn't create** the required caches because the cache manager already was created. Thus, **null** caches are returned when requested, causing **NullPointerException**.

**Comment by chrisdennis** [comment]
The CacheManager configuration is a single atomic unit. If the CacheManager does not exist then it is created, along with every Cache that the passed configuration defines. If the CacheManager does exist then there is no use for the configuration object. If we implemented this in any other way you'd run in to all sorts of issues when trying to merge the manager level elements of one configuration with the cache level elements on another. That could never be made to work properly.

The CacheManagers are keyed by ClassLoader and then by URI. If you pass the same class loader and URI it will return the same CacheManager.

The Javadoc in this area is definitely a little sparse, and most of the behavior has to be inferred by reading the Javadoc of the overloaded methods. I'll leave this issue open to track the fixing of that Javadoc.
