### ISSUE TITLE
How many times do I use ehcache data?

### ISSUE THREAD

**Issue by taagholi** [ehcache/ehcache3#2853]
Greetings
I want to know how much ehcache was used during the execution of my program, that is, every time I call `session.get` and the data comes from ehcache, I want to print it in the log console or something.
I got acquainted with CacheEventListener during my search, but this interface does not notice me when loading and only when push / expire / eviction.

**Comment by chrisdennis** [comment]
There just isn't enough demand for a get listener to justify the performance overhead of logging on every get. This should however be trivial to implement in a wrapper around the caches.
