### ISSUE TITLE
Upgrading ehcache-web

### ISSUE THREAD

**Issue by AbstractAlao** [ehcache/ehcache3#2855]
I've noticed that the dependency ehcache-web is no longer included in the new version of Ecache.  What would be the correct way of upgrading if the application is dependent on  SimplePageCachingFilter.  Should we implement out own version of this class?

**Comment by chrisdennis** [comment]
Yes there is no equivalent to ehcache-web for Ehcache 3. You will need to implement your own version. I would recommend if doing this that you consider coding if possible against the `javax.cache` (JSR-107) API to provide maximum flexibility.
