### ISSUE TITLE
How to get the cache name in CacheEventListener?

### ISSUE THREAD

**Issue by sunyitao** [ehcache/ehcache3#2865]
In practice, you need to add different listeners according to the different names of the configured cache.
But the CacheEventListener interface does not get the cache name, unfortunately did not find other ways!!!

Through CacheRuntimeConfiguration only registerCacheEventListener and deregisterCacheEventListener methods, there is no method to query the existing listener, resulting in frequent and repeated registration exceptions.

Please give a solution!!!🙏

**Comment by chrisdennis** [comment]
The issue tracker isn't for support questions but for the filing of bugs. The documentation for cache event listeners can be found here: https://www.ehcache.org/documentation/3.8/cache-event-listeners.html

I would suggest that if you find yourself needing to know the alias for a cache in a listener (caches don't have names) then you're probably doing something wrong. Instead just have distinct listener instances for each cache.

As for registration exceptions: those should only happen if you are trying to register the same listener twice (as judged by `Object.equals(...)`).
