### ISSUE TITLE
Getting Duplicate identity constraint name in Ehcache3.8.1 with XML Configuration

### ISSUE THREAD

**Issue by santhoshpt** [ehcache/ehcache3#2866]
I'm getting below exception with ehcache 3.8.1 with XML Configuration file (the application is an EAR deployed to weblogic server). Did anyone faced this issues? When debugged the code in ehcache, I could find that getting three XML schema in below code snipped of ConfigurationParser.java and failing with duplicate. Is I'm doing any wrong?

```
 public static Schema discoverSchema(Source ... fixedSources) throws SAXException, IOException {
    ArrayList<Source> schemaSources = new ArrayList<>(asList(fixedSources));
    for (CacheManagerServiceConfigurationParser<?> p : servicesOfType(CacheManagerServiceConfigurationParser.class)) {
      schemaSources.add(p.getXmlSchema());
    }
    for (CacheServiceConfigurationParser<?> p : servicesOfType(CacheServiceConfigurationParser.class)) {
      schemaSources.add(p.getXmlSchema());
    }
    for (CacheResourceConfigurationParser p : servicesOfType(CacheResourceConfigurationParser.class)) {
      schemaSources.add(p.getXmlSchema());
    }
    return newSchema(schemaSources.toArray(new Source[0]));
  }
```
Getting the following exception

```
Error on line 28
  Duplicate identity constraint name {default-template-ref} - previously defined on line 28 of
Error on line 37
  Duplicate identity constraint name {template-ref} - previously defined on line 37 of
org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:/D:/*********/UIM/config/ehcache3.xml
        at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:124) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
        at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:90) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
```

The code is as follows:
```
URL url = getClass().getResource("/"+configFileName);
Configuration xmlConfig = new XmlConfiguration(url);
admin = CacheManagerBuilder.newCacheManager(xmlConfig);
admin.init();
```

The xml configuration is as follows:
```
<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xmlns:tc='http://www.ehcache.org/v3/clustered'
    xmlns="http://www.ehcache.org/v3"
	xsi:schemaLocation="
            http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core.xsd
			http://www.ehcache.org/v3/clustered http://www.ehcache.org/schema/ehcache-clustered-ext.xsd">
			
  <service>
    <tc:cluster>
      <tc:connection url="terracotta://localhost:9410/clustered"/>
      <tc:server-side-config auto-create="true">
        <tc:default-resource from="default-resource"/>
      </tc:server-side-config>
    </tc:cluster>  
  </service>  
   
  <cache-template name="myDefaults"> 
    <key-type>java.lang.String</key-type>
    <value-type>java.io.Serializable</value-type>
    <heap unit="entries">1000</heap>
  </cache-template>
  
  <cache alias="frameworkCache">
    <key-type>java.lang.String</key-type>
    <value-type>java.io.Serializable</value-type>
    <resources>
      <tc:clustered-dedicated unit="MB">5</tc:clustered-dedicated>
	</resources>
  </cache>
  
  <cache alias="isolatedCache">
   <key-type>java.lang.String</key-type>
   <value-type>java.io.Serializable</value-type>
   <resources>
   	  <heap unit="MB">10</heap>
	</resources>
  </cache>
  
  <cache alias="default" uses-template="myDefaults" >
    <key-type>java.lang.String</key-type>
    <value-type>java.io.Serializable</value-type>
    <resources>
      <tc:clustered-dedicated unit="MB">5</tc:clustered-dedicated>
	</resources>
  </cache>

</config>
```

**Comment by santhoshpt** [comment]
I found XMLSchemaFactory class instances as different when invoke the code independently (standalone app with JDK8) and as application in weblogic.  Is the ehcache 3.8.1 supported in weblogic?

`In standalone application the instance is com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory@dd0c991`

`In weblogic application the instance is com.saxonica.jaxp.SchemaFactoryImpl@73364cb3`

**Comment by santhoshpt** [comment]
I have removing the following entries from the ehcache 3.8.1 atleast the xml file is read.  Not sure whether we need this for core ehcache functionlaity. 
META-INF/services/org.ehcache.xml.CacheServiceConfigurationParser
META-INF/services/org.ehcache.xml.CacheManagerServiceConfigurationParser

**Comment by chrisdennis** [comment]
The errors indicate that Ehcache is somehow discovering multiple copies of the JSR-107 extension on the classpath. Could you tell me what ehcache jars you are using in your application and where you are loading them from (mainly the EAR itself versus the common container classpath)?

**Comment by santhoshpt** [comment]
The application structure is listed below which has shared libraries.  The ehcache will be loaded in UX code in application.ear by using the shared library code.  **The same was working fine with ehcache-2.10.6.jar and got the issue when upgraded the ehcache to 3.x**.  

APPLICATION.EAR
  -- UX
  -- REST 
  -- EJBS
  -- shared_library_internal.ear (Contain internal libraries)
      -- entities.jar
      -- tools.jar
      -- framework.jar (which has logic to configure the ehcache cache)
  -- shared_library_external.ear (Listed some significant external libraries)
      -- slf4j-api-1.7.29.jar
      -- saxon9ee.jar
      -- log4j-slf4j-impl-2.9.1.jar
      -- log4j-core-2.9.1.jar
      -- log4j-api-2.9.1.jar
      -- ehcache-3.8.1.jar

The following will be in weblogic startup classpath
weblogic.jar, webservices.jar and wlclient.jar;

**Comment by santhoshpt** [comment]
Hi Chris,

Did you get any clue about the issue after looking above application hierarchy? 

I have another question: To setup the ehcache with cluster do I need to include the ehcache-3.8.1.jar and ehcache-clustered-3.8.1.jar files into the application classpath?

**Comment by santhoshpt** [comment]
@chrisdennis could you please let me know whether I'm doing any working in xml configuration.  If I use the configuration as above, I'm able to use the ehcache3 with terracotta.  I need the xml configuration so that it can be configured without modifications to the code.

**Comment by santhoshpt** [comment]
My application is saxon9ee.jar for xml.  Is the ehcache 3.x is tested or supported with saxon parser?  

I'm able to reproduce the issue in standalone setup by including the saxon9ee.jar in classpath in eclipse java project.  I'm getting the following exception :
`Error on line 552 
  Error in complex type resources-type: Ambiguous content model, element
  <Q{.../clustered}clustered> appears more than once
Exception in thread "main" org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:******************ehcache3.xml
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:124)
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:90)
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:76)
	at inventory.LoadEhcache.load(LoadEhcache.java:17)
	at inventory.LoadEhcache.main(LoadEhcache.java:27)
Caused by: org.xml.sax.SAXException: Ambiguous content model, element <Q{.../clustered}clustered> appears more than once
net.sf.saxon.type.SchemaException: Ambiguous content model, element <Q{.../clustered}clustered> appears more than once
	at com.saxonica.jaxp.SchemaFactoryImpl.newSchema(SchemaFactoryImpl.java:218)
	at org.ehcache.xml.ConfigurationParser.newSchema(ConfigurationParser.java:114)
	at org.ehcache.xml.ConfigurationParser.discoverSchema(ConfigurationParser.java:460)
	at org.ehcache.xml.ConfigurationParser.<init>(ConfigurationParser.java:173)
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:114)
	... 4 more`

**Comment by chrisdennis** [comment]
I think this is just a different symptom of the same problem... somehow the schemas are being discovered twice - this strongly hints at a classloading issue. Could you run your reproducer again but with `-verbose:class` turned on?

**Comment by chrisdennis** [comment]
Okay... scratch everything I said. I think I know what this is and am preparing a fix. I think is Saxon handling being passed duplicate schema files differently to the way Xerces (the JDK builtin) does. I haven't had a chance to test the theory myself yet... but I believe my employer has a license for Saxon so I'll try to prove it out.

**Comment by santhoshpt** [comment]
Thanks  @chrisdennis .  Let me know if you need the license.  I have acquired one month trail license for testing.

**Comment by chrisdennis** [comment]
Not sure how this managed to not get closed... this was fixed under https://github.com/ehcache/ehcache3/pull/2871

**Comment by chrisdennis** [comment]
This should end up in the next 3.9.x line release, can't give a firm date on that yet though.

**Comment by pranneetth** [comment]
> This should end up in the next 3.9.x line release, can't give a firm date on that yet though.

Okay, thanks for the update! Looking forward to next 3.9 release.
