### ISSUE TITLE
http://ehcache.org is down

### ISSUE THREAD

**Issue by haqer1** [ehcache/ehcache3#2875]
It's been down since at least February 8th, 2021 (i.e., 3 days as of today). This makes it harder to find the documentation during development.

**Comment by chrisdennis** [comment]
It's working for me, and for others: https://downforeveryoneorjustme.com/ehcache.org

**Comment by haqer1** [comment]
Strange: this is the only site that's down for me. I'll ping my ISP...
If your site is doing anything cutting-edge, i'd appreciate if you let me know.
![Ekran Körüntisi - 2021-02-10](https://user-images.githubusercontent.com/23289745/107604511-82aa7e00-6c5a-11eb-80de-7e687d41fa93.png)

**Comment by haqer1** [comment]
FYI: the issue on this end has been resolved.
