### ISSUE TITLE
With XML-based config the cache cannot be restarted with previous mappings

### ISSUE THREAD

**Issue by haqer1** [ehcache/ehcache3#2876]
whereas with Java-API-based config, it can be restarted with previous mappings.

**Comment by haqer1** [comment]
I think it would be a good idea to fix this. To reproduce the issue, feel free to use the parameterized JUnit test from PR #2877.

**Comment by chrisdennis** [comment]
You need to set the disk resource to be persistent: `<disk persistent='true' unit='MB'>1024</disk>`

**Comment by haqer1** [comment]
Good to know. Thanks.
