### ISSUE TITLE
About PlainJavaSerializer.class serialization performance

### ISSUE THREAD

**Issue by dylan-tao** [ehcache/ehcache3#2890]
Class：org.ehcache.impl.serialization.PlainJavaSerializer，the performance of default serialization is a little poor. Is there a better serialization recommendation, thanks !

**Comment by chrisdennis** [comment]
The default serialization implementation used by Ehcache is the `CompactJavaSerializer` this uses default Java serialization but with out-of-band object stream class descriptors. This makes it more space efficient than regular serialization but the same from a latency/speed point of view. If you want something faster I would encourage you to look at adopting an alternative serialization mechanism of your choice by implementing the Serializer interface. JSON, BSON. Kryo, Protocol Buffers are probably all good choice depending on your needs.

**Comment by dylan-tao** [comment]
thank you ~
