### ISSUE TITLE
DependencyException

### ISSUE THREAD

**Issue by Tarnumx** [ehcache/ehcache3#2891]
Hello,

I'm trying to use ehcache 3.9.2 in standalone java application. When I run my app from intellij idea it works fine. When I assemble it then it throws exception. Code is pretty simple:

        try {
            CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder().build();
            cacheManager.init();
        } catch (Exception ex) {
            loger.logMessage(ex.toString(), BasicLoging.LOG_LEVEL_INFO);
        }

The exception is:
`java.lang.IllegalStateException: org.ehcache.core.spi.ServiceLocator$DependencyException: Failed to find provider with satisfied dependency set for interface org.ehcache.core.events.CacheEventDispatcherFactory [candidates []]`

I'm using maven and trying different plugins. Nothing changes. All information I found in all issues was about jar assembling that META-INF/services might be munged. 
Here is list of org.ehcache.core.spi.service.ServiceFactory file:

> org.ehcache.impl.internal.store.heap.OnHeapStoreProviderFactory
org.ehcache.impl.internal.store.offheap.OffHeapStoreProviderFactory
org.ehcache.impl.internal.store.disk.OffHeapDiskStoreProviderFactory
org.ehcache.impl.internal.store.tiering.TieredStoreProviderFactory
org.ehcache.impl.internal.store.tiering.CompoundCachingTierProviderFactory
org.ehcache.impl.internal.store.loaderwriter.LoaderWriterStoreProviderFactory
org.ehcache.impl.internal.TimeSourceServiceFactory
org.ehcache.impl.internal.spi.serialization.DefaultSerializationProviderFactory
org.ehcache.impl.internal.spi.loaderwriter.DefaultCacheLoaderWriterProviderFactory
org.ehcache.impl.internal.spi.event.DefaultCacheEventListenerProviderFactory
org.ehcache.impl.internal.executor.DefaultExecutionServiceFactory
org.ehcache.impl.internal.persistence.DefaultLocalPersistenceServiceFactory
org.ehcache.impl.internal.persistence.DefaultDiskResourceServiceFactory
org.ehcache.impl.internal.loaderwriter.writebehind.WriteBehindProviderFactory
org.ehcache.impl.internal.events.CacheEventNotificationListenerServiceProviderFactory
org.ehcache.impl.internal.spi.copy.DefaultCopyProviderFactory
org.ehcache.impl.internal.sizeof.DefaultSizeOfEngineProviderFactory
org.ehcache.impl.internal.spi.resilience.DefaultResilienceStrategyProviderFactory
org.ehcache.core.internal.statistics.DefaultStatisticsServiceFactory

Why doesn't it contain needed candidate? Where can I start searching the solution?

Thanks a lot.

**Comment by chrisdennis** [comment]
Sorry, I got a bit behind on some of these issues. It should be finding: `CacheEventNotificationListenerServiceProviderFactory` which appears like it should be there. I think the best next step here would be to try calling:
```java
org.ehcache.core.util.ClassLoading.servicesOfType(org.ehcache.core.spi.service.ServiceFactory.class)
```
and then dumping the output in both environments. You should see an identical list of types, if you don't then hopefully the diff between the two should hint at whats going wrong.
