### ISSUE TITLE
What is the current (stable) release?

### ISSUE THREAD

**Issue by Brummolix** [ehcache/ehcache3#2900]
On https://www.ehcache.org/ it says "Ehcache 3.8 is now available!" and the getting-started-example mentions 3.8.1.
On https://github.com/ehcache/ehcache3/releases it says 3.8.1 is the "Latest release"
On https://mvnrepository.com/artifact/org.ehcache/ehcache there are several 3.9 releases up to 3.9.3
On https://github.com/ehcache/ehcache3 it says "We released 3.9.0... The release notes contain the links to the artifacts and the documentation to help you get started. You should consider upgrading to 3.9.x as it does all previous 3.x do and more with a fully compatible API." The "release notes" link points to https://github.com/ehcache/ehcache3/releases/tag/v3.9.0 (the 3.9.0 tag).

Maybe you can imagine that this is a bit confusing.
What is the current recommended stable release? Is it 3.8.1? 3.9.0? 3.9.3?

**Comment by chrisdennis** [comment]
Right now I’m the only person doing significant work on the release side of things and I’ll admit that I’ve got behind on doing the ancillary work around releases (like updating the website). If you’re using unclustered caching only then there really isn’t much difference between all of those releases. If you’re using Terracotta clustered caching then there is significant difference between the operational aspects of running a cluster in 3.8.x and 3.9.x. I would recommend switching to the 3.9.x line eventually, but expect some disruption when you do and plan accordingly.
