### ISSUE TITLE
Performance degradation with jsr107 statistics

### ISSUE THREAD

**Issue by manuhode** [ehcache/ehcache3#2902]
I use JavaMelody to get statistics from ehcache.
JavaMelody periodically calls the default caching provider to get the list of cache names.
Each time, a new Eh107CacheStatisticsMXBean is created for each cache, adding new LatencyMonitor on operation statistics.
After some hours, performance on get or put operation is significantly degraded.
This is due to Eh107CacheManager.refreshAllCaches() line 92 : 
`  
caches.putIfAbsent(name, wrapEhcacheCache(name, config));
`
Replacing with : 
`  
caches.computeIfAbsent(name, k -> wrapEhcacheCache(name, config));
`
solves the problem

**Comment by chrisdennis** [comment]
I believe this was fixed under #2996.
