### ISSUE TITLE
Why ehcache deadlock?

### ISSUE THREAD

**Issue by yanhua0** [ehcache/ehcache3#2904]
I find that a large amount of threads are waiting for a thread lock, and this thread deadlock on ehcache。

part of stack is:
java.lang.Object.wait(Native Method)
java.lang.Object.wait(Object.java:485)
net.sf.ehcache.util.concurrent.ConcurrentHashMap$Node.tryAwaitLock(ConcurrentHashMap.java:687)
net.sf.ehcache.util.concurrent.ConcurrentHashMap.internalClear(ConcurrentHashMap.java:2016)
net.sf.ehcache.util.concurrent.ConcurrentHashMap.clear(ConcurrentHashMap.java:2680)
net.sf.ehcache.store.cachingtier.OnHeapCachingTier.clear(OnHeapCachingTier.java:213)
net.sf.ehcache.store.CacheStore.removeAll(CacheStore.java:250)
net.sf.ehcache.Cache.removeAll(Cache.java:2451)
net.sf.ehcache.Cache.removeAll(Cache.java:2436)
org.springframework.cache.ehcache.EhCacheCache.clear(EhCacheCache.java:74)
org.springframework.cache.interceptor.CacheAspectSupport.inspectCacheEvicts(CacheAspectSupport.java:243)
org.springframework.cache.interceptor.CacheAspectSupport.inspectAfterCacheEvicts(CacheAspectSupport.java:227)
org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:212)
org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:66)

**Comment by chrisdennis** [comment]
Please direct usage and support questions to the Ehcache users mailing list: https://groups.google.com/g/ehcache-users (ehcache-users@googlegroups.com). When asking there you will need to provide at a minimum the version of Ehcache you are using and a full set of stack traces.
