### ISSUE TITLE
Empty sources artifact on maven central for versions 3.9.x

### ISSUE THREAD

**Issue by mleguevel** [ehcache/ehcache3#2912]
Hello,

I noticed that since the version 3.9.0, the sources artifact published to maven central is empty: it only contains the META-INF folder. Example [here for the version 3.9.0](https://repo1.maven.org/maven2/org/ehcache/ehcache/3.9.0/ehcache-3.9.0-sources.jar) compared to [here for the version 3.8.1](https://repo1.maven.org/maven2/org/ehcache/ehcache/3.8.1/ehcache-3.8.1-sources.jar).

I was wondering if it was intentional or if it was by mistake?

Thank you.

**Comment by chrisdennis** [comment]
By mistake... I probably broke something during a Gradle upgrade. Bisecting the build at the moment to find the source of the regression.

**Comment by chrisdennis** [comment]
Bisect reports: 170893930723114ac3dcf0d5050b529a3a5d91bc as the faulty commit.
