### ISSUE TITLE
Ehcache + Terracotta server does not work with anything other than host="localhost"

### ISSUE THREAD

**Issue by VikramVasudevan** [ehcache/ehcache3#2924]
I have researched enough about this issue but getting nowhere. Hoping you can help.

In the tc-config.xml, if I give anything other than host="localhost" for the server tag (like for e.g. host="my_public_ip_address_here" ), it fails with the following error:

 ERROR - Unable to find local network interface for [my_public_ip_address_here]

How do I start a terracotta server so I can access from another remote machine?

**Comment by myronkscott** [comment]
are you using ehcache2 or ehcache3?   I ask because configuring the server for ehcache3 is markedly different from ehcache2 and typically doesn't use a tc-config.xml

**Comment by jhouserizer** [comment]
No update with more info/clarification in months.
