### ISSUE TITLE
Max Object Graph Size reached for the object

### ISSUE THREAD

**Issue by liduanwen** [ehcache/ehcache3#2935]
Hello, I used ehcache in the project development process. I configured 300MB in the XML file, but the warning Max object graph size reached for the object occurred in the actual test environment, but no specific error was reported. Is this because the upper limit is reached? If so, will the default expulsion strategy be triggered? Please help me answer it. Thank you

**Comment by chrisdennis** [comment]
I would suggest that you resubmit this support request to the https://groups.google.com/g/ehcache-users mailing list along with a copy of your full XML configuration, specific Ehcache version, and the logging lines that are concerning you.
