### ISSUE TITLE
Out of heap serialization and deserialization problems

### ISSUE THREAD

**Issue by duanwenL** [ehcache/ehcache3#2947]
Hello, the current usage of cache is that we cache tens of thousands of pieces of data first and then out of the heap. When the user accesses, we load the data, which will involve the problem of deserialization. We use kyro, but the function test is no problem. When we use the pressure test tool for pressure test, 20qps can't support it. I want to ask how to solve it. Thank you

**Comment by chrisdennis** [comment]
GitHub issues should only be used for product bugs and/or feature requests, not for general support issues. You are much more likely to get help with this support issue if you use the ehcache-users google group: https://groups.google.com/g/ehcache-users
You will also need to provide much more information about the workload: (access patterns, configurations, etc.); the environment: JDK, virtualization, hardware, etc.; and what performance or support means in terms of hard metrics, and how they are currently being breached.
