### ISSUE TITLE
ehcache-clustering-kit v3.9.6: Failed to add timeToIdleExpiration and timeToLiveExpiration 

### ISSUE THREAD

**Issue by richardmuucyi** [ehcache/ehcache3#2966]
It will only take effect of the last withExpiry.

CacheConfigurationBuilder.newCacheConfigurationBuilder(String.class, clazz,
                        ResourcePoolsBuilder.newResourcePoolsBuilder()
                                .heap(4, MemoryUnit.MB)
                                .with(ClusteredResourcePoolBuilder.clusteredDedicated(SERVER_RESOURCE_NAME, 8, MemoryUnit.MB)))
                .withExpiry(ExpiryPolicyBuilder.timeToIdleExpiration(Duration.ofSeconds(2)))
                .withExpiry(ExpiryPolicyBuilder.timeToLiveExpiration(Duration.ofSeconds(10)))
                .withService(ClusteredStoreConfigurationBuilder.withConsistency(Consistency.STRONG))
                .build();

**Comment by chrisdennis** [comment]
Ehcache 3 does not support both TTL and TTI at the same time. In fact Ehcache 3 consider TTI informally deprecated: #1097
