### ISSUE TITLE
java.lang.reflect.InaccessibleObjectException with java 17 and Hibernate second level cache

### ISSUE THREAD

**Issue by z27chenn** [ehcache/ehcache3#2987]
I'm getting the following Warning messages when trying to use ehcache as a second level cache for hibernate 

`WARN  2022-01-27 11:31:55,737 org.ehcache.sizeof.ObjectGraphWalker                                    : The JVM is preventing Ehcache from accessing the subgraph beneath 'private final byte[] java.lang.String.value' - cache sizes may be underestimated as a result 
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @3e11f9e9`

Here is my spring config : 
`spring.jpa.properties.hibernate.cache.use_second_level_cache=true`
`spring.jpa.properties.hibernate.cache.use_query_cache=true`
`spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory`
`spring.jpa.properties.hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider`

It seems that "deep reflection" is not allowed anymore since java 16.

**Comment by chrisdennis** [comment]
Correct... you will either need to open the necessary modules to allow the reflection or switch to using count based heap tier sizes (thus avoiding any need to size objects).
