### ISSUE TITLE
ehcache 3.10.0 build fails with maven 3.8.5

### ISSUE THREAD

**Issue by 4soft-liebig** [ehcache/ehcache3#3028]
Hi,

I'm trying to use ehcache version 3.10.0 with maven 3.8.5 in a Java project. According to the maven release-notes (see https://maven.apache.org/docs/3.8.1/release-notes.html), repositories that use http (not https) are blocked by default, since they match a default mirror.

We used previously version 3.9.9, which worked out of the box. Find the maven error attached ([maven_error.txt](https://github.com/ehcache/ehcache3/files/8669427/maven_error.txt)).

What can I do?

Best regards
Jörg Liebig

**Comment by linghengqian** [comment]
I don't understand. Your network can't access Maven Central? This warehouse has no geographical limitations.

**Comment by 4soft-liebig** [comment]
Hi,

thanks for the fast response.

Our network can access maven central. The relevant part of the maven error is:
`Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Blocked mirror for repositories: [releases.java.net (http://maven.java.net/content/repositories/releases/, default, releases+snapshots), shapshots.java.net (http://maven.java.net/content/repositories/snapshots/, default, releases+snapshots), jvnet-nexus-staging (http://maven.java.net/content/repositories/staging/, default, releases+snapshots), netbeans (http://bits.netbeans.org/nexus/content/groups/netbeans, default, releases)]`

This is caused by maven's standard configuration in `/conf/settings.xml`:
```
    <mirror>
      <id>maven-default-http-blocker</id>
      <mirrorOf>external:http:*</mirrorOf>
      <name>Pseudo repository to mirror external repositories initially using HTTP.</name>
      <url>http://0.0.0.0/</url>
      <blocked>true</blocked>
    </mirror>
```

When we use ehcache version 3.9.9 the maven build succeeds. If we use version 3.10.0 it fails. Looking further in the problem. The depdency chain is: `org.ehcache:ehcache:jar:3.10.0 -> org.glassfish.jaxb:jaxb-runtime:jar:2.4.0-b180725.0644 -> com.sun.istack:istack-commons-runtime:jar:3.0.6`. As far as I can see istack-commons-runtime:jar:3.0.6 is not on maven-central (see https://search.maven.org/artifact/com.sun.istack/istack-commons-runtime).

What can we do?

**Comment by linghengqian** [comment]
- This is a very strange phenomenon. I have never seen such a log after using ehcache 3.10.0. Both ./mvnw and mvn commands are displayed on my gitlab-ci. 

- Also, why is your org.glassfish.jaxb:jaxb-runtime `2.4.0-xxx`? You can try specifying its version as `2.3.5` or `2.3.6`, `2.4.x` has never had a stable version, the stable version of `2.3.x` is followed by `3.x` and `4.x` in the `jakarta ee` namespace , refer to https://mvnrepository.com/artifact/org.glassfish.jaxb/jaxb-runtime. 

- For the changes made by Ehcache to JAXB because of compatibility, you can refer to https://github.com/ehcache/ehcache3/issues/2993 .

**Comment by 4soft-liebig** [comment]
I don't know why version `2.4.0-xxxx` was picked during the build. After specifying an explicit version for the `jaxb-runtime` dependency via:
```xml
            <dependency>
                <groupId>org.glassfish.jaxb</groupId>
                <artifactId>jaxb-runtime</artifactId>
                <version>3.0.2</version>
            </dependency>
```
our build worked again. Thanks for pointing that out.

**Comment by chrisdennis** [comment]
The situation with JAXB in the JRE/Ehcache is all kinds of messed up. What we’ve settled for now is to have a dependency version range: org.glassfish.jaxb:jaxb-runtime:[2.2,3)

If you want a specific version you can pin it down yourself. Personally, I’ve never had problems with allowing that version range to resolve to the latest available.
