### ISSUE TITLE
ehcache artifact without JSR-107 support would simplify apps deployed on app servers w/ a diff. default JSR-107 provider

### ISSUE THREAD

**Issue by haqer1** [ehcache/ehcache3#3037]
Without advertising the other JSR-107 provider,
the following exception is thrown:
**[2022-06-18T11:36:21.319+0200] [SomeServer 4.1] [SEVERE] [] [com.something.app.someapp.type.web.config.SomeConfigurer] [tid: _ThreadID=15 _Thread     Name=RunLevelControllerThread-1655544943873] [timeMillis: 1655544981319] [levelValue: 1000] [[
   Multiple CachingProviders have been configured when only a single CachingProvider is expected                         
 javax.cache.CacheException: Multiple CachingProviders have been configured when only a single CachingProvider is expected
     at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:376)                                 
     at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:351)                                 
     at javax.cache.Caching.getCachingProvider(Caching.java:142)
     ...**

P.S. Given that setting system property
javax.cache.spi.CachingProvider=com.alernative.cache.AlternativeCachingProvider
hasn't helped,
my current hackish work-around is to build a custom artifact after minimalistic deletion of relevant files:
```
$ rm org/ehcache/jsr107/EhcacheCachingProvider*
$ rm META-INF/services/javax.cache.spi.CachingProvider
$ rm OSGI-INF/org.ehcache.jsr107.*
```
P.P.S. My idea has been to use ehcache caches backed by the file-system, which the alternative doesn't seem to support (for free).

**Comment by chrisdennis** [comment]
If you wish you can use the explicit modules `org.ehcache.modules:*` rather than the default package that includes 107 support.

**Comment by chrisdennis** [comment]
Given that we think this an unusual case we're going to say that depending on individual modules is the solution here.

**Comment by haqer1** [comment]
The suggestion seems feasible. I put a comment to try it when i play with that code again.

P.S. I'd appreciate feedback on the following. 
1) Is org.ehcache:ehcache(:3.(9|10)) equivalent to 
everything under `org.ehcache.modules:*`
including org.ehcache.modules:ehcache-107
or some modules are excluded?
2) Does org.ehcache:ehcache(:3.(9|10)) 
include everything under 
`org.ehcache.modules.clustered:*`?
P.P.S. My guess is, I'd need to exclude just org.ehcache.modules:ehcache-107, including `org.ehcache.modules.clustered:*` to start with (further omissions could be considered over time to reduce the size of dependencies)...
