### ISSUE TITLE
Question about licensing of Terracotta classes

### ISSUE THREAD

**Issue by wojteo** [ehcache/ehcache3#3063]
Are Terracotta classess embedded into final jars governed by Apache 2.0 or Terracotta Public License?

If I use ehache, do I have to include the phrase "Powered by Terracotta" as a clickable hyperlink directing to http://www.terracotta.org at the bottom of any user interface screen ?

**Comment by jhouserizer** [comment]
If you simply use ehcache foss jar, there are no classes within that licensed for TPL.

If you use a bundling that includes the Terracotta client libraries, or additionally include (distribute) the ehcache-terracotta jar, then yes, that includes items currently licensed under TPL.

How to adhere to the TPL license would be a question for your lawyer, but probably isn't far off what you noted in your question.
