### ISSUE TITLE
EhCache evicting items even when there is enough allocated offheap space

### ISSUE THREAD

**Issue by arpitmalhotra** [ehcache/ehcache3#3098]
I am seeing EhCache evicting items from the off-heap cache even tho the allocated size of the off-heap cache is 3G and the occupied size is a 100s of Mb. Why is this behavior happening for evictions even tho allocated off-heap size is much more. This is evictions , expirations for TTL is 1/10th of evictions. Following is my config

            CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
                    .using(statisticsService)
                    .withCache("cache", CacheConfigurationBuilder.newCacheConfigurationBuilder(String.class, String.class, ResourcePoolsBuilder.newResourcePoolsBuilder()
                                                .offheap(3, MemoryUnit.GB).heap(1, MemoryUnit.GB).build())
                                                .withExpiry(ExpiryPolicyBuilder.timeToLiveExpiration(Duration.ofMinutes(10)))
                                                .withService(WriteBehindConfigurationBuilder.newUnBatchedWriteBehindConfiguration()
                                                                    .queueSize(10)
                                                                    .concurrencyLevel(10).build()))
                                                .build();
            cacheManager.init();

**Comment by chrisdennis** [comment]
Without a lot more information it's hard to know what is going on here. It seems much more likely that this is a usage issue, and not a bug. I would suggest that unless you have a reproducible test case (or a enough information for someone to build one) then this isn't a bug and should be directed to https://groups.google.com/g/ehcache-users

**Comment by arpitmalhotra** [comment]
My off-heap size is 3G, the allocated size that I see is only 2G. I still see continuous evictions from the cache. Would there be a reason for evictions given I have enough space allocated (read from stats.getTierStatistics().get("OffHeap").getEvictions()). Could other NIO operations cause off heap to evict more often ?

**Comment by arpitmalhotra** [comment]
@chrisdennis I am still having issues with this. Any advise would be very helpful.

 The constant stream of evictions at > 200 items per sec drops my hit rate to 65%.

Any idea what could be the cause of these evictions ? Is the off-heap store also limited by size or percentage of the allocated direct memory on the JVM. These are not expired items but evicted items for some reason. Also asked it here https://stackoverflow.com/questions/74903991/ehcache-too-many-items-getting-evicted-from-off-heap-store-even-though-there-i
