### ISSUE TITLE
Global configuration for all caches under a single CacheManager (ehcache 3.10.0 + JSR 107)

### ISSUE THREAD

**Issue by AntonioFilipov** [ehcache/ehcache3#3112]
Based on the [docs](https://www.ehcache.org/documentation/2.8/configuration/cache-size.html#cache-sizing-examples) for ehcache version 2.8, it seems that setting _maxBytesLocalHeap_, _maxBytesLocalOffHeap_ and _maxBytesLocalDisk_ was supported on the CacheManager level. 

Is it deprecated in 3.x? I cannot find any information regarding the deprecation or any alternative ways of achieving the same behavior in 3.x.

**Comment by chrisdennis** [comment]
This is a known feature gap from Ehcache 2.x. It's actually being actively worked on under https://github.com/ehcache/ehcache3/issues/33 (and in a few other related issues) at the moment.
