### ISSUE TITLE
ehcache 2 到 3.9.2版本升级

### ISSUE THREAD

**Issue by tangkuo88** [ehcache/ehcache3#3146]
ehcache3.9.2版本中很多ehcache2版本的类找不到了，RMI前缀开始的类；在新版本中应该需要怎么集成；能否提供具体升级替换改动代码与配置文件信息.谢谢.

**Comment by chrisdennis** [comment]
Translated:
> In ehcache3.9.2 version, many classes of ehcache2 version can not be found, the classes starting with RMI prefix; how to integrate in the new version; can you provide specific upgrade, replacement, change code and configuration file information. Thank you.

Answer:
There is no RMI replication support in Ehcache 3.x. It should be pretty simple to implement using an appropriately configured cache listener however.

Translated:
> Ehcache 3.x 中没有 RMI 复制支持。 然而，使用适当配置的缓存侦听器来实现应该非常简单。
