### ISSUE TITLE
org/ehcache/core/spi/store/Store.java using javax.* reference on jakarta branch

### ISSUE THREAD

**Issue by jaraujo-sinch** [ehcache/ehcache3#3172]
Hi!

The class is using javax.annotation.NonNull, instead of its jakarta.* counterpart.
Can you guys fix it?

Thanks!

**Comment by chrisdennis** [comment]
There is no runtime dependency on the module, and given how few usages there are the only fix you're likely to see for this would be dropping the `@Nonnull` annotations entirely. Would that be acceptable here?

**Comment by jaraujo-sinch** [comment]
Yes. I agree.
