### ISSUE TITLE
Align Cache & CacheManager builders behavior wrt .init()

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#318]
Also rename `StandaloneCache` to `UserManagedCache` (and builder)

Some return call `.init()` others don't:
 - `CacheManagerBuilder.build()` : inits the `CacheManager`
 - `StandaloneCacheBuilder.build()` : doesn't... 

should we refactor `.build()` to `build(bool init)` ?

Also rename the static util method that creates the actual builder to align with the explicit name

**Comment by ljacomet** [comment]
We discussed in last public meeting that we would go for `Builder.build(boolean initialise)`
