### ISSUE TITLE
Add capacity constraint to `RuntimeConfig`

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#320]
Do it!

**Comment by rishabhmonga** [comment]
As per discussion with Louis following things were to be included with this : 
- add store parameter to CacheEventNotificationListenerServiceProvider
- add validations to updateResourcePools() (for negative values, new tier, disk size less than heap size if both defined with ENTRIES)
- add listener to heap so updateResourcePools() for heap is functional
- add resourcePoolType to events generated from updateResourcePools()
- find a way to allow ehcache to register itself to the store listener if possible. Else leave a comment about the setSource method workaround in CacheEventNotificationService interface

**Comment by rishabhmonga** [comment]
•	create a ResourcePoolMerger which merges all validated ResourcePool(s) and returns a resourcePools object

**Comment by ljacomet** [comment]
PR #408 has been merged.
However, the code as it stands silently applies a heap mutation with a `MemoryUnit` taking the size and interpreting is as a count based change. This should be fixed to consider this task closed. I would simply refuse it at the validation.
