### ISSUE TITLE
Support for jaxb-runtime 4+?

### ISSUE THREAD

**Issue by Selaron** [ehcache/ehcache3#3208]
Hello,

when loading a ehcache.xml using ehcache 3.10 I get an exception:

Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventHandler

This is because ehcache3 requires jaxb-runtime < 3 while hibernate-core 6 requires jaxb-runtime >= 4.

Is ehache going to upgrade this dependency and migrate to jakarta.* namespace?

**Comment by laurentschoelens** [comment]
Normally the `jakarta` classifier should do the job

**Comment by Selaron** [comment]
Indeed, the jakarta classifier does the job. Thanks.
This can be closed.

>       <dependency>
>         <groupId>org.ehcache</groupId>
>         <artifactId>ehcache</artifactId>
>         <version>${ehcache.version}</version>
>         <classifier>jakarta</classifier>
>       </dependency>
>
