### ISSUE TITLE
Deprecated javax.xml API is used to parse configuration in Ehcache3

### ISSUE THREAD

**Issue by radistao** [ehcache/ehcache3#3225]
[javax.xml.bind » jaxb-api](https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api) v2 is outdated for 6 years already and migrated to  [jakarta.xml.bind » jakarta.xml.bind-api](https://mvnrepository.com/artifact/jakarta.xml.bind/jakarta.xml.bind-api) v4, but [Ehcache still depends on the old v2 API and implementation](https://github.com/ehcache/ehcache3/blob/561af430d76847a2c8aa1ba507cf3e142ad9185e/ehcache-xml/build.gradle#L104-L105), in particular https://github.com/ehcache/ehcache3/blob/561af430d76847a2c8aa1ba507cf3e142ad9185e/ehcache-xml/src/main/java/org/ehcache/xml/ConfigurationParser.java#L43

For example, having:
* Spring Boot 3 with dependencies `spring-boot-starter-cache`, `hibernate-jcache`, `ehcache`
* configured property `hibernate.javax.cache.uri=ehcache.xml` ([Hibernate Guide](https://docs.jboss.org/hibernate/orm/6.1/userguide/html_single/Hibernate_User_Guide.html#caching-provider-jcache-cache-manager))
*  `javax.xml.bind:jaxb-api` not provided or excluded, but `jakarta.xml.bind:jakarta.xml.bind-api:4.0.2` provided

The application  throws exception
> org.springframework.beans.factory.BeanCreationException: Error creating bean XXXXX: javax/xml/bind/ValidationEventHandler
>    ...
> Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventHandler
>   at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:116)
>   at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:92)
>    at org.ehcache.jsr107.EhcacheCachingProvider$ConfigSupplier.getConfiguration(EhcacheCachingProvider.java:328)
>    at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:134)
>    at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:85)
>    at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:194)
>    at org.hibernate.cache.jcache.internal.JCacheRegionFactory.resolveCacheManager(JCacheRegionFactory.java:208)
>    ...
>Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationEventHandler

<code><b>javax.xml</b>.bind.ValidationEventHandler</code> defined in <code><b>javax.xml</b>.bind:jaxb-api</code>
but <code><b>jakarta.xml</b>.bind:jakarta.xml.bind-api</code> defines <code><b>jakarta.xml</b>.bind.ValidationEventHandler</code>

Will the be migrated to `jakarta.xml` any time soon?

Thank you.

**Comment by chrisdennis** [comment]
Duplicate.
