### ISSUE TITLE
Leverage `ClassInstanceProvider`

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#347]
Make sure all user provided class instantiating "thing" leverage this abstract class.

**Comment by palmanojkumar** [comment]
Pl find analysis of different services for use of ClassInstanceProvider as mentioned in Issue-347. 

Analysis Result:

1.	DefaultSerializationProviderFactory
this service already leverage ClassInstanceProvider.

2.	DefaultCacheLoaderWriterFactoryProvider
this service already leverage ClassInstanceProvider.

3.	DefaultCacheEventListenerFactoryProvider
this service already leverage ClassInstanceProvider.

4.	WriteBehindDecoratorLoaderWriterProviderFactory
This service decorates user provided CacheLoaderWriter and uses DefaultCacheLoaderWriterFactoryProvider service for acquiring user supplied CacheLoaderWriter instance. 
In nutshell, this service doesn’t need any refactoring.

5.	CacheEventNotificationListenerServiceProviderFactory
This service provides mechanism to register user supplied CacheEventListener. User provided an instance of CacheEventListener and is registered with this service using CacheRuntimeConfiguration.
In nutshell, this service doesn’t need refactoring.	

6.	DefaultThreadPoolsServiceFactory
this service doesn’t deal with user provided classes and hence refactoring not required.

7.	DefaultLocalPersistenceServiceFactory
this service doesn’t deal with user provided classes and hence refactoring not required.

8.	CacheStoreProviderFactory
this service doesn’t deal with user provided classes and hence refactoring not required.

9.	DiskStoreProviderFactory
this service doesn’t deal with user provided classes and hence refactoring not required.

10.	OffHeapStoreProviderFactory
this service doesn’t deal with user provided classes and hence refactoring not required.

11.	OnHeapStoreProviderFactory
this service doesn’t deal with user provided classes and hence refactoring not required.

12.	DefaultStoreProviderFactory
this service doesn’t deal with user provided classes and hence refactoring not required.

Summary:
The necessary services already use ClassInstanceProvider and hence no modification/change is required.
