### ISSUE TITLE
Wire lifecycle concerns into `PersistentService`

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#355]
Methods of `Persistent*` types don't handle lifecycle concerns (e.g. `PersistentCacheManager.destroyCache`), that needs to be properly fixed (i.e. delegate to the appropriate `PersistenceProvider`)

**Comment by ljacomet** [comment]
Pushed out an initial PR: #434

Regarding persistent user managed caches, I have two approaches and would like feedback on these.
The first one hides the handling of persistent storage lifecycle inside the `PersistentUserManagedCache`:
```java
    PersistentUserManagedCache<Long, String> cache = UserManagedCacheBuilder.newUserManagedCacheBuilder(Long.class, String.class, "persistent-user-managed") // <1>
        .with(new UserManagedPersistenceConfiguration<Long, String>(new File(getStoragePath(), "myUserData"))) // <2>
        .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
            .heap(10L, EntryUnit.ENTRIES)
            .disk(100L, EntryUnit.ENTRIES, true)) // <3>
        .build(true);

    cache.close(); // <4>
    cache.toMaintenance().destroy(); // <5>

```
1. Create a `UserManagedCacheBuilder`, the identifier is mandatory if the cache needs to become persistent
2. Pass it the persistence configuration, which also makes the builder returns a `PersistentUserManagedCache`
3. Define disk resources, persistent or not
4. Closing the cache does not destroy storage if it was made persistent in 3.
5. On a closed cache, put it in maintenance and destroy its storage.

The second one forces the user to manage the lifecycle of the data himself:
```java
    LocalPersistenceService persistenceService = getPersistenceService(); // <1>
    persistenceService.start(new PersistenceConfiguration(new File(getStoragePath(), "myUserData"))); // <2>
    FileBasedPersistenceContext persistenceContext = persistenceService.createPersistenceContext("cache1"); // <3>

    UserManagedCache<Long, String> cache = UserManagedCacheBuilder.newUserManagedCacheBuilder(Long.class, String.class)
        .withPersistenceContext(persistenceContext) // <4>
        .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
            .heap(10L, EntryUnit.ENTRIES)
            .disk(100L, EntryUnit.ENTRIES, true)) // <5>
        .build(true);

    cache.close(); // <6>
    persistenceService.destroyPersistenceContext("id"); // <7>
```
1. Create a persistence service
2. Start it with a configuration
3. Create the persistence context to be used by your cache
4. Pass this context when building the cache - note the cache remains a _simple_ `UserManagedCache`
5. the boolean here no longer means anything (not that I like it ...)
6. Closing the cache does not touch the persistence context at all
7. Explicitly destroy the persistence context. One alternative is that the type given by the persistence service offers a destroy method, which is not on the type expected by the builder.

The second approach feels very much in line with what we imagine for user managed caches. At the same time, it is clearly more verbose for something that could be considered _core_, a disk store.

Questions? Comments?

**Comment by ljacomet** [comment]
After discussions with @alexsnaps and @chrisdennis amongst others, I believe the right solution is actually a mix of the propositions made before:

```java
    LocalPersistenceService persistenceService = getPersistenceService(); // <1>
    persistenceService.start(new PersistenceConfiguration(new File(getStoragePath(), "myUserData"))); // <2>

    PersistentUserManagedCache<Long, String> cache = UserManagedCacheBuilder.newUserManagedCacheBuilder(Long.class, String.class)
        .with(new UserManagedPersistenceConfiguration("cache-id", persistenceService)) // <3>
        .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
            .heap(10L, EntryUnit.ENTRIES)
            .disk(100L, EntryUnit.ENTRIES, true)) // <4>
        .build(true);

    // Work with the cache
    cache.put(42L, "The Answer!");
    assertThat(cache.get(42L), is("The Answer!"));

    cache.close(); // <5>
    cache.toMaintenance().destroy(); // <6>
```
1. You create _manually_ the persistence service
2. and you start it with its configuration
3. The configuration to make a persistent cache takes both an id for the storage and the persistence service
4. the disk resource config remains the point where you indicate if the storage is _persistent_ or not
5. Once you are done with the cache, close it - will delete files if not _persistent_
6. Or explicitly destroy its storage for _persistent_ ones.

The proposition enables the following:
* Share a persistence service between different user managed caches
* Creation and destruction of the persistence context remains logically linked with the cache lifecycle.

Does that make sense?
