### ISSUE TITLE
ConfigurationParser rules about ResourcePool inheritance from templates need defining/fixing

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#357]
The ConfigurationParser logic for collecting the resources used by a cache from it's XML config and template is a little weird.  Currently it collates all definitions from both together.  It seems we would want some kind of system where the cache config would take precedent over the template, but at what granularity I'm not yet sure (e.g. what happens if the cache config specifies a heap resource, and the template specifies a disk resource).  We also need to have the ConfigurationParser enforce that at least one of the template or cache configs contain resource definition - since this can't be done in XML without invoking the glory of Schematron - which is apparently frowned upon in this establishment.

**Comment by alexsnaps** [comment]
Relate to #33

**Comment by ljacomet** [comment]
Current status with regards to _defaults_:
* In a `CacheConfigurationBuilder`, we define a default resource pool containing `HEAP` resource, sized in entries at `Long.MAX_VALUE`
* In XML, if there is nothing defined, there are really no resources defined as we _always_ construct a `ResourcePools` even if fully empty.

I propose the following changes:
* `ResourcePoolsBuilder.build()` will throw an `IllegalStateException` if no pools have been defined
* XML will only configure `ResourcePools` if there is a definition, both for templates and cache declarations
* This means that there will now be a common default, the one from `CacheConfigurationBuilder`.

Comments on template inheritance at a later stage.

**Comment by ljacomet** [comment]
After further discussion with @lorban and going back to #421, the changes above to align XML and builder based config will be done.
However, the default heap pool will be discarded for Ehcache, making sizing mandatory.
For JSR-107 when caches are created:
* From `javax.cache.configuration.CompleteConfiguration`, a default heap of `Long.MAX_VALUE` size will be used,
* From  an Ehcache config - XML, template override or programmatic wrapped - no defaults, sizing is mandatory.

**Comment by ljacomet** [comment]
PR #952 opened for the changes mentioned above.

As for the cache vs. template behaviour, there is no plan to change current behaviour which is:
* When a cache definition is based on a template, any resource declaration will result in ignoring the template level definition.

This means that there is no notion of merging individual resource definitions.
