### ISSUE TITLE
OffHeapStore flush returns true when mapping was not faulted

### ISSUE THREAD

**Issue by aurbroszniowski** [ehcache/ehcache3#362]
The method OffHeapStore.flush(K key, ValueHolder<V> valueHolder, CachingTier<K, V> cachingTier) returns true even if the mapping was not faulted before.

**Comment by ljacomet** [comment]
Dependency on #373

**Comment by ljacomet** [comment]
Maybe flush does not even need a return value with Ehcache 3

**Comment by alexsnaps** [comment]
If the currently ignored tests are complete and test for this condition, `OffHeapStore` is currently behaving just fine with the work on-going as part of #373 & #436 ... @aurbroszniowski can you confirm these tests are complete and test for the condition above? `DiskStore` is still busted

**Comment by alexsnaps** [comment]
Addressed as part of #373
