### ISSUE TITLE
DiskStore flush returns false even though mapping was faulted

### ISSUE THREAD

**Issue by aurbroszniowski** [ehcache/ehcache3#363]
The method DiskStore.flush(K key, ValueHolder valueHolder, CachingTier cachingTier) returns false even though the mapping was faulted before.

**Comment by chrisdennis** [comment]
Whoever investigates this issue and #362 should first investigate whether we need this return value for any product reasons before fixing these bugs.  We may be able to get away with eliminating the return value entirely rather than fixing these bugs.

**Comment by aurbroszniowski** [comment]
Also AuthoritativeTierFlush SPI tests should be updated in case a value is not returned anymore

**Comment by alexsnaps** [comment]
Ah! Turns out these were test issues, and actually still somewhat are... The mock passed in are not configured to return the proper value, so the CAS-like op fails... Now, with the id stuff, it works, but sort of coincidently

**Comment by alexsnaps** [comment]
Addressed as part of #373
