### ISSUE TITLE
Add Cache.compute()-like method

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#365]
To sort of match `javax.cache.Cache.invoke(K, EntryProcessor<K, V, T>, Object...): T` 

Should also enable us to get rid of `org.ehcache.Jsr107Cache.compute`

**Comment by lorban** [comment]
A proposed implementation is available there: https://github.com/ehcache/ehcache3/pull/478

**Comment by alexsnaps** [comment]
Was discussed here: https://www.youtube.com/watch?v=vE6VvwriKlI
