### ISSUE TITLE
Only minimal (de)serialization between tiers

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#369]
If not the case already, make sure we don't unnecessarily deserialize out of one tier, to only re-serialize back into the next one...

**Comment by ljacomet** [comment]
Adding on the topic: currently Store.containsKey ends up calling into get in order to handle expiry - which means deserialization also. Probably worth optimising away.

**Comment by lorban** [comment]
Depends on #158 as the latter will have an impact on this.

**Comment by ljacomet** [comment]
Started looking at operations and cache configurations.

See https://docs.google.com/spreadsheets/d/1JiS3kp3q1SHR0YrIVb7YOUp3JlKJXSDt_Tndz2V1IDg/edit?usp=sharing

Will push a first PR for taking care of low hanging fruits.

Next step is around making `OffHeapValueHolder` lazy with regards to the deserialize of the value itself and add a method to enable taking a copy of the `ByteBuffer` holding it.

**Comment by ljacomet** [comment]
When faulting from authority to caching tier, while we need to deserialize to compute the new expiry duration, we may win a serialization when the caching tier stores serialized entries.
See `org.ehcache.internal.store.heap.OnHeapStore#importValueFromLowerTier` for example.
However, this would mean making the authority aware that the caching tier uses serialization.

**Comment by ljacomet** [comment]
Idea of making the `OffHeapValueHolder` lazy has been pushed out. Only with real perf number will this option be considered again.

Others improvements have been made though in two PRs.
