### ISSUE TITLE
Fix fields visibility in service implementations

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#372]
Some services don't seem to take into account that they can be called from different threads, hence some fields changes are not guaranteed to be visible and should be marked as volatile.

DefaultThreadPoolsService, DefaultStoreProvider and CacheStore.Provider are affect, but there may be more.

**Comment by palmanojkumar** [comment]
The below listed are list of services where field visibility needs to be fixed.
DefaultStoreProvider
OnHeapStore.Provider
OffHeapStore.Provider
DiskStore.provider
CacheStore.Provider
ClassInstanceProvider
DefaultThreadPoolsService
DefaultLocalPersistenceService

Comment if I missed any service.
