### ISSUE TITLE
OffheapStore.flush() doesn't copy the expiration properties from the flushed ValueHolder

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#373]

**Comment by alexsnaps** [comment]
We want to bring "ValueHolder identity" to solve this. i.e. have a `ValueHolder` have a unique identifier, propagated to all layers... so that can be reused when `flush` ing the access data. Each `Store` probably best decides how to achieve this...

**Comment by alexsnaps** [comment]
See whether anything should be done wrt #362 & #363 here as well.

**Comment by alexsnaps** [comment]
Needs #436 to be fixed first.

**Comment by ljacomet** [comment]
Re-opening: I missed something in the review. The `org.ehcache.internal.store.offheap.portability.OffHeapValueHolderPortability` was not updated to serialize / deserialize the  newly introduced `ValueHolder` id.
One way to see that is `org.ehcache.internal.store.offheap.OffHeapStoreTest#testFlushUpdatesAccessStats` will return a `ValueHolder` with `id == -1` when calling `OffHeapStore.getAndFault(key)` while it should not.
