### ISSUE TITLE
Clean up builders according to design guildelines

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#391]
See https://github.com/ehcache/ehcache3/wiki/design.basics#builder-design-guidelines

**Comment by lorban** [comment]
CacheManagerBuilder, CacheConfigurationBuilder and ResourcePoolsBuilder are good candidates to start with. There probably are others too.

**Comment by ljacomet** [comment]
[Relevant conversation](https://www.youtube.com/watch?v=NEwlUbxSezA) during one of our dev meetings

**Comment by ljacomet** [comment]
Key points from the conversation to be generalised in current code:
* All methods calls on builder that return the builder type are expected to make a copy instead of modifying in place. This allows to reuse intermediate builder states for different final states,
* Allow to skip `.build()` call when the result is consumed by another builder,
* Provide named methods for boolean settings or settings based on Enums. To decide against this, look at what kind of method explosion is causes on the builder as whole.
