### ISSUE TITLE
Define and apply naming conventions around providers and factories

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#392]

**Comment by lorban** [comment]
Have a look at the org.ehcache.spi.service.ServiceFactory file, as it contains:

*ProviderFactory
*FactoryProvider
*ServiceFactory
*ServiceProviderFactory

Those classes (and probably the related ones too) do not respect the Provider / Factory naming convention which adds quite some confusion. They should all be renamed consistently.

**Comment by ljacomet** [comment]
1. `ClassInstanceProvider` subclasses to be name `XxxProvider` and the class creating them `XxxProviderFactory`
2. Ehcache 3 services to be named `YyyService` unless they fall under point 1. Their factory classes to be named `YyyServiceFactory`.
3. Look at existing classes and reuse naming conventions. Signal any discrepancies.
