### ISSUE TITLE
Clustered ServerSideCacheManagerEntity create/destroy

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#393]
* How to identify a cluster? and a clustered CacheManager?
* Define configuration API and XML
* Design and implement

**Comment by AbfrmBlr** [comment]
As discussed in planning meeting, as part of this issue primarily we will focus on following points :-
--  Configuration
--  creating ClusteredCacheMananger, connecting it to the server side counterpart of it.
-- Focusing on Lifecycle of ClusteredCacheManager and handling of failure scenarios.

**Comment by AbfrmBlr** [comment]
After the discussions in dev meeting, we came to an consensus to add ARC config to the scope of this task. This will help in setting up the ground even for the unclustered cases.

**Comment by alexsnaps** [comment]
Somewhat reducing the scope of this issue. Let's focus on the `ServerSideCacheManagerEntity` from a Voltron perspective for now... that still requires addressing the concerns around "Voltron Storage API" though, but "only" for the `CacheManager` 's metadata, i.e. not key-value mappings

**Comment by alexsnaps** [comment]
Waiting on Coordinator entity to be read in https://github.com/Terracotta-OSS/terracotta-platform/issues/3 to finish the life cycle aspect of the this issue

**Comment by alexsnaps** [comment]
The `ClusteredCacheManagerEntityManager` needs to account for "taking over" a nomination from another client... Like in the case where it is supposed to create then actual `ClusteredCacheManagerEntity`... See terracotta-oss/tc-platform#15

**Comment by chrisdennis** [comment]
Obsolete, now covered by the issues under the BF-4487 milestone.
