### ISSUE TITLE
WriteBehind writer blocks cache put operation

### ISSUE THREAD

**Issue by aurbroszniowski** [ehcache/ehcache3#413]
I define a CacheLoaderWriter that simulate a long write operation, and couple it with a write behind config:

```
public class LongCacheLoaderWriter<K, V> implements CacheLoaderWriter<K, V> {

 ...

 public void write(final K k, final V v) throws Exception {
    try {
      Thread.sleep(4000);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
  }
...
```

The following code, just doing a cache.put(...) is then blocked by the writer

```
   CacheManagerBuilder<CacheManager> cacheManagerBuilder = CacheManagerBuilder.newCacheManagerBuilder();
    cacheManagerBuilder
        .withCache("writebehindcache", newCacheConfigurationBuilder()
            .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
                .heap(100, EntryUnit.ENTRIES).build())
            .buildConfig(Long.class, String.class));

    cacheManagerBuilder
        .using(WriteBehindConfigurationBuilder.newWriteBehindConfiguration()
            .concurrencyLevel(3).batchSize(4)
            .queueSize(10)
            .build());
    cacheManagerBuilder
        .using(new LongCacheLoaderWriterFactory<Long, String>(datasource));
    CacheManager cacheManager = null;
    try {
      cacheManager = cacheManagerBuilder.build(true);

      Cache<Long, String> cache = cacheManager.getCache("writebehindcache", Long.class, String.class);
      assertThat(datasource.size(), is(equalTo(0)));
      long start = System.currentTimeMillis();
      cache.put(1L, "value");
      long elapsedTime = System.currentTimeMillis() - start;
      assertThat("the cache.put should not be blocked by the write behind cachewriter", elapsedTime, is(lessThan(3000L)));
    } finally {
      if (cacheManager != null) {
        cacheManager.close();
      }
    }
```

**Comment by rishabhmonga** [comment]
I tried recreating the bug by using the following CacheLoaderWriter for simulating write operation:


  public class LongCacheLoaderWriter<K, V> implements CacheLoaderWriter {

    private static final Logger LOGGER = LoggerFactory.getLogger(LongCacheLoaderWriter.class);
    
    @Override
    public Object load(Object key) throws Exception {
      throw new UnsupportedOperationException("Implement me!");
    }

    @Override
    public Map loadAll(Iterable keys) throws Exception {
      throw new UnsupportedOperationException("Implement me!");
    }

    @Override
    public void write(Object k, Object v) throws Exception {
      try {
        LOGGER.info("Write");
        Thread.sleep(4000);
      } catch (InterruptedException e) {
        throw new RuntimeException(e);
      }
    }

    @Override
    public void delete(Object key) throws Exception {
      throw new UnsupportedOperationException("Implement me!");
    }

    @Override
    public void deleteAll(Iterable keys) throws Exception {
      throw new UnsupportedOperationException("Implement me!");
    }

    @Override
    public void writeAll(Iterable iterable) throws Exception {
      try {
        LOGGER.info("WriteAll");
        Thread.sleep(4000);
      } catch (InterruptedException e) {
        throw new RuntimeException(e);
      }
    }
  }

And the following LoaderWriteFactory

    private class LongCacheLoaderWriterFactory<K, V> implements CacheLoaderWriterFactory {

    @Override
    public void start(ServiceConfiguration<?> config, ServiceProvider serviceProvider) {
      //noop
    }

    @Override
    public void stop() {
      //noop
    }
    
    @SuppressWarnings("unchecked")
    @Override
    public <K, V> CacheLoaderWriter<? super K, V> createCacheLoaderWriter(String alias, CacheConfiguration<K, V> cacheConfiguration) {
      return new LongCacheLoaderWriter<K, V>();
    }

    @Override
    public void releaseCacheLoaderWriter(CacheLoaderWriter<?, ?> cacheLoaderWriter) {
      //noop
    }
   }

And used the following configurations for a simple put operation:

  @Test
  public void testWriter() {
    CacheManagerBuilder<CacheManager> cacheManagerBuilder = CacheManagerBuilder.newCacheManagerBuilder();
    
    cacheManagerBuilder
        .using(new LongCacheLoaderWriterFactory<Long, String>());

    CacheManager cacheManager = cacheManagerBuilder.build(true);
    
    final Cache<Long, String> writeBehindCache = cacheManager.createCache("writeBehindCache",
        CacheConfigurationBuilder.newCacheConfigurationBuilder()
            .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
                .heap(100, EntryUnit.ENTRIES).build())
            .add(WriteBehindConfigurationBuilder.newWriteBehindConfiguration()
                .queueSize(10)
                .concurrencyLevel(3)
                .batchSize(1))
            .buildConfig(Long.class, String.class));

    long start = System.currentTimeMillis();
    writeBehindCache.put(1L, "value");
    long elapsedTime = System.currentTimeMillis() - start;
    assertThat("the cache.put should not be blocked by the write behind cachewriter", elapsedTime, is(lessThan(3000L)));
    System.out.println(elapsedTime);

    cacheManager.close();
  }

The put operation seems to work expectedly without any blocking from the writer. If you could share the `LongCacheLoaderWriterFactory ` you used. We can check if something unexpected is caused due to that. 
Also please note that since you are using `batchSize(4)` this will route to a `writeAll` rather than a `write` operation.

**Comment by aurbroszniowski** [comment]
Here is the class:
```
package com.terracotta.qa.ehcache.configuration;

import org.ehcache.config.CacheConfiguration;
import org.ehcache.spi.ServiceProvider;
import org.ehcache.spi.loaderwriter.CacheLoaderWriter;
import org.ehcache.spi.loaderwriter.CacheLoaderWriterFactory;
import org.ehcache.spi.service.ServiceConfiguration;

import java.util.Map;

public class LongCacheLoaderWriterFactory<K, V> implements CacheLoaderWriterFactory {

  private Map<K, V> datasource;

  public LongCacheLoaderWriterFactory(Map<K,V> datasource) {
    this.datasource = datasource;
  }

  @Override
  @SuppressWarnings("unchecked")
  public <K, V> CacheLoaderWriter<? super K, V> createCacheLoaderWriter(final String s, final CacheConfiguration<K, V> cacheConfiguration) {
    return new LongCacheLoaderWriter(datasource);
  }

  @Override
  public void releaseCacheLoaderWriter(final CacheLoaderWriter<?, ?> cacheLoaderWriter) {

  }

  @Override
  public void start(final ServiceConfiguration<?> serviceConfiguration, final ServiceProvider serviceProvider) {

  }

  @Override
  public void stop() {

  }
}
```

**Comment by ljacomet** [comment]
More discussions on this topic happened during the public dev meeting of this day.
One idea was to remove from the public API `org.ehcache.CacheManagerBuilder#using(org.ehcache.spi.service.ServiceConfiguration<?>)`.
