### ISSUE TITLE
Returning copy of builders and default heap pool size initialization to Long MAX_VALUE

### ISSUE THREAD

**Issue by aurbroszniowski** [ehcache/ehcache3#421]
Builders returns copies, which means that a config defined on several lines must reassign itself otherwise the changes will be ignored.

See the example below, the resource pool definition here is ignored
```
    CacheConfigurationBuilder<Object, Object> builder = CacheConfigurationBuilder.newCacheConfigurationBuilder();
    builder.withResourcePools(newResourcePoolsBuilder().heap(100, EntryUnit.ENTRIES).build());
```

because the second line should be 
```
  builder = builder.withResourcePools(newResourcePoolsBuilder().heap(100, EntryUnit.ENTRIES).build());
```

So what happens is that the heap size is defined by the call on the first line:
```
CacheConfigurationBuilder<Object, Object> builder = CacheConfigurationBuilder.newCacheConfigurationBuilder();
```

And it will initialize a default heap size of the max value of Long:
Taken from CacheConfigurationBuilder.java:
```
  private CacheConfigurationBuilder() {
    this.resourcePools = ResourcePoolsBuilder.newResourcePoolsBuilder().heap(9223372036854775807L, EntryUnit.ENTRIES).build();
  }
```

This is particularly problematic because this will happily lead to GC pauses as soon as too many mappings are put in the cache, thus slowing down the application and even blocking it in the case of warming up the cache.

**Comment by ljacomet** [comment]
* Regarding the builders: I propose to extend the documentation on the topic to make the choice made very obvious and easily linkable when the question comes again.
* Regarding the default heap size, I propose to remove the default altogether and make cache creation without heap size specified invalid.

Other opinions?

**Comment by ljacomet** [comment]
The proposition of not having a size default for heap clashes with JSR-107. As the spec has no capacity concept, by default it will create heap-only caches without size specified.
Do we want to have no default in plain Ehcache as suggested above and default to max long in JSR-107?

**Comment by ljacomet** [comment]
Deciding default probably depends on ARC #33 - waiting for this to be done.

**Comment by chrisdennis** [comment]
My understanding of the way the scheme we chose for clustered ARC would map to unclustered ARC says that this doesn't have any effect on this.  I vote for no default in regular Ehcache and default unlimited (i.e. Long.MAX_VALUE entries) in 107.

**Comment by ljacomet** [comment]
Closing as the builder pattern will not change and with regards to sizing defaults, see #357
