### ISSUE TITLE
CacheStore.clear is racy

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#439]
afaict :
```
    try {
      authoritativeTier.clear();
    } finally {
      cachingTier.clear();
    }
```
Won't cut it, will it?! @lorban am I missing something?

**Comment by lorban** [comment]
I'd like to hear your concerns before touching this code as I agree that it is somewhat racy but it used to be impossible to observe the race when I originally wrote it IIRC.

**Comment by alexsnaps** [comment]
We can probably leave this undone, @chrisdennis is finishing the new `DiskStore`, and that should resolve it all... afaict the issue is the same as it always was, the flushing of entries from the queue to disk. Tests have been failing forever, they just fail more often now.

**Comment by alexsnaps** [comment]
Whatever I said, is total BS... this applies to #385 but not this one.
