### ISSUE TITLE
DiskStore capacity constraint

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#442]
... in whatever natural unit it may be

**Comment by chrisdennis** [comment]
This is coded (though not very well tested).  It relies on changes in offheap-store that have been merged, but not yet released.  I'm holding the release of offheap-store until the failure observed by Rishabh has either been fixed in offheap-store, or offheap-store has been ruled out as a culprit.

**Comment by chrisdennis** [comment]
The bug (#467) identified by @rishabhmonga has been fixed, it turned out to be a test bug, and not an offheap issue.  Consequently the 2.1.0 release of offheap-store has been cut and this issue is now unblocked.
