### ISSUE TITLE
Problem with FIFO Eviction

### ISSUE THREAD

**Issue by alanzplus** [ehcache/ehcache3#447]
Hey currently I' using the ehcache3 lib and I had a problem with FIFO eviction prioritizer.

The following is my part of cache config xml.

```xml
 <ehcache:eviction-prioritizer>FIFO</ehcache:eviction-prioritizer>
 <ehcache:resources>
     <ehcache:heap size="5" unit="entries"/>
  </ehcache:resources>
```

So if I have list of key like `1, 2, 3, 4, 5, 6`.
Then I put these key into the cache in order (from 1 to 6). So when I put the key 6,
the cache should evict key 1. However, the key the cache evicted is quite randomly.
Sometimes, it just evicted key 6! (this what i just inserted)

Does anyone know about this ?

**Comment by alexsnaps** [comment]
@alanzplus FIFO is based on the `creationTime` (which is in millisecond precision). Further more, a sample population is chosen and the eviction victim is chosen from there... 
With that in mind, could it be you're creating things that quickly that they _all_ qualify as "eldest" as far as the Cache is concerned?

**Comment by alanzplus** [comment]
@alexsnaps according to your comment, I tried to insert things into cache by an "large interval like 1 second.
But the problem cannot be solved. And also according to http://ehcache.org/documentation/2.8/apis/cache-eviction-algorithms,(and if ehcache3 use the same implementation as ehcache2), 15 random sample will be selected, so in my case, since only have 5 elements, the first key should be evicted. BTW, in the ehcach 3, what kind of strategy is used for sampling, and what is the sample size?

**Comment by rishabhmonga** [comment]
@alanzplus would you please confirm topology you are using. Also can you please share the complete ehcache config xml

**Comment by alexsnaps** [comment]
@alanzplus Best would be to share a complete reproducible test case... @rishabhmonga took a crack at reproducing the issue, but "only" got it to expose the behavior you describe in the `OffHeapStore` case if I got him right... Which isn't surprising, but probably still undocumented.

**Comment by rishabhmonga** [comment]
@alanzplus following is a test that demonstrates the use-case you mentioned when using an on heap cache. Since the cache size here is smaller than the size of the sample chosen for selecting eviction candidates, the outcome is predictable and confirms expected behavior.

````java
    TestTimeSource timeSource = new TestTimeSource();

    CacheConfiguration<String, String> cacheConfiguration = CacheConfigurationBuilder.newCacheConfigurationBuilder()
        .usingEvictionPrioritizer(Eviction.Prioritizer.FIFO)
        .add(new TimeSourceConfiguration(timeSource))
        .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
            .heap(5L, EntryUnit.ENTRIES).build()).buildConfig(String.class, String.class);

    CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder().withCache("cache", cacheConfiguration)
        .build(true);

    Cache<String, String> cache = cacheManager.getCache("cache", String.class, String.class);

//    Adding elements after time intervals
    cache.put("1", "a");
    timeSource.advanceTime(1);

    cache.put("2", "b");
    timeSource.advanceTime(1);

    cache.put("3", "c");
    timeSource.advanceTime(1);

    cache.put("4", "d");
    timeSource.advanceTime(1);

    cache.put("5", "e");
    timeSource.advanceTime(1);

    cache.put("6", "f");

//    asserting cache content
    assertNull(cache.get("1"));
    Assert.assertThat(cache.get("2"), Is.is("b"));
    Assert.assertThat(cache.get("3"), Is.is("c"));
    Assert.assertThat(cache.get("4"), Is.is("d"));
    Assert.assertThat(cache.get("5"), Is.is("e"));
    Assert.assertThat(cache.get("6"), Is.is("f"));

    cacheManager.close();
````

**Comment by alanzplus** [comment]
Thanks

**Comment by shengc** [comment]
Is this really getting resolved at all ? Look at the following logs out of the cache even listener. The case has been under heavy updates, and constantly rewritten to ehcache. Somehow along this process, it got evicted. If the eviction algorithm is FIFO, how come this happened ? 

Sorry I cannot share the code that generated the following logs, which is against the company policy. 

    2018-02-01 05:19:29,668 DEBUG - case RecurringInqReqWF-n9t4ns68jzv7bwu3apcqwvyf5 has been updated in cache
    2018-02-01 05:19:29,672 DEBUG - case RecurringInqReqWF-n9t4ns68jzv7bwu3apcqwvyf5 has been updated in cache (RecurringInqReqWF-n9t4ns68jzv7bwu3apcqwvyf5,1939392,18)
    2018-02-01 05:20:04,135 DEBUG - case RecurringInqReqWF-n9t4ns68jzv7bwu3apcqwvyf5 has been updated in cache
    2018-02-01 05:20:04,144 DEBUG - case RecurringInqReqWF-n9t4ns68jzv7bwu3apcqwvyf5 has been updated in cache
    2018-02-01 05:20:04,148 DEBUG - case RecurringInqReqWF-n9t4ns68jzv7bwu3apcqwvyf5 has been evicted from cache
