### ISSUE TITLE
Add/Remove `Cache` to `ServerSideCacheManager`

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#450]
This is about adding an empty `Cache` to an existing `ServerSideCacheManager`, not adding mapping into that `Cache`. i.e. what would metadata would be stored by the `ServerSideCacheManager` about that named `Cache` et al.

**Comment by ljacomet** [comment]
Work done under another set of issues, this is available as of Ehcache 3.1.0
