### ISSUE TITLE
Implement `ClusteredStore`

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#452]
Wiring the `Store` interface methods into the lower level API, enabling CRUD operations on a `Cache`.
This includes configuring a `Cache` to actually be clustered (i.e. Ehcache3 user facing API work)

**Comment by sgjava** [comment]
Is there any examples of using clustered/replicated caches with JCache? I used the old ehcache 2.x implementation and you could just configure a replicated cache in XML. I do not want to use Terracotta packages in my imports though.

**Comment by ljacomet** [comment]
@sgjava This is still work in progress, however the goal is to be transparent in that aspect. So by having clustered cache configured in XML, you would be able to use them from a pure JSR-107 code dependency.

**Comment by sgjava** [comment]
Very cool, I'm using Hazelcast provider until you guys get this completed, It will be nice to have another provider that will boot in the same JVM (Apache JCS requires you to run a server instance to do clustering) and do clustering.

**Comment by ljacomet** [comment]
@sgjava Terracotta clustering for Ehcache requires a Terracotta server to be running. It was the case in Ehcache 2.x and it will remain so in 3.x.

**Comment by sgjava** [comment]
I guess I stay with Hazelcast then. To have to use a server for clustering makes no sense.

**Comment by ljacomet** [comment]
Work performed under another set of issues - this is available as of Ehcache 3.1.0
