### ISSUE TITLE
CacheLoaderWriter method call

### ISSUE THREAD

**Issue by JSAhuja** [ehcache/ehcache3#454]
In CacheLoaderWriter for methods: loadAll, writeAll, deleteAll.
They are being called number of time, the number of keys(key set size) being passed as argument to them.  

Example: Say for WriteAll
Map<Long, String> map=new HashMap();
for(long i=1;i<=100;i++)
	map.put(i, "Value is "+i);
cache.putAll(map);

So here the writeAll is being called 100 times.

**Comment by chrisdennis** [comment]
This obviously isn't ideal... but there is some interesting balance between the most efficient way for the store to do the compute/install and the most efficient way for the CacheLoaderWriter to do the write.  The loader/writer may well *want* the keys in different batch sizes to the sizes that the store implementation *wants* to provide them.  This is obviously an extreme example of that scenario, but I think solving this issues is best served by solving the grander problem - who gets to dictate the batch sizes here.

**Comment by alexsnaps** [comment]
Right, we have had these discussion in the past. The agreement is: the `Store` does. i.e. it decides what the optimal batch size (and batch content) is, based on its locking strategy. Indeed, with heap only, that will always translate to batches of 1...

**Comment by ljacomet** [comment]
Not a defect
