### ISSUE TITLE
Improve Cache Config XML usability

### ISSUE THREAD

**Issue by JSAhuja** [ehcache/ehcache3#461]
In cache config XML characters like \n(New Line), spaces, \t(tabs) should be handles duringXML parsing.

Example:
```
<ehcache:serializer type="java.lang.Long">
                     serializers.CustomSerializerFloat
</ehcache:serializer>
```
When using the above configuration, getting class not found exception.

**Comment by alexsnaps** [comment]
I had a quick look at possibly fixes... Here's my take for now:

 - add a dedicated FQCN type to our XSD;
 - use that type where classnames are to be expected;
 - add an adapter to XJC for that type, so it trims the text value.

wdyt?

**Comment by JSAhuja** [comment]
I think so this should work.
