### ISSUE TITLE
Design and implement bulk operation statistics.

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#468]
We need to decide how the statistics on bulk operations 'work'.  Of particular interest is how bulk operations can be related to their non bulk equivalents.  There is a related issue around how operations in general related to their logically equivalent operations, whether those are bulk to non-bulk breakdowns or compound to non-compound breakdowns.  The needs of JSR-107 are a particular constraining parameter set here.

**Comment by ljacomet** [comment]
From multiple discussions, what needs to happen here is that bulk stats should:
* Offer operation statistics like  getAll count
* Offer logical operations count like hits, misses, puts and removes

Current idea is to implement this inline, as is done for getAll counting hits and defer adding this support to the statistics framework.

**Comment by albinsuresh** [comment]
Some bulk stats tests need to be added to `org.ehcache.jsr107.StatisticsTest` class, right???

**Comment by ljacomet** [comment]
Indeed, added to the PR
