### ISSUE TITLE
CoalesceKeysFilter is inefficient (potentially very slow)

### ISSUE THREAD

**Issue by headstar** [ehcache/ehcache3#477]
CoalesceKeysFilter takes O(n^2) time which is a problem if n is "big" and there are many duplicates.

Have had problem in production with this (using 2.6), when writes lags for some reason (database temporarily overloaded) and the write behind queue grows to maybe a million entries. One call to CoalesceKeysFilter easily takes more than 20 minutes in that case. 

I suggest a rewrite to bring it down to O(n).

**Comment by alexsnaps** [comment]
Only the batch gets coalesced though, not saying we shouldn't make it
better, but surprised by the 20 minute call. How big were your batches?!

**Comment by headstar** [comment]
All the quarantined items are filtered, right? Which means the entire queue?

**Comment by headstar** [comment]
Have implemented an alternative to the current implementation. The alternative is about 20 times faster when having 10000 duplicates and a total of 100000 elements. It's about 200 times faster when having 50000 duplicates and a total of 500000 elements.

**Comment by ljacomet** [comment]
Thanks for taking the time to look into this. Indeed there is room for improvement as you have shown.

Now, looking at the code as it exists now, there would be a better way to handle that:
In `org.ehcache.loaderwriter.writebehind.AggregateWriteBehindQueue.WriteBehindQueueFactory#createQueue` we could return a different `WriteBehind` queue implementation when coalescing is on.
This would allow the coalescing to happen on insertion and completely remove the need for the filter. Which means removing code that deals with that filter as an added bonus.

Would you be interested in moving forward with that idea?

**Comment by alexsnaps** [comment]
@headstar Y... sorry. The entire queue gets filtered (i.e. coalesced). I shouldn't do work related emails when on vacation ;) 
That being said, given the new approach we took, I'm pretty much in agreement with @ljacomet here. We need to make sure that the cost of the insertion remains fixed though.

**Comment by headstar** [comment]
@alexsnaps  No problem, lots of code to keep track of! :)

**Comment by ljacomet** [comment]
Waiting for #350 to be done

**Comment by ljacomet** [comment]
obsolete because of the changes that went into write-behind recently
