### ISSUE TITLE
Persistence Context not working as expected

### ISSUE THREAD

**Issue by rishabhmonga** [ehcache/ehcache3#494]
destroy() does not destroy non-persistent context

**Comment by rishabhmonga** [comment]
when `OffHeapDiskStore.Provider.releaseStore(store)` is called for a non-persistent store the `fileBasedPersistenceContext` should be cleaned up

**Comment by ljacomet** [comment]
@rishabhmonga Not at all, that was the whole point of #355 in order to decouple this. Let's have a chat to better describe this issue.

**Comment by rishabhmonga** [comment]
`EhcacheManager.destroy()` should clean up all `persistenceContext`. This will require starting the `LocalPersistenceService` so that the cleanup can be done.
