### ISSUE TITLE
DefaultLocalPersistenceTest failing on windows

### ISSUE THREAD

**Issue by AbfrmBlr** [ehcache/ehcache3#500]
org.ehcache.internal.persistence.DefaultLocalPersistenceServiceTest > testFailsIfDirectoryDoesNotExistsAndIsNotCreated FAILED
    java.lang.AssertionError at DefaultLocalPersistenceServiceTest.java:77

org.ehcache.internal.persistence.DefaultLocalPersistenceServiceTest > testFailsIfDirectoryExistsButNotWritable FAILED
    java.lang.AssertionError at DefaultLocalPersistenceServiceTest.java:47

**Comment by chrisdennis** [comment]
Yay Windows! http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6728842
