### ISSUE TITLE
Build failure in docs project with PermGen space error on Java 6

### ISSUE THREAD

**Issue by albinsuresh** [ehcache/ehcache3#512]
Environment:
java version "1.6.0_65" on Mac

Snippet from the build output:

:docs:asciidoctor FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docs:asciidoctor'.
> PermGen space

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by albinsuresh** [comment]
Build passes on Java versions 7 and 8.

**Comment by ljacomet** [comment]
This is a consequence of PR #424 which resolved issue #394. It probably should be documented on the dev wiki.

**Comment by ljacomet** [comment]
Found a general solution for this:

* Bump gradle version to 2.6 (and some plugins that need an update)
* Configure the build to use the "gradle daemon" which can be configured with JVM args

Unless someone has a strong argument against it, this is the way to go for "portable" builds.
