### ISSUE TITLE
Configuring ehcache as second level cache

### ISSUE THREAD

**Issue by GLE81** [ehcache/ehcache3#516]
Hi,

'm configuring ehcache in an Application on Spring 3.2.14.RELEASE and hibernate 4.3.11.Final. I'm having an error when a deploy the application in the server:

Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [] as strategy [org.hibernate.cache.spi.RegionFactory]

This are my configuration files:
		<dependency>
			 <groupId>net.sf.ehcache</groupId>
			 <artifactId>ehcache-core</artifactId>
			 <version>2.4.3</version>
		</dependency>
		<dependency>
			<groupId>net.sf.ehcache</groupId>
			<artifactId>ehcache</artifactId>
			<version>2.10.0</version>
			<type>pom</type>
		</dependency>
<dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-ehcache</artifactId>
    <version>4.3.11.Final</version>
            <exclusions>
                <exclusion>
                    <groupId>net.sf.ehcache</groupId>
                    <artifactId>ehcache-core</artifactId>
                </exclusion>
            </exclusions>
</dependency>       

Persistencia.xml
<persistence-unit name="persistenceUnit" transaction-type="RESOURCE_LOCAL">
        <provider>org.hibernate.ejb.HibernatePersistence</provider>
        <properties>
            <property name="hibernate.dialect" value="org.hibernate.dialect.OracleDialect"/>
            
            <property name="hibernate.hbm2ddl.auto" value="none"/>
            <property name="hibernate.ejb.naming_strategy" value="org.hibernate.cfg.DefaultNamingStrategy"/>
            <property name="hibernate.connection.charSet" value="UTF-8"/>
            
            
            
            <property key="hibernate.cache.use_second_level_cache">true</property>
            <property name="hibernate.cache.region.factory_class">org.hibernate.cache.ehcache.EhCacheRegionFactory</property>           
            <property key="net.sf.ehcache.configurationResourceName">/ehcache.xml</property>
            
        </properties>
    </persistence-unit>
</persistence>

ehcache.xml
<ehcache xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    updateCheck="false" xsi:noNamespaceSchemaLocation="ehcache.xsd" name="notificationsCacheManager" updateCheck="true"
    monitoring="autodetect" dynamicConfig="true">
    <diskStore path="java.io.tmpdir" />
    <defaultCache maxEntriesLocalHeap="10000" eternal="false"
        timeToIdleSeconds="120" timeToLiveSeconds="120" diskSpoolBufferSizeMB="30"
        maxEntriesLocalDisk="10000000" diskExpiryThreadIntervalSeconds="120"
        memoryStoreEvictionPolicy="LRU" statistics="true">
        <persistence strategy="localTempSwap" />
    </defaultCache>
    <cache name="com.test.notifications.domain.ClientOauth"  maxEntriesLocalHeap="10000"
                eternal="false"
                timeToIdleSeconds="300"
                timeToLiveSeconds="600"
                <persistence strategy="localTempSwap"/>
    <cache name="org.hibernate.cache.internal.StandardQueryCache"
                maxElementsInMemory="10000"
                eternal="false
                timeToLiveSeconds="86400"
                overflowToDisk="false"
                memoryStoreEvictionPolicy="LRU" />          

</ehcache>

Do I have anything wrong in my configuration?

**Comment by ljacomet** [comment]
For questions on Ehcache (2.x or 3.x) usage, please ask them on the [google group](https://groups.google.com/forum/?#!forum/ehcache-users).

This project is for Ehcache 3 development, so closing as not relevant.
