### ISSUE TITLE
Implement `ResilientCache` strategy et al

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#52]
Figure out and implement the default `ResilienceStrategy`

**Comment by ljacomet** [comment]
One item to do when resuming work here is add `DEBUG` logging statement each time the `Cache` hands over control to the strategy.

**Comment by rishabhmonga** [comment]
It would help with the EhCache3 Load Testing if `ResilienceStrategy` was pluggable so the exceptions being thrown internally can be recorded efficiently.

**Comment by henri-tremblay** [comment]
Will be addressed by #2198
