### ISSUE TITLE
Fix default and limit values in write behind configuration

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#543]
From the pull request #541 on issue #534, a number of comments were made around the documenting of effective defaults and limit values. This issue aims to address these remarks:

* Default and limit value for rate limit

>   /**
>    * The maximum number of write operations to allow per second.
>    *
>    * {@code 0} means no limit.
>
> chrisdennis added a note 21 hours ago
>
> > Bleagh... nasty Ehcache 2.x wart re-emerging.
>
> alexsnaps added a note 21 hours ago
>
> > Right, it an int, let's make this Integer.MAX_VALUE (which most probably is more than large enough even if considered a "strict" limit)

* Default and limit value for max queue size

>   /**
>    * The maximum amount of operations allowed on the write behind queue.
>    *
>    * {@code 0} indicates an unbound queue.
>
> chrisdennis added a note 21 hours ago
>
>> More warts
>
> alexsnaps added a note 21 hours ago
>
>> Again, use Integer.MAX_VALUE, which is inline with JDK types btw...

* Default and limit values for min and max write delay

Also it seems we have defaults encoded in three places: configuration class, XSD and XML parser. The last two are a clear duplication that should be resolved.

**Comment by ljacomet** [comment]
Part of the duplication between XSD and XML parser comes from https://jaxb.java.net/guide/Element_default_values_and_unmarshalling.html

But changing that for write behind would mean that

````xml
      <ehcache:writebehind coalesce="true" concurrency="10" size="100000">
        <ehcache:writedelay min="5" max="30"/>
        <ehcache:ratelimitpersecond>50000</ehcache:ratelimitpersecond>
        <ehcache:batchsize>10</ehcache:batchsize>
        <ehcache:retryAttempts delay="5">10</ehcache:retryAttempts>
      </ehcache:writebehind>
````
would become
````xml
      <ehcache:writebehind coalesce="true" concurrency="10" size="100000" 
                           minWriteDelay="5" maxWriteDelay="30" rateLimit="50000" 
                           batchSize="10" retryDelay="5" retryAttempts="10"/>
````

Is this acceptable?

**Comment by lorban** [comment]
Personally, I like the attributes much better than the child elements.
