### ISSUE TITLE
Misc write behind improvements / cleanup

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#547]
As noted on the PR #544 over issue #543, there are potential cleanups to be done in writebehind:

* No rate limiting when batch size is 1? See `AbstractWriteBehindQueue`
* Try to extract out the commonality between processBatchedOperations(...) and processSingleOperation(...). See `AbstractWriteBehindQueue`
* Improve time related settings to be a long + TimeUnit combination and use a common time unit inside the code

**Comment by ljacomet** [comment]
@chrisdennis How much of this issue is made obsolete by your work on #350?

**Comment by chrisdennis** [comment]
Quite possibly all of it... but I'd probably leave this open until #350 is done so we know for sure.  Let me mark this as blocked until #350 is done, that way no one will pick it up in the meantime.

**Comment by ljacomet** [comment]
obsolete because of the changes that went into write-behind recently
