### ISSUE TITLE
XML elements and attributes naming convention

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#548]
Should we align on:
* Camel case - clearly java inspired
* name-name - more XMLish
* something else??

**Comment by lorban** [comment]
After checking:

https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/resources/org/hibernate/hibernate-mapping-4.0.xsd

https://github.com/spring-projects/spring-framework/blob/master/spring-beans/src/main/resources/org/springframework/beans/factory/xml/spring-beans-4.2.xsd

apparently, both Spring and Hibernate rely on the following naming convention:

 - Dashed XML-ish element and attribute names.
 - Caml case for complexType

but they differ on enums: Hibernate sticks to XML-ish while Spring goes Caml.

**Comment by ljacomet** [comment]
Decided to go for the general rule of using `word-word` style for elements, attributes and complex type names.
PR #613 takes care of that.
