### ISSUE TITLE
Key Copier not always called

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#554]
Configure a key copier on a tiered cache, and the key copier is not called to copy the key when the mapping is faulted on-heap.

**Comment by lorban** [comment]
Configure a key copier on a tiered cache, and the key copier is not called to copy the key when the mapping is faulted on-heap.

**Comment by ljacomet** [comment]
Now that I think about it, how is it an issue since the key and value come from the Authority and so have been serialised / deserialised?
I understand that this logic is impl. dependent and so I am not against the fix, still wondering ;-)

**Comment by lorban** [comment]
Good point, this extra copy might not be needed. But I still believe that the MapWrapper's putIfAbsent() contract is broken, or at the very least breaks the principle of least surprise.

If we want to keep the implementation the way it is, we'd better make sure to document this "unnatural" MapWrapper behavior and write specific tests for it.

**Comment by ljacomet** [comment]
Not saying we need to / should do that. Just wanted to make sure if you had a buggy behaviour you did not end up blaming the wrong piece of code and thus leaving the issue in.

**Comment by lorban** [comment]
No worries, the only buggy behavior I observed is that some assertions I'm writing about the key copier being called failed.
