### ISSUE TITLE
Declared services in org.ehcache.spi.service.ServiceFactory are started more than 1 time

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#569]
At cache initialization, if a user service depends on a service declared in a `org.ehcache.spi.service.ServiceFactory`, such as the ManagementRegistry, the dependency is started more than 1 time.

This is a new issue that came after commit 0e4d6af79b75a9c570872db33f9fb245e2969b36.

Some tests not committed yet were failing for the management registry refactoring I am currently working on.

@ljacomet : perhaps you would like to have a look ?

I will attach a PR which includes a unit test to reproduce the issue.

**Comment by ljacomet** [comment]
@mathieucarbou Good catch!

However, your fix does not resolve another issue introduced by my broken fix: when a dependency is started, it does not make it inside the list of started services and so in case of failure it will not be stopped.

I will be working on a fix that will address that too.

**Comment by mathieucarbou** [comment]
@ljacomet cool tahnk you :+1:
