### ISSUE TITLE
Weird developer organization names in generated pom

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#595]
This is what the generated <organization> entries look like:

```
    <developer>
      <name>Ludovic Orban</name>
      <email>lorban@bitronix.be</email>
      <organization>org.apache.maven.model.Organization@291b9a0d</organization>
      <organizationUrl>http://ehcache.org</organizationUrl>
    </developer>
```

**Comment by ljacomet** [comment]
Ended up checking out Gradle and there is an issue with the way you can fill a pom. It seems the system confuses the `organization` node inside `developer` which should be a `String` with the root `organization` node which is a complex object.

Found a work around and will be pushing out a PR soon. Also investigating where to report this to Gradle.
