### ISSUE TITLE
offheap too small causes silent insert failure

### ISSUE THREAD

**Issue by sfrind** [ehcache/ehcache3#597]
When I put some values and the offheap seems to small then I can't get it later. No Exception is thrown!
Expected is that if a value does not make it into the cache then the put should fail.
Testproject can be provided.
Tested on version 3.0.0.m2

**Comment by ljacomet** [comment]
Hello,

Don't you have at least a log statement indicating the issue?
And also, what kind of off heap size and value size are you talking about here?

As for wanting an exception to be thrown, remember that it is valid for a cache to drop an entry on put due to eviction. So we plan to have the default resilience strategy only log. But you will most likely be able to configure a different one that then could throw.

**Comment by sfrind** [comment]
I had not in mind that the cache might evict values. I might misuse the cache for my purpose because I want to keep track of things.
I will try to use pinning of the whole cache.

**Comment by sfrind** [comment]
I had something like
cacheManager = CacheManagerBuilder
				.newCacheManagerBuilder()
				.with(new CacheManagerPersistenceConfiguration(new File("c:\\tmp", "myData")))
				.withCache("stephanConfig",
						CacheConfigurationBuilder.newCacheConfigurationBuilder()
						.withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder().heap(100000, EntryUnit.ENTRIES).offheap(100, MemoryUnit.MB))
						.buildConfig(Key.class, String.class))
				.build(true);

for 1000000 values that I have inserted. I did hope that no values were evicted but probably I have not configured properly that it should use the disk if RAM is not sufficient.

**Comment by ljacomet** [comment]
* Ehcache 3 no longer has a pinning concept, so you cannot prevent eviction of entries completely. You can however use an eviction veto - no documentation outside of code yet. If you need _always_ in memory values, consider using a different library.
* Your configuration shows some weird things:
  * It declares a persistence configuration but you do not use a disk, you are using OffHeap memory instead. See [documentation](http://www.ehcache.org/documentation/3.0/getting-started.html#disk-persistence)
  * In Ehcache 3 _ALL_ elements are always stored in the lower tier so you need to size it appropriately to hold all of on heap + extras.

**Comment by sfrind** [comment]
I have tried

class MyEvictionVeto implements EvictionVeto<Key, String> {

		/**
		 * return true means veto
		 */
		public boolean test(Entry<Key, String> argument) {
			return true;
		}
		
	}
	
	private void initCache() {
		cacheManager = CacheManagerBuilder
				.newCacheManagerBuilder()
				.with(new CacheManagerPersistenceConfiguration(new File("c:\\tmp", "myData")))
				.withCache("stephanConfig",
						CacheConfigurationBuilder.newCacheConfigurationBuilder()
						.evictionVeto(new MyEvictionVeto())
						.withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
								.heap(10000, EntryUnit.ENTRIES).offheap(50, MemoryUnit.MB).disk(100, MemoryUnit.MB))
						.buildConfig(Key.class, String.class))
				.build(true);
		cache = cacheManager.getCache("stephanConfig", Key.class, String.class);
	}

But the result is not that put results in exception when there is no free space. The result is that put gets extremely slow.
But it is no problem. I will always make the disk big enough.
Thanks a lot for your help.

**Comment by ljacomet** [comment]
Not a bug

**Comment by ljacomet** [comment]
With regards to the veto impl: you are forcing iteration over the whole content of the cache to find an eviction candidate. When that fails, Ehcache will start looking for a candidate without invoking the veto. So it is slow on a large cache indeed. The concept is designed for having some implementation that veto a limited number of entries, not all.
