### ISSUE TITLE
Add gitter.im badge in README ?

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#610]
This is a sort of chatroom by organization / projects (i.e. https://github.com/Ovea/testatoo)

**Comment by ljacomet** [comment]
We already have an IRC channel, see https://github.com/ehcache/ehcache3/wiki#process

Are you proposing this as an alt?

**Comment by mathieucarbou** [comment]
Ok! Actually I just found the tool nice and beautiful, easy to use and with a GitHub integration for projects. And also much more attractive compared to IRC ;-) I don't know if it can/should replace/be an alternative of IRC, but for all these points, as a user, if i had the choice of using both on a GihHub project, for sure I would choose the easiest integrated no-conf no-setup solution :-)

**Comment by mathieucarbou** [comment]
FYI, I would add that Gitter.im as basics IRC-like commands (ban, unban, join, etc.), keyboard shortcuts, pull request / issue reference, message history, private rooms, mentions, etc. So it could be thought as a collaborative tools for discussions around a GitHub project. And like IRC, there's some android, iphone, pc, mac clients.

They also have an __IRC bridge__: https://irc.gitter.im/

So I guess you could still use IRC, but they add a better integration layer on top of it for GitHub projects.

**Comment by ljacomet** [comment]
Sticking with IRC, although it is true that we could spend some time improving the channel by setting up a bot.
