### ISSUE TITLE
Remove extractable (and rarely used?) write-behind features

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#627]
The write behind retry functionality can be safely made the concern of the CacheLoaderWriter implementor.  This simplifies the write behind implementation and configuration.  If we want to support the useless ourselves this can be accomplished by writing a CacheLoaderWriter wrapper implementation that handles the retry concerns.

**Comment by ljacomet** [comment]
As commented on the PR that removes this (and the rate limiting logic), we should consider providing the wrapper implementation although at a later stage.

**Comment by chrisdennis** [comment]
In the same vein as retry I'm also removing the rate limiting from write behind and pushing it to a potential future CacheLoaderWriter wrapper.
