### ISSUE TITLE
http://www.ehcache.org/v3/jsr107 missing

### ISSUE THREAD

**Issue by sgjava** [ehcache/ehcache3#658]
Using from your example:

<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.ehcache.org/v3'
    xmlns:jsr107='http://www.ehcache.org/v3/jsr107'>

**Comment by ljacomet** [comment]
Sorry, can you expand on what the issue is?

Because the URI of an XML namespace does not need to match a valid URL for downloading the XSD. Its goal is to be a unique identifier.

We also decided that the XSD will not be published before it is final, that is when the 3.0.0 GA is released.

**Comment by sgjava** [comment]
It's just failing XML validation in Netbeans, not a big deal. You can close it then.

**Comment by alexsnaps** [comment]
I'm not net beans expert, but you should be able to point it to the
locations of the xsd which are all in the Ehcache jar

**Comment by sgjava** [comment]
It's OK for now since it will be published in the final release. Nice seeing you guys at the conference. I'm sure I'll have more questions as I'm working my way through an example I'm developing.

**Comment by alexsnaps** [comment]
Good stuff, looking forward to your input then!
