### ISSUE TITLE
JCache annotations do not work

### ISSUE THREAD

**Issue by sgjava** [ehcache/ehcache3#666]
Looking through the source I do no see any interceptors for the JCache annotations. The following dependancies worked for ehcache 2 JCache (this is my ehcache 3 test project https://github.com/sgjava/ehcachejsr107):

```
        <dependency>
            <groupId>org.jsr107.ri</groupId>
            <artifactId>cache-annotations-ri-cdi</artifactId>
            <version>1.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jboss.spec.javax.interceptor</groupId>
                    <artifactId>jboss-interceptors-api_1.1_spec</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>jcache</artifactId>
            <version>1.0.1</version>
        </dependency>
```

**Comment by ljacomet** [comment]
I am not sure what you find missing.
As found in the following [blog post](http://blog.hazelcast.com/how-jsr107-caching-annotations-are-meant-to-be-used/), it is not the implementor's role to provide annotation integration.

**Comment by sgjava** [comment]
I think it's pretty clear from the dependency I pointed out above. That dependency worked with ehcache 2 jcache extensions, but cache-annotations-ri-cdi doesn't work with ehcache 3. Do you have any examples using JCache annotations with ehcache 3?

**Comment by ljacomet** [comment]
My bad, misunderstood what you were saying. I did not try annotations with Ehcache 3. Maybe someone else did?

**Comment by sgjava** [comment]
I kind of have it working now, but I'm having a scope issue with the annotations. It looks like ehcache.xml is getting picked up and creating the caches, but trying to read a named cache from a unit test is returning a new cache.

**Comment by anthonydahanne** [comment]
I just came across this demo project using the JCache annotations : 
https://github.com/Adopt-a-JSR/JCache-CDI 

they don't configure much, but I kind of like the idea of just replacing :

        <dependency>
            <groupId>org.jsr107.ri</groupId>
            <artifactId>cache-ri-impl</artifactId>
            <version>1.0.0</version>
        </dependency>

in the pom.xml, with : 

        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
            <version>3.0.0.m3</version>
        </dependency>

and re running the demo main class (App) and see ehcache3 in action.

**Comment by sgjava** [comment]
This is close, but no cigar:
* I'm using named caches created from ehcache.xml
* I need to validate cached data via unit test.
* I need to create a cache resolver, so the cache can span apps/JVMs

**Comment by sgjava** [comment]
OK, using a CacheResolverFactory I was able to share the named cache across annotations and manual access. See https://github.com/sgjava/jcache-tomee for example.
