### ISSUE TITLE
search attributes on diskStore

### ISSUE THREAD

**Issue by publicocean0** [ehcache/ehcache3#670]
Hi , i developed  a lot of code using ehcache 2.10 , supposing search attributes are working in every case. Now i discovered that in DiskStore is not working. 
So for not replaching all my code i m trying to understand 
1) does ehcache3 permit to use search attributes in disk Store (persistent case)?
2) ehcache3 contains already integration for Spring Library ? 

Thanks for every suggestion

**Comment by ljacomet** [comment]
Hello,

Ehcache 3 no longer has the search feature.

Regards,
Louis

**Comment by ljacomet** [comment]
Also, please use the [ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) google group for this kind of questions.

**Comment by publicocean0** [comment]
ops :) so, i will have to implement on my own this part
