### ISSUE TITLE
Modularize APIs to account for JDK9

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache3#683]
May want to use this to figure out where we screwed up:
http://jqassistant.org/get-started/

**Comment by ljacomet** [comment]
* API module is master
 * a package present here cannot be repeated anywhere else.
* core module: 
 * `org.ehcache.core.*`
* impl module:
 * `org.ehcache.impl.*`
 * `org.ehcache.config.builders`
* xml module:
 * `org.ehcache.xml.*`
* transactions module:
 * `org.ehcache.transactions.*`
* 107 module:
 * `org.ehcache.jsr107.*`
* clustered modules:
 * `org.ehcache.clustered.*`
