### ISSUE TITLE
How  to get instance of CacheManager using XML-configured template

### ISSUE THREAD

**Issue by ipolevoy** [ehcache/ehcache3#701]
This is more of a question than an issue, but I was unable to find answers. 

If I load XML configuration, and have the following in the XML file: 

```xml
<config xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns='http://www.ehcache.org/v3'
        xsi:schemaLocation="http://www.ehcache.org/v3 ../../../main/resources/ehcache-core.xsd">
    <cache-template name="activejdbc">
        <key-type>java.lang.String</key-type>
        <value-type>java.lang.Object</value-type>
        <heap size="200" unit="entries"/>
    </cache-template>
</config>
```

I will then load the config file: 

```java
URL url = getClass().getResource("/activejdbc-ehcache.xml");
XmlConfiguration xmlConfiguration = new XmlConfiguration(url);
```

How to get an instance of CacheManager based on this configuration? In other words, I want all new caches generated from this CacheManager to use the same config template. 

Can I do this?

**Comment by AbfrmBlr** [comment]
You can use the `XMLConfiguration` to get a `CacheMananger` using the following code snipppet 
```` java 
CacheManager cacheManager = CacheManagerBuilder.newCacheManager(configuration); 
````

**Comment by ljacomet** [comment]
@ipolevoy Please use the [ehcache-users google group](https://groups.google.com/forum/#!forum/ehcache-users) for such questions.

Also, it is [documented](http://www.ehcache.org/documentation/3.0/xml.html), including how to work with templates in that context.
