### ISSUE TITLE
Documenting dynamic updatable properties

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#702]

**Comment by lorban** [comment]
Currently, the `CacheRuntimeConfiguration` interface only allow registering and deregistering cache event listeners and modifying the resource pools.

We already have a `updateResourcesAtRuntime` example in `GettingStarted` briefly showing how to modify the resource pools.

What do we exactly want to document? The whole ruleset about what resources can or cannot be updated? A `registerCacheEventListener` example? Are we missing other dynamic updatable properties?
