### ISSUE TITLE
attribute vs. element in XML config

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#703]
Some "logical" consistency has to be applied here.
From issue #20

**Comment by lorban** [comment]
Everything looks decent to me, maybe another pair of eyeballs would disagree?

**Comment by ljacomet** [comment]
Some inconsistencies found:
  * Sizing information: align on time information format
    * We have time information which uses an attribute for the time unit and the element content for the value
    * We have size information which uses two attributes for the quantity and unit
  * Ordering of elements:
    * SizeOf config should be close to disk store config inside the cache.
