### ISSUE TITLE
Builders: more specific methods

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#705]
With #635 done, users will be able to configure instances of loader-writers, serializers etc directly using the cache configuration builder as follows:

````java
CacheConfigurationBuilder.newCacheConfigurationBuilder()
        .add(new DefaultCopierConfiguration<Description>(new DescriptionCopier(),
            CopierConfiguration.Type.KEY))
````
This way the user still has to use a service configuration explicitly to stick in an actual instance. As an improvement ver this, specialized methods like withLoaderWriter, withValueSerializer etc can be added to the CacheConfigurationBuilder so that the configuration of instances would look much more intuitive. Internally we can still get the job done with the overloaded service configuration constructors that take in instances. But at least the user facing API would look much cleaner this way.

So configuring instances could be done this way:

````java
CacheConfigurationBuilder.newCacheConfigurationBuilder()
        .withLoaderWriter(new SimpleLoaderWriter())
        .withKeyCopier(new DescriptionCopier())
        .withValueSerializer(new PersonSerializer())
````

From #20

**Comment by lorban** [comment]
This requires moving the builders out of core, either in impl or in a new module. One of the reason being that Default*Configuration classes are in impl while builders are in core.

**Comment by ljacomet** [comment]
I am in favour of moving the builders to impl module.
