### ISSUE TITLE
data loss when init EHCacheManager

### ISSUE THREAD

**Issue by yuankui** [ehcache/ehcache3#712]
hello,

In code `org.ehcache.internal.store.disk.OffHeapDiskStore#recoverBackingMap`, there are the following logs
```
The index for data file {} is out of date by {}ms, probably due to an unclean shutdown. Creating a new empty store
```
that may cause all the data been ignored thus lossing all the data that persist before.

So In a Java web application, How to properlly shutdown EHCache to verify that all data in cache flushed into disk before application exited.

here is my code & xml

```
final URL myUrl = HelloServlet.class.getResource("/ehcache.xml");
        Configuration xmlConfig = null;
        try {
            xmlConfig = new XmlConfiguration(myUrl);
        } catch (Exception e) {
            e.printStackTrace();
        }
        cacheManager = CacheManagerBuilder.newCacheManager(xmlConfig);

        System.out.println("hitting...");
        if (cacheManager.getStatus() != Status.AVAILABLE) {
            System.out.println("cacheManager = " + cacheManager.getStatus());
            cacheManager.init();
        }

        cache = cacheManager.getCache("test", String.class, String.class);
```

xml
```
<core:config xmlns:core="http://www.ehcache.org/v3">

    <core:service>
        <core:persistence directory="/Users/yuankui/tmp/mydata" />
    </core:service>

    <core:cache alias="test">

        <core:key-type copier="org.ehcache.internal.copy.SerializingCopier">java.lang.String</core:key-type>

        <core:value-type copier="org.ehcache.internal.copy.SerializingCopier">java.lang.String</core:value-type>

        <core:expiry>
            <core:tti unit="minutes">2</core:tti>
        </core:expiry>

        <core:eviction-prioritizer>LFU</core:eviction-prioritizer>

        <core:resources>
            <core:heap size="200" unit="entries" />
            <core:offheap size="200" unit="mb" />
            <core:disk size="2000" persistent="true" unit="mb" />
        </core:resources>
    </core:cache>


</core:config>
```

**Comment by AbfrmBlr** [comment]
@yuankui This is documented <a href="http://www.ehcache.org/documentation/3.0/getting-started.html">here.

**Comment by yuankui** [comment]
@AbfrmBlr But if the web application is kill by `kill -9`,then there may result in data loss as described.

I think there should be a better way to deal with it.

**Comment by ljacomet** [comment]
Hello,

Just to clarify about the supposed data loss:
Ehcache is a caching product, so losing data should not be an issue. After
all it has expiry and eviction.

The persistence option for the cache is provided as a way of reloading your
cache faster. It IS NOT there so that the cache can act as a system of
record. And yes indeed the open source persistence has this limitation that
the index and data files MUST be in sync in order to be considered valid at
recovery.

Regards,
Louis

**Comment by yuankui** [comment]
okey.

CACHE!

that's a GOOD EXCEUSE

**Comment by ljacomet** [comment]
Not an excuse, just an honest description of the open source feature set.
We welcome contributions if you feel like having a resilient disk store is a must in the open source version.

Closing for now.
