### ISSUE TITLE
Potential issue in iteration with multiple tiers

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#716]
While working on #165, I realised that we may have an issue when iterating on multiple tiers.
Currently, the iteration happens at the `AuthoritativeTier` level and will remove expired entries. But I believe this happens without looking at the pinning state, which means we may end up in weird state.

Did not write a test to confirm yet, so this may be bogus ... though I doubt it.

**Comment by lorban** [comment]
I confirm this bug: iterating expired entires of a n-tier caches won't make the caching tier immediately flush their mappings. On the other hand, once expiration happened in the authority, it will eventually happen from the caching tier too which will flush the value that will instantly be dropped to the floor by the authority, and the cache will return null as it should. Not ideal, but not broken from a user's perspective.

On the other hand, there is a nasty side-effect: iterating the authority means iterating a store that doesn't have its metadata up-to-date as those happen only get updated in the caching tier as long as the mapping doesn't get flushed down.
This means that iterating an authority can very well prematurely expire perfectly valid mappings (think TTI).

**Comment by lorban** [comment]
Resolving #825 first would make fixing this bug much simpler in the light of keeping the implementation JSR-107 compliant.

**Comment by lorban** [comment]
Related to https://github.com/jsr107/jsr107spec/issues/337 as well.
