### ISSUE TITLE
Ehcache Specific ServerEntityService Management Concerns

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#720]
This is a separate task because it's not an upstream dependency of any of the other tasks.  It's obviously dependent on knowing how the server side Ehcache code will interact with the M&M code.

**Comment by mathieucarbou** [comment]
Requires:

1. management module refactoring to extract the management registry layer into terracotta-management for other project usage
2. improving terracotta-model to add support for monitoring messages and notifications and topology
3. an ehcache "collector" service and a provider to configure it through management calls to output ehcache notifications and statistics to a consuming class (i.e. management service producer of tc server)
4. Adding a producer that consumes the collector messages and put them in the tc server monitoring tree in the right tree path.
5. Eventually add a specific Management Provider for the server entity ?

**Comment by chrisdennis** [comment]
Closing this as it is being tracked within the M&M work.
