### ISSUE TITLE
BlockingCacheDecoratorFactory implementation

### ISSUE THREAD

**Issue by pisek** [ehcache/ehcache3#726]
There is no BlockingCacheDecoratorFactory for creating blocking cache from xml.

This factory should probably be inside ehcache OTB.

**Comment by ljacomet** [comment]
Thanks for your interest in Ehcache 3!

Can you describe your usage scenario?

We are currently not planning on providing any API to enable explicit locking and thus not port of the Ehcache 2.x blocking cache.

**Comment by pisek** [comment]
There was no cacheDecoratorFactory which can be used inside xml to generate BlockingCache etc.

Example:
```xml
	<cache 
		name="someCache" 
		eternal="false" 
		maxEntriesLocalHeap="20000" 
		timeToLiveSeconds="1800" 
		memoryStoreEvictionPolicy="LRU">

		<cacheDecoratorFactory class="somtehing.BlockingCacheDecoratorFactory"
        	properties="timeoutMillis=10000" />

	</cache>
```

Example BlockingCacheDecoratorFactory:
```java
/**
 * A decorator factory to create {@link BlockingCache}
 */
public class BlockingCacheDecoratorFactory extends CacheDecoratorFactory {
	private static final Logger logger = LoggerFactory.getLogger(BlockingCacheDecoratorFactory.class);

	@Override
	public Ehcache createDecoratedEhcache(Ehcache cache, Properties properties) {
		BlockingCache blockingCache = new BlockingCache(cache);
		
		String timeoutMillisString = properties.getProperty("timeoutMillis");

		if (timeoutMillisString != null) {
			try {
				int timeoutMillis = Integer.parseInt(timeoutMillisString);
				blockingCache.setTimeoutMillis(timeoutMillis);
			} catch (NumberFormatException e) {
				logger.error("Could not parse timeoutMillis ["+timeoutMillisString+"] to proper integet. Using no-timeout locks.", e);
			}
		}
		
		return blockingCache;
	}

	@Override
	public Ehcache createDefaultDecoratedEhcache(Ehcache cache, Properties properties) {
		return createDecoratedEhcache(cache, properties);
	}
}
```

**Comment by ljacomet** [comment]
Indeed this is lacking in the Ehcache 2.x line.

If you are interested in contributing something like that, please open an issue at https://jira.terracotta.org/jira/browse/EHC and we will follow up with you.

Note that as I stated before, we have no plan on porting this feature to the 3.x line, so if you are interested in seeing it, please describe your use case.
