### ISSUE TITLE
Splitting the distribution jar to have a lightweight ehcache jar

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#748]
We could remove the management module (and thus its 2 transitive dependencies) from the default dist. This would depend on #747. Probably most of the ehcache users won't need this feature ? And we could have something like:
- ehcache.jar
- ehcache-management.jar

**Comment by mathieucarbou** [comment]
@ljacomet : I am wondering if we can close it ?

**Comment by chrisdennis** [comment]
I think this already happened: 1b9b8fabd17cf10310ac1cd27ca110cf8aeb8e18. I did it as part of #747.
