### ISSUE TITLE
Server Side Cache Configuration

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#764]
Implement a type to represent the server side aspects of a cache's configuration.   In a similar way to #835 this may result in a number of different types, along client/server/transport boundary.  This issue is also coupled to #763, which will produce a server side cache/store type that right now will only be a holder for this type - but will eventually come to represent the richer clustered cache.

**Comment by chrisdennis** [comment]
Blocked on various tasks in Voltron/Platform on the core storage service.

**Comment by chrisdennis** [comment]
Also relates to #859 regarding what configuration elements are actually needed here.

**Comment by cljohnso** [comment]
The addition of issue #1141 covers the work remaining for this issue.  This issue is being retired.
