### ISSUE TITLE
Builds for JDK 1.8 failing 

### ISSUE THREAD

**Issue by cljohnso** [ehcache/ehcache3#770]
While the JDK 1.6 and JDK 1.7 builds are successful, the JDK 1.8 builds are failing.  The indications are build worker is being killed (kill -9) while running tests.

Curiosity about the build environment led to the following:

* JDK 1.6 build is running on a "large" machine (Building remotely on 646591f4 (standard m1.large lxc-fedora17 large))
* JDK 1.7 build is running on a "large" machine (Building remotely on 646591f4 (standard m1.large lxc-fedora17 large))
* JDK 1.8 build is running on a "**small**" machine (Building remotely on 567587d5 (small lxc-fedora17 m1.small))

Assuming Amazon EC2, an `m1.small` machine has 1.7 GB RAM with 1 vCPU and an `m1.large` machine has 7.5 GB RAM with 2 vCPU.  Might this be the root of the failure?

**Comment by ljacomet** [comment]
Looks like PR #772 passed.

Two changes: 
* one on the job config so that all variations are limited to a standard cloudbees machine.
* one on the gradle build where we specify the max heap for test JVMs

**Comment by ljacomet** [comment]
Looks like the real culprit was the missing label axis in matrix jobs. This is now fixed.
