### ISSUE TITLE
Improve javadoc

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#776]
While releasing m5 javadoc, I noticed that outside of the api module, there are a number of classes that are user facing that lack proper documentation.
This includes package level documentation.

**Comment by ljacomet** [comment]
First PR (#802) pushed out for the builders javadoc

**Comment by ljacomet** [comment]
From @lorban, `Store.replace(K, V)` javadoc needs to be looked at.

**Comment by lorban** [comment]
`Store.computeIfPresent()` and `Store.bulkComputeIfAbsent()` should be looked at too, especially their returned value contract.

**Comment by ljacomet** [comment]
Create #844 to track further javadoc improvements.
