### ISSUE TITLE
Split Cache implementation: with or without LoaderWriter

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#777]
This is an enhancement investigation where we want to measure the effect of no longer having allocations inside the `Cache` implementation when it uses no `CacheLoaderWriter`.

Depending on the performance result, we will determine if this change becomes permanent.

**Comment by lorban** [comment]
According to the investigation done in #507, this is a big deal for performance. So this isn't a question anymore: let's do it!

**Comment by ljacomet** [comment]
Follow ups from conversations with @AbfrmBlr and @lorban:
* Cache Put statistics to have outcomes `PUT` or `UPDATE` in addition to `FAILURE`
* `Store.put` to return boolean to enable the above
* For similar reasons, `Store.remove` will change its return type to boolean
* put, replace and remove operations in `Store` implementations must handle expiry properly. They were not, most likely because they were not used in practice thus far.
 * This indicates missing SPI tests that should be added

**Comment by ljacomet** [comment]
Was a bit too quick in closing - still needs test additions: ones equivalent to `EhcacheBasic*Test` for a non loader writer cache.

**Comment by ljacomet** [comment]
Looking at `EhcacheWithLoaderWriter`, I realise it still accounts for not having a loader writer. But that makes no sense as we always will have one in this type. So the code needs to be cleaned up to account for that.

**Comment by ljacomet** [comment]
The following should throw if used `org.ehcache.core.Ehcache.Jsr107CacheImpl#loadAll` and that means related code can be deleted.
This method is JSR-107 specific but making sense only with a loader writer configured.

**Comment by ljacomet** [comment]
Previous comment is wrong as JSR-107 enables registration of a cache loader without using it as read through. And in that case, the code in `org.ehcache.core.Ehcache.Jsr107CacheImpl#loadAll` will be invoked.
