### ISSUE TITLE
Getting started documentation on disk store

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#781]
Call outs are out of sync with the code as they mention a `LocalPersistenceService` while the code only deals with configuration objects

**Comment by AbfrmBlr** [comment]
````java
    LocalPersistenceService persistenceService = new DefaultLocalPersistenceService(new CacheManagerPersistenceConfiguration(new File(getStoragePath(), "myData")));
    PersistentCacheManager persistentCacheManager = CacheManagerBuilder.newCacheManagerBuilder()
        .using(persistenceService)
        .withCache("persistent-cache", CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, String.class)
            .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
                .heap(10, EntryUnit.ENTRIES)
                .disk(10L, MemoryUnit.MB, true)) // <2>
        )
        .build(true);
````

This code does not compile. I understand why, but for the user it is still a persistent cache manager which was created using a service. 
I am just raising a question, whether we should document that to use `PersistentCacheManager ` specific methods, a cast is needed.

**Comment by ljacomet** [comment]
We should not document the above example anywhere and then the question does not exist. Or am I missing something?

**Comment by AbfrmBlr** [comment]
As discussed, this way need not be documented.
