### ISSUE TITLE
EhcacheOffHeapBackingMap.computeIfPinned()  too eagerly deserializes the OffHeapValueHolder's value

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#799]
`AbstractOffHeapStore.flush()` calls `EhcacheOffHeapBackingMap.computeIfPinned()` which fully deserializes the `OffHeapValueHolder`'s value even if the latter only is necessary when the flushed value expires *and* there is a registered cache event listener. The expiration check could be done solely with the `OffHeapValueHolder`'s metadata, saving the enormous cost of object deserialization.

**Comment by lorban** [comment]
This relates to #797 but is more important as more perf is lost here than in the other compute methods.

**Comment by ljacomet** [comment]
Requires offheap-store release (most likely 2.2.1) to fix a bug
