### ISSUE TITLE
Scalability of ehcache

### ISSUE THREAD

**Issue by porunov** [ehcache/ehcache3#815]
Hello,

I need to create a big and scalable cache cluster to store most viewed (hot) photos of my site.
Now all photos stored in S3.
I need features like these:
- Simple add/remove cache nodes to cluster
- Rebalance cluster when add/remove nodes
- Replicate data
- Protection of node failure

Does ehcache supports these features or I need use commercial Terracotta's products?

Best Regards, Alexandr

**Comment by ljacomet** [comment]
Hi Alexandr,

Thanks for your interest in Ehcache 3.
You should consider using the [google group](https://groups.google.com/forum/#!forum/ehcache-users) for this kind of questions.

Now to answer quickly some topics here:

> - Simple add/remove cache nodes to cluster

Will be supported once clustered is released if we are talking about client nodes, see next point.
> - Rebalance cluster when add/remove nodes

Not relevant in the Ehcache model as the cluster is an independent set of nodes from the clients. Note that the open source offering is limited to a single active server.
> - Replicate data
> - Protection of node failure

High availability in Terracotta is achieved by having passive standby nodes which should cover both points above.

More details on the [Terracotta open source offering](http://terracotta.org/downloads/open-source/catalog).

Regards,
Louis
