### ISSUE TITLE
EhcacheManager.close hangs after error creating cache

### ISSUE THREAD

**Issue by cljohnso** [ehcache/ehcache3#822]
If an `Error` is thrown after the `CacheHolder` is added to 'caches' but before `value.setCache` is called, then a `EhcacheManager.close` hangs (in `EhcacheManager.CacheHolder.retrieve`) waiting for the cache reference to be set in the `CacheHolder` instance.

This problem was discovered during testing when a place-holder update in `EhcacheManager.getStore` threw an `AssertionError`.  The fault could be caused by an `Error` thrown during `Service` resolution or `Store` creation.

**Comment by ljacomet** [comment]
I am not sure this should be fixed at all. When an `Error` is thrown, we should not even pretend to clean up.
And our own code throwing `AssertionError` is such a case ... as it should not happen under any _normal_ circumstances.

**Comment by cljohnso** [comment]
The way the code is now, an Error leaves us in a hard wait with no clue as to why.

**Comment by ljacomet** [comment]
After discussions, while we do not want to catch `Error` or `Throwable` during cache construction, we need to make sure this does not cause `CacheManager.close()` to block.

**Comment by AbfrmBlr** [comment]
````java
  @Test
  public void testCloseWhenCacheCreationFailsDuringInitialization() throws Exception {
    Store.Provider storeProvider = mock(Store.Provider.class);
    doThrow(new Error("Test EhcacheManager close.")).when(storeProvider).createStore(any(Store.Configuration.class), Matchers.<ServiceConfiguration>anyVararg());

    CacheConfiguration<Long, String> cacheConfiguration = new BaseCacheConfiguration<Long, String>(Long.class, String.class, null, null, null, ResourcePoolsHelper.createHeapOnlyPools());
    Map<String, CacheConfiguration<?, ?>> caches = new HashMap<String, CacheConfiguration<?, ?>>();
    caches.put("cache1", cacheConfiguration);
    DefaultConfiguration config = new DefaultConfiguration(caches, null);
    final CacheManager cacheManager = new EhcacheManager(config, Arrays.asList(
        storeProvider,
        mock(CacheLoaderWriterProvider.class),
        mock(WriteBehindProvider.class),
        mock(CacheEventDispatcherFactory.class),
        mock(CacheEventListenerProvider.class),
        mock(LocalPersistenceService.class)
    ));

    final CountDownLatch countDownLatch = new CountDownLatch(1);

    Executors.newSingleThreadExecutor().submit(new Runnable() {
      @Override
      public void run() {
        try {
          cacheManager.init();
        } catch (Error err) {
          assertThat(err.getMessage(), equalTo("Test EhcacheManager close."));
          countDownLatch.countDown();
        }
      }
    });
    countDownLatch.await();
    cacheManager.close();

  } ````

**Comment by AbfrmBlr** [comment]
Is this a valid test?
If yes, then in this case also the cachemanager.close hangs but at InternalStatus$Transition.get and waits for internal status to e not null.
