### ISSUE TITLE
Change stores to inline-evict mappings for which the updated expiration timestamp's makes them expire

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#825]
Currently, when a `Store` implementation figures a mapping hasn't yet expired but after updating its timestamp the mapping has expired, it is kept into the store.

We could optimize that by checking for expiration after updating the mapping's timestamp to avoid keeping the latter.

**Comment by lorban** [comment]
This is especially annoying in the context of JSR-107 where creation and access can have different expiration policies.

Configuring such expiration policy on a JSR-107 cache:
```
new ParameterizedExpiryPolicy(Duration.ETERNAL, Duration.ZERO, null)
```
makes this problem quite apparent as with our current implementation, a mapping will not expire before its first access (as it should be) but we only expire it on the 2nd access. This isn't incorrect, but can create some friction with the JSR-107 TCK's `Cache.iterator().hasNext()` tests.

**Comment by ljacomet** [comment]
Requires #866 before it can be finished
