### ISSUE TITLE
Clustered Caching Client Side Configuration

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#833]
Design XSD and programmatic API for configuring clustered caches.  The current plan here is to support caches that are either explicitly sized or share an explicitly sized pool.  We will need 'resource' configuration for explicit sizing and sharing at the cache level, and 'service' level configuration for the shared pools.  Both pools and explicitly sized caches will allocate storage out of named server side resources that will have been configured in the server configuration.

**Comment by cljohnso** [comment]
Need programmatic creation of ClusteredResourceType
