### ISSUE TITLE
Server Side CacheManager Configuration

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#835]
Implement the server side cache manager configuration types.  Depending upon the decisions made around the compatibility rules under #858 there may be up to four types coming out of this task:

1. Full server resident representation
2. Full client resident representation
3. Messaging representation (likely not distinct, but possible)
4. Partial client resident representation

**Comment by cljohnso** [comment]
Since concurrency strategy support is not expected to be user configurable, the addition of issue #1138 covers the work remaining for this issue.  This issue is being retired.
