### ISSUE TITLE
Revisit contract between ClassInstanceProvider and Closeable things

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#837]
After discussions with @cljohnso, @chrisdennis and @lorban there is some thought that the contract with regards to user provided instances needs to be revised.

Currently anything that implements `Closeable` will be closed when released. Suggestion is to not do that for things that were provided as instances and limit it to things that were constructed by provider.

**Comment by ljacomet** [comment]
From discussion during the (dev meeting of March 15th](https://www.youtube.com/watch?v=ROiD7zPLqfk), we agreed that while we maintain the `Closeable` will be closed contract, it will be limited to instances constructed by the `ClassInstanceProvider` or equivalent. When the user provides us with his own instance, we will not perform that invocation at all.

**Comment by AbfrmBlr** [comment]
A little clarificaiton :
When user provides class name in configuration, Ehcache instantiates the instance, thus it will closed (if Closeable), whether ClassInstanceProvider creates it or not.
But if user direatly provides the instance, since Ehcache does not instantiate, it will not close.

**Comment by lorban** [comment]
I assume that this means `Copier` instances created by `ClassInstanceProvider` will also respect the `Closeable` contract.
