### ISSUE TITLE
Define Server Side Cache Configuration Contents and Compatibility Rules

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#859]
This includes functionality for validating the configuration against the configuration provided by a client attempting to retrieve the cache.  The server-side cache configuration type will be a folding of both cluster specific configuration pulled from the clustered "resource" for this cache, in addition to some aspects of the general configuration of this cache (it may indeed be simplest to embed the actual cache configuration object within this type - if that is possible).   We need to decide what properties are part of the server side cache configuration, and what the rules are for compatibility on those properties.

**Comment by ljacomet** [comment]
See #1130 for one invalid use case that needs a proper user level exception,
