### ISSUE TITLE
During flush to disk, value is deserialized from the authoritative tier

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#861]
`AbstractOffHeapStore.flush()` calls `computeIfPinned()` on the backing map but the given BiFunction almost never needs to read the value from the `ValueHolder`.

Unfortunately, if you drill down to the `OffHeapHashMap.computeIfPresentWithMetadata()` method, you can see on line 2047 that the value is being deserialized before passing it to the BiFunction.

This has quite a measurable performance impact on the disk store.

**Comment by ljacomet** [comment]
That should only deserialize the 5 longs of metadata of the `LazyOffHeapValueHolder` and not the value itself. And we need that metadata in all methods, including flush.
