### ISSUE TITLE
Proposal: provide shaded entity jars for clustering

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#863]
With @anthonydahanne, we'd like to create some system tests and also tests manually the clustered ehcache kit with our project. We find the kitting hard to use for the server part at the moment because there are a lot of jars and we don't really know where to put them and how they will impact our own entities that are eventually using some same dependencies.

So we were wondering if it was possible to just provide 2 entity jars containing the needed dependencies shaded inside.
1. coordinator-entity.jar => would contain coordinator-entity-\* + voltron-proxy
2. ehcache-entity.jar => would contain ehcache-\* + annotations (?)
3. Also, we were able to remove the server api jars because they are provided by the server. I.e. our shaded jars only contain required application classes and it works fine.

The idea would be to only have 2 jars (sort of standalone independent plugins) that the users just need to drop into the server's lib folder.

Also, in our application, we provide 2 entity jars the same way, and both are using the voltron-proxy. Same for coordinator entity. So with the server plugin isolation, perhaps it would be better to have the dependencies shaded so that one entity could depend on voltron proxy 1.0.1 and for example another entity could depend on voltron-proxy 1.0.2 (i.e. it should work if there is no big changes and classpath is isolated). I take as an hypothesis that the server isolates each entity plugin independently based on the jar files.

Let me know what you think @chrisdennis @ljacomet : I could provided a PR if you need ? Otherwise if it is not possible, what are the reasons why we should keep these jars spread like this ?

Thanks :-)

```
├── plugins
│   ├── api
│   └── lib
│       ├── annotations-2.0.3.jar
│       ├── coordinator-entity-common-1.0-SNAPSHOT.jar
│       ├── coordinator-entity-server-1.0-SNAPSHOT.jar
│       ├── ehcache-common-3.0.0-SNAPSHOT.jar
│       ├── ehcache-server-3.0.0-SNAPSHOT.jar
│       ├── entity-server-api-1.0-SNAPSHOT.jar
│       └── voltron-proxy-1.0-SNAPSHOT.jar
```

**Comment by mathieucarbou** [comment]
:-)

Speaking with @anthonydahanne , he explained me that you prefer having all jars apart and dependencies declared in the manifest.

Ok!

**Comment by chrisdennis** [comment]
Actually I proposed supporting a directory per logical classpath partition... i.e. `plugins/api/ehcache`, `plugins/lib/ehcache`, `plugins/api/management`, `plugins/lib/management`.  I think that should be a very minimal change in voltron, and provides much more obvious and flexible isolation for entity/service implementers.

**Comment by chrisdennis** [comment]
If there's an issue here then its a terracotta-platform one.  @myronkscott what do you think to the idea in my last comment?
