### ISSUE TITLE
Move EhcacheManager.closeEhcache persistence logic should move to a deeper layer

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#885]
Currently the closeEhcache method in the manager contains logic that would seem to be related to how persistence is handled by the various services that might support it.  It would seem to me that like how we extracted out the maintenance mode logic to those layers that this code should also belong somewhat deeper in the services.  I am being vague because right now it seems the location of this code is 'wrong', but I'm not 100% on what the 'right' location would be.

**Comment by ljacomet** [comment]
I believe this has been addressed when implementing generalisation of tiered storage and especially the introduction of `PersistableResourceService`.
