### ISSUE TITLE
Determine need for org.ehcache.config.builders.ResourcePoolsBuilder#withReplacing method

### ISSUE THREAD

**Issue by cljohnso** [ehcache/ehcache3#893]
The `ResourcePoolsBuilder.withReplacing` was added to preserve the ability to _replace_ a `ResourcePool` in an existing collection as part of removing replace capability from the `with` (and adjunct) method.  The expectation was there would be some places in the code where the `withReplacing` method would be required over `with`.  This turned out **not** to be the case.

Is `withReplacing` needed?

If needed, unit test coverage needs to be added to support the use case.

**Comment by chrisdennis** [comment]
The only use I can think of for this is reusing a resource pool builder and wanting to overwrite a previous;y defined resource.  I also wonder if this might have interactions/implications for #357

**Comment by ljacomet** [comment]
Changes done for #357 end up having no impact on this, in the sense that the decided overwrite behaviour is at the _resource pools_ level, not per _resource pool_. As such the `withReplacing` remains unused in the code base.

However, I still believe it makes sense to have it for the use case described by Chris.

Starting work on this issue to add the tests for it.
