### ISSUE TITLE
Finalized core XSD should be uploaded to the public website in the conventional location

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#894]
Prior to going GA we should make sure that ehcache-core.xsd file is uploaded to the conventional location on the website relative to it's XML namespace.  Someone with more XML knowledge than me can probably determine exactly what behavior/location that is.

**Comment by cljohnso** [comment]
The class-level javadoc in `org.ehcache.xml.XmlConfiguration` needs to be updated to include a reference to the schema location.

**Comment by ljacomet** [comment]
Propose to inspire ourselves from what's [done in Spring](http://docs.spring.io/spring/docs/3.0.x/spring-framework-reference/html/xsd-config.html#xsd-config-body-referencing):
* Main XSD
  * Schema namespace: `http://www.ehcache.org/v3`
  * Schema location: `http://www.ehcache.org/schema/ehcache-core-3.0.xsd`
* XA xsd
  * Schema namespace: `http://www.ehcache.org/v3/tx`
  * Schema location: `http://www.ehcache.org/schema/ehcache-tx-ext-3.0.xsd`
* javax.cache xsd
  * Schema namespace: `http://www.ehcache.org/v3/jsr107`
  * Schema location: `http://www.ehcache.org/schema/ehcache-107ext-3.0.xsd`

with each namespace having a basic landing page that lists the relevant XSD files.

**Comment by ljacomet** [comment]
After discussion with @jhouserizer agreed to use `xml` as the folder name for schema files, to align with Quartz

**Comment by ljacomet** [comment]
PR ehcache/ehcache.org-site#30 has been merged
