### ISSUE TITLE
Combine the multiple XML parsing services in to a single service type

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#895]
Currently there are 3 XML parsing service (service creation, service, and resource).  Each of these service types has an interface and they all have `getXMLSchema()` methods that are called to add their schema to the central XML parser/validator.  I don't think the resultant schema duplication is causing any problems but I'm wondering if moving to single service might be simpler:

``` java
public interface ExtensionConfigurationParser<T, U> {
  Source getXmlSchema() throws IOException;

  URI getNamespace();

  ServiceCreationConfiguration<T> parseServiceCreationConfiguration(Element element);

  ServiceConfiguration<T> parseServiceConfiguration(Element element);

  ResourcePool parseResourcePool(Element element);
}
```

In the example above I've moved the parse methods in to this uber-parser, but we could have indirection through multiple parser instances instead:

``` java
public interface ExtensionConfigurationParser<T, U> {
  Source getXmlSchema() throws IOException;

  URI getNamespace();

  Parser<ServiceCreationConfiguration<T>> serviceCreationConfigurationParser();

  Parser<ServiceConfiguration<T>> serviceConfigurationParser();

  Parser<ResourcePool> resourcePoolParser(Element element);
}
```

**Comment by chrisdennis** [comment]
@albinsuresh Do you think this is still a valid/sensible thing to do?  If not could you close it.

**Comment by albinsuresh** [comment]
It definitely can be improved/simplified but I guess it's not worth the time and effort at this point since the value addition is minimal. So let's close it for now and revist later if there's interest.
