### ISSUE TITLE
Replace gradle with maven

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#905]

**Comment by cschanck** [comment]
+1

**Comment by GaryWKeim** [comment]
+2

**Comment by ljacomet** [comment]
I understand Gradle is a different tool, which means a learning curve again.

Having `mavenLocal()` declared in the repositories was a mistake and PRs are up to fix that. The right way is to go with a [local init scripts](https://docs.gradle.org/current/userguide/init_scripts.html#N14A03) for devs having to integrate development on an Ehcache 3 dependency with Ehcache 3 dev itself.

The same technique could probably resolve the request from issue #734 - ping @mathieucarbou.

**Comment by mathieucarbou** [comment]
@lorban : see m'y workaround when I need thé poms: 

https://gist.github.com/mathieucarbou/fb791e084995bb5c12ffd817608c753d

`curl -Ls https://goo.gl/qIapwy | sh`
