### ISSUE TITLE
Test with Hibernate

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#913]
We should make sure that ehcache 3 works flawlessly as a Hibernate 2LC.

All Hibernate cache modes are supported so they should all be tested: read-only, read-write, nonstrict-read-write and transactional.

**Comment by chrisdennis** [comment]
I think a functional H2LC implementation would be dependent on this branch getting merged in: https://github.com/alexsnaps/hibernate-orm/tree/jsr107

**Comment by chrisdennis** [comment]
Non-issue - Ehcache 3 integration in Hibernate is through the 107 module.
