### ISSUE TITLE
One of Ehcache or EhcacheWithLoaderWriter duplicates the CacheEntryIterator class

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#915]
Both Ehcache and EhcacheWithLoaderWriter contain the CacheEntryIterator class, one of these is a duplicate.  Maybe we could eliminate this duplication by creating a common superclass?

**Comment by ljacomet** [comment]
Depends on #880

**Comment by chrisdennis** [comment]
Fixed in #2217
