### ISSUE TITLE
Review memoization of functions passed to OffHeap and Disk stores

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#920]
The offheap and disk stores can both end up needing to call the functions passed to the compute methods multiple times.  It is believed this is safe because despite some of these functions having side affects as the functions are memoized.  This should be carefully validated, otherwise we could see some very hard to diagnose bugs out in the wild.

**Comment by ljacomet** [comment]
Needs investigation and listing all issues so that they can be prioritised.

**Comment by chrisdennis** [comment]
Reviewed current code and filed #1055 and #1056.

**Comment by chrisdennis** [comment]
Missed a bunch of cases...

**Comment by chrisdennis** [comment]
Added #1058 in addition.
