### ISSUE TITLE
Transactional Caches currently ignore user defined vetoes

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#923]
The transaction code currently ignore user defined eviction veto functions.  I think this might be as simple as the used veto function being a logical or of the users veto with the xa veto.

**Comment by ljacomet** [comment]
Created some high level [design docs](https://github.com/ehcache/ehcache3/wiki/module.xa) around XA caches.
I believe there is no reason to not support user specified vetoes.
