### ISSUE TITLE
Confirm Correctness issues in some Ehcache unit tests

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#930]
There are still a bunch of "Confirm Correctness TODOs left over from #147.  These should be inspected to validate whether there is anything needing fixing here:

https://github.com/ehcache/ehcache3/blob/77a8ba2d1b1384799a690cdc213b87c6132ae007/core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicPutIfAbsentTest.java#L212
https://github.com/ehcache/ehcache3/blob/77a8ba2d1b1384799a690cdc213b87c6132ae007/core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicPutIfAbsentTest.java#L241
https://github.com/ehcache/ehcache3/blob/77a8ba2d1b1384799a690cdc213b87c6132ae007/core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicPutIfAbsentTest.java#L346

https://github.com/ehcache/ehcache3/blob/77a8ba2d1b1384799a690cdc213b87c6132ae007/core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicRemoveValueTest.java#L481
https://github.com/ehcache/ehcache3/blob/77a8ba2d1b1384799a690cdc213b87c6132ae007/core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicRemoveValueTest.java#L603

https://github.com/ehcache/ehcache3/blob/77a8ba2d1b1384799a690cdc213b87c6132ae007/core/src/test/java/org/ehcache/core/EhcacheWithLoaderWriterBasicReplaceValueTest.java#L795

**Comment by ljacomet** [comment]
1. Behaviour exposed by test is expected - stats indicates a cache failure even though the operation completes normally for the user as we could recover from the errors.
2. Same as previous
3. Same as previous

However for all three points above an assertion on the `putIfAbsent` return was missing and there was a bug hiding there. While we would _recover_ internally, we were not returning the proper result:
* previous value when value loaded,
* `null` when value written

**Comment by ljacomet** [comment]
* For 4: Correct, without LoaderWriter error, we should obey the SoR state - no remove since value do not match
* For 5: Same as 1 to 3

Although reviewing these tests and knowing about the issues found for putIfAbsent, I added some assertions on the remove return value.

**Comment by ljacomet** [comment]
For 6, the behaviour is consistent with all other code path - we never record a stat event when exiting from a Cache method on a `CacheLoadingException` or `CacheWritingException`.
