### ISSUE TITLE
getEvictionCandidate() is very expensive on heap tier

### ISSUE THREAD

**Issue by skbansal** [ehcache/ehcache3#932]
I have noticed that getEvictionCandidate() itself is taking 1/3rd of total elapsed time for a get() call.

Test case
Ehcache : 3-RC2
R:W = 90:10
Element : (Long,ByteArray[])
XMS,XMX : 4G
Tier : Heap (10mb), offHeap(4G)

Here are some stats from profiling
store.heap.OnHeapStore.evict(StoreEventSink) 57.054%
    org.ehcache.impl.internal.store.heap.SimpleBackend.getEvictionCandidate()   31.008%
      concurrent.ConcurrentHashMap.getEvictionCandidate()26.528%
         concurrent.ConcurrentHashMap$Traverser.advance()10.647%
         concurrent.ConcurrentHashMap.getEvictionCandidateWrap()10.432%

**Comment by ljacomet** [comment]
This rings a bell but for a get() call it seems really weird as a get will never trigger eviction.

**Comment by lorban** [comment]
It can happen on a 100% read-only use-case *if* you configured multiple tiers though.

**Comment by ljacomet** [comment]
Indeed, my bad!

**Comment by skbansal** [comment]
My usecase in 90% get() and 10% put(), but still I am seeing this.

Does it mean, call is specific to usecase? 100% get or 90%?

**Comment by ljacomet** [comment]
No, in a multi tier cache, eviction will happens when a hotter entry is faulted inside the heap tier causing it to evict. And this will indeed happen on the get path.

**Comment by chrisdennis** [comment]
This is 90% read, 4Gb of offheap, and 10MB of heap.  I’m guessing the distribution is relatively flat.  It’s just missing in heap all the time, faulting from offheap and having to evict from the heap, to satisfy the put.  This is the perfect use case for one of Ludovics offheap only caches.

**Comment by skbansal** [comment]
Tried offheap only and disk only caches. It executed successfully.

Performance stats are much better i.e. 80%.

It is (10-15% improved) as compared to Ehcache2 (minimal heap and major portion in offheap only) also

**Comment by chrisdennis** [comment]
There are other performance related issues that capture the problems with the heap tiers... this is more just a misconfiguration. Closing.
