### ISSUE TITLE
Registering a CharSequence serializer make you still get the bundled StringSerializer if you configure a cache of strings

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#937]
There currently is no way to register a serializer for CharSequence that would get used for a cache of String (key, value or both, it doesn't matter) as the bundled StringSerializer is always going to take precedence.

The same is true for Number and bundled LongSerializer and friends.

**Comment by ljacomet** [comment]
This is now [properly documented](http://www.ehcache.org/documentation/3.0/serializers-copiers.html#serializers-bundled) and there is no intention of fixing that.
