### ISSUE TITLE
Clustered Ehcache Operations Caching Research Spike

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#941]
Research spike on how we want the client side caching to work in Ehcache... focus here is on two main things.  When are cache invalidations sent from the server, and how is the caching logic/layering used in clustered related to the caching layers used in unclustered.  Ideally I would like this to use as much of the same code as possible.

**Comment by ljacomet** [comment]
Some of the discussion for this happened under #919, but I have come to realise it is wrong.

#919 should focus on wiring emergency valve in 3.0 if we need that, without API changes.

In the context here, I propose the following first step:
* Introduction of the `InvalidationValve` - #1030

**Comment by ljacomet** [comment]
Will use this issue to extend the `ClusteredStore` to be an `AuthoritativeTier`. From what is known, the standard tiering model should apply for cluster just as well.

**Comment by ljacomet** [comment]
Actually #1043 exists for that, thus closing this.
