### ISSUE TITLE
XML configuration extension may need access to user land class loader

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#942]
Currently, any XML configuration extension will only know about the class loader that created it.

Usage patterns may require access to other ones, the Ehcache main one or the user provided one.

For example, following the changes done in #850, user class may need to be resolved from the transaction XML extension.

Investigation needs to confirm this and depending on the result some XML extension SPI changes may be required.

**Comment by chrisdennis** [comment]
I think this is all "correct" now... `ServiceCreationConfiguration` parsers get the managers classloader, `ServiceConfiguration` parsers get the cache's classloader. If there are other needed loaders then it's up to the implementation to feed them wherever they need to go.
