### ISSUE TITLE
API to get complete Ehcache configuration in text format

### ISSUE THREAD

**Issue by skbansal** [ehcache/ehcache3#951]
It will be helpful if we can get an API which will give us the complete Ehcache Configuration in text format (Probably xml).

This will be helpful for debugging purpose and sharing the configuration among Ehcache users.

**Comment by chrisdennis** [comment]
I think this is a good idea... but I would vote for not XML.

**Comment by skbansal** [comment]
XMLs are easy to parse (using some standard parsers) and help in understanding the tree structure.

Moreover, for debugging, I could just use the same XML and can create original like configuration to debug/reproduce the issue with 0% error rate.

**Comment by chrisdennis** [comment]
The set of all programatic configurations is larger than the universe of all XML configurations... not every one is mappable.

> Moreover, for debugging, I could just use the same XML and can create original like configuration to debug/reproduce the issue with 0% error rate.

Do we really want to make that a goal/feature?  It's a pretty lofty one, and one that caused us pain in the past.  I'd want to see a strong use case for this.

**Comment by ljacomet** [comment]
After discussion with @mathieucarbou, there is some need to be able to visualise configuration, without ever thinking about XML format.
In this context, the work for this enhancement is to created a _formatted_ `String` out of the `Configuration` object and its graph.

This should give us a valid `String` representation from the `Cache` level as well.
