### ISSUE TITLE
Investigate XSD update following changes around resources

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#959]
In short we want the definition of at least one resource between a cache and a template definition.

But thinking about it, I realise this may not be possible to express in XSD.

Still filing this to keep track of the conclusion for the future.

**Comment by chrisdennis** [comment]
You want to enforce that the result of resolving each configuration against it's configured template contains at least one resource?  If so, I'm pretty sure that requires:
![Schematron](http://i.stack.imgur.com/53S46.jpg)

**Comment by ljacomet** [comment]
Indeed - closing as not resolving
