### ISSUE TITLE
EvictionVeto: rename and complete documentation

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#962]
The `EvictionVeto.vetoes` names are misleading in the sense that we will only take the result as a hint for eviction, nothing stronger.
Also, the current documentation does not indicate that the state is resolved when the mapping is written to the cache, not when it is a potential eviction candidate.

So this issue leads to:
* A potential rename of the type and the method
* Improved documentation that clarifies implementation should not have any time related factors in the decision that are expected to be evaluated during eviction itself.

**Comment by lorban** [comment]
wiki doc that needs to be updated too: https://github.com/ehcache/ehcache3/wiki/module.xa
