### ISSUE TITLE
result is different every time

### ISSUE THREAD

**Issue by whaon** [ehcache/ehcache3#990]
Cache<Long, String> ce = myCacheManager.getCache("cache", Long.class, String.class);
		ce.put(1L, "a");
		ce.put(2L, "b");
		ce.put(3L, "c");
		System.out.println(ce.get(1L)); // a
		System.out.println(ce.get(2L));// b
		System.out.println(ce.get(3L));// c

as the code above,the expiry is none,the entry size is 2, but the result is uncertain,line a,line b and line c are all could get null,does it have any problem?

**Comment by ljacomet** [comment]
Hello,

Thank you for your interest in Ehcache 3.

Note that the preferred channel for such questions is the google user group [ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users).

Now, to your question, yes it is perfectly normal. [Eviction](http://www.ehcache.org/documentation/3.0/caching-terms.html#eviction) is what makes sure the cache never goes above capacity. And this process is sample based and tailored for large caches.

So there is indeed no guaranteed eviction of a specific entry with the case presented here.

Remember, Ehcache is a caching product and will evict when it needs to. It cannot act as a memory store, you need to have another way (probably slower) to recover what is not cached.

**Comment by whaon** [comment]
thanks for your answer
Does ehcache 3.0 provider the eviction stratey? like FIFO,LRU,LFU?
Or it manage the behaviou itself and no need for us to configurate?

**Comment by terracotta-org** [comment]
Sorry, I missed that follow up question.

Ehcache 3.0 does not expose any configuration of the underlying eviction policy, this is all internal and actually depends on the tiering configuration.

**Comment by ljacomet** [comment]
Sorry, I missed that follow up question.

Ehcache 3.0 does not expose any configuration of the underlying eviction policy, this is all internal and actually depends on the tiering configuration.

{fixed to use proper user - sorry about that}
