### ISSUE TITLE
Enable statistics via (xml) configuration

### ISSUE THREAD

**Issue by snicoll** [ehcache/ehcache3#992]
When using JSR-107, it looks like there is no configuration alternative for `setStatisticsEnabled` on `MutableConfiguration`.

I am working on a sample where I bootstrap `javax.cache.CacheManager` with the URI to [a configuration file](https://github.com/spring-projects/spring-boot/blob/0cfcbeb40e075da9baa6bb85c15ceceacb5695c4/spring-boot-samples/spring-boot-sample-cache/src/main/resources/ehcache3.xml). I'd like to be able to enable statistics there as well.

**Comment by ljacomet** [comment]
Thanks for the report @snicoll 

That looks like an oversight indeed. And I believe the equivalent should be available to enable management (`MutableConfiguration.setManagementEnabled`).
