### ISSUE TITLE
Server Store Proxy Impl

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#994]
Implementation of the ServerStoreProxy interface, including the necessary Voltron messaging code (marshall and unmarshall) to interface with the server side ServerStore implementation.

**Comment by AbfrmBlr** [comment]
Had a discussion with @albinsuresh @rkavanap @itsroshan, @ljacomet  & sairam and no one seems to like this switch/case thing. This needs refactoring and statics needs to go.Will be taken in further PRs.
