### ISSUE TITLE
ehcache v3 set setTimeToIdleSeconds without use xml config

### ISSUE THREAD

**Issue by marti1125** [ehcache/ehcache3#995]
I didn't find an example like this http://www.programcreek.com/java-api-examples/index.php?api=net.sf.ehcache.config.CacheConfiguration

**Comment by ljacomet** [comment]
Hi,

Thanks for your interest in Ehcache 3.

For this kind of questions, we recommend using the [ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) google group.

Now, to answer your question:
Ehcache 3 is a complete rework of the API.

What you are looking for can be done as follows:
```java
CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, Person.class,
    ResourcePoolsBuilder.newResourcePoolsBuilder().heap(10, EntryUnit.ENTRIES))
    .withExpiry(Expirations.timeToIdleExpiration(new Duration(10, TimeUnit.SECONDS)));
```
Please refer to the [rest of the documentation](http://www.ehcache.org/documentation/3.0/getting-started.html) for interactions between cache configurations and cache managers.

Thanks to your question I realised this is a topic left out of the Getting Started documentation and that is a mistake that needs fixing.

**Comment by marti1125** [comment]
@ljacomet Thanks!! =D how to I can help you?

**Comment by ljacomet** [comment]
Keep on reporting missing documentation topics, that would help for sure.

**Comment by marti1125** [comment]
I would like to add eternal false http://techblog.constantcontact.com/software-development/solving-a-classic-ehcache-problem-retrieving-expired-data/

**Comment by lorban** [comment]
In Ehcache 3, there is no such thing as 'eternal'. Simply configuring an expiry (using `CacheConfigurationBuilder.withExpiry(...)`) will make your configured expiry policy taken into account by the cache.
